### ISSUE TITLE
Version-clash in LSTM-CRF model

### ISSUE THREAD

**Issue by sflin** [amaiya/ktrain#101]
Hi amaiya
I try to run the [Sequence-Tagging Tutorial](https://github.com/amaiya/ktrain/blob/master/tutorials/tutorial-06-sequence-tagging.ipynb) with an LSTM-CRF-model. However, when running the first few cells of the notebook it complains about the versions:
```
Exception                                 Traceback (most recent call last)
<ipython-input-3-d851226d5f91> in <module>()
----> 1 import ktrain
      2 from ktrain import text

1 frames
/usr/local/lib/python3.6/dist-packages/ktrain/imports.py in <module>()
     49 
     50 if version.parse(tf.__version__) < version.parse('2.0'):
---> 51     raise Exception('As of v0.8.x, ktrain needs TensorFlow 2. Please upgrade TensorFlow.')
     52 
     53 os.environ['TF_KERAS'] = '1' # to use keras_bert package below with tf.Keras

Exception: As of v0.8.x, ktrain needs TensorFlow 2. Please upgrade TensorFlow.
```
Is there a step I miss?
Many thanks in advance

**Comment by amaiya** [comment]
*ktrain* requires TensorFlow 2. Please upgrade TensorFlow to TensorFlow 2 (preferably 2.1.0).

IF you're on Google Colab, you can do this: `!pip3 install tensorflow_gpu==2.1.0`.

`

**Comment by sflin** [comment]
Thanks, I'm aware of that but in your tutorial you're writing:

> ktrain currently uses the CRF module from keras_contrib, which is not yet fully compatible with TensorFlow 2. To use the BiLSTM-CRF model (which currently requires keras_contrib) for sequence-tagging in ktrain, you must **disable V2 behavior in TensorFlow 2** by adding the following line to the top of your notebook or script before importing ktrain.

and then in the second cell:
`os.environ['DISABLE_V2_BEHAVIOR'] = '1'`

**Comment by amaiya** [comment]
The error message should not occur if you're using TensorFlow 2 and add the `os.environ['DISABLE_V2_BEHAVIOR']='1' at the top as shown in the tutorial.

Can you please provide more information on what the issue is? What version of TF are you using? Are you getting this error despite following steps above? Or, are you trying to find out why the tutorial can't be run on TF1.x? Thanks

**Comment by sflin** [comment]
Ah I resolved the error now. I got confused with the disabling V2-behaviour and downgraded my tensorflow beforehand. That's not necessary. Thanks!
