### ISSUE TITLE
[Question] how to put log for debug?

### ISSUE THREAD

**Issue by zirubak** [amaiya/ktrain#102]
Hi~ 

I try to put some log message for debugging but it doesn't show up. :(
I hope ktrain has slack ch. for asking someone to this general question. 

Here is my trial steps:
1. put warnings message
warnings.warn('I want to debug')
OR
print('I want to debug')

2. build and install
$ python setup.py build -f
$ python setup.py install -f

3. import ktrain
4. run code

But I can't see any printed message.
Could you someone please advise how to debug? 

PS: Ktrain has Slack ch?

**Comment by amaiya** [comment]
There are print and warning statements throughout the library, so not sure why the ones you added are not showing up.  That said, *ktrain* does suppress some TF warning messages by default.  To see them, you can add this to the top of your script or notebook:
```
import os
os.environ['SUPPRESS_TF_WARNINGS'] = '0'
```
Don't see how this would affect your print/warning statements, though.

We're using GitHub Issues as a help forum for right now, so you can continue posting questions here for now. Thanks.
