### ISSUE TITLE
preprocess

### ISSUE THREAD

**Issue by gogokre** [amaiya/ktrain#104]
preprocessing train...
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-23-7a63d7df94b4> in <module>()
      1 
----> 2 trn = t.preprocess_train(x_train, y_train)
      3 val = t.preprocess_test(x_test, y_test)

2 frames
/usr/local/lib/python3.6/dist-packages/ktrain/text/textutils.py in detect_lang(texts, sample_size)
    204             continue
    205     if len(lst) == 0:
--> 206         raise Exception('could not detect language in random sample of %s docs. Are you sure you provided a list of strings?'  % (sample_size))
    207     return max(set(lst), key=lst.count)
    208 

Exception: could not detect language in random sample of 32 docs. Are you sure you provided a list of strings?

-------

I want to learn by entering numeric text, but it floats like this. What should I do?

**Comment by amaiya** [comment]
What do you mean by "numeric text"?  Please provide examples from your `x_train`  that you're supplying to `preprocess_train`.

**Comment by amaiya** [comment]
In v13.0 of *ktrain*, the error has been changed to a warning and fallbacks to `lang='en'` in this case when language can't be detected.
