### ISSUE TITLE
'BERTPreprocessor' object has no attribute 'preprocess_train_called'

### ISSUE THREAD

**Issue by cvantass** [amaiya/ktrain#105]
I've successfully loaded my preprocessor object with ktrain.load_predictor(/path/to/file), however, when it comes time to make a prediction on the text and I call .predict(text), I get this error:

`AttributeError: 'BERTPreprocessor' object has no attribute 'preprocess_train_called'`

I followed the traceback and looked into the scripts, but I still can't figure out why I'm getting this. It looks like the only argument required for this to work is the texts argument, which is definitely provided in my case.

Some context in case it helps:
I had originally created the .preproc file and the associated classifier file in Google Colab a couple months back. I just downloaded those two files and saved them onto my own machine today to replicate the predictor I had built in Google Colab (which used to work completely fine, but is now also giving me the same exact error). I upgraded both ktrain and tensorflow today before running and both upgrades were successful. Could it be that in between the time I created the original files and the time I downloaded them today, the scripts were updated to include the preprocess_train_called attribute? That's my only thought. Any ideas?

Thanks!

**Comment by amaiya** [comment]
Yes, I think you're probably right.  There have been several new releases between the time your originally created your files and now.  There a few things you can try:

1. Install the same version of *ktrain* you used originally on Google colab
2. Using the current version of *krain*, re-create the `preproc` object from a scratch and replace the old preproc with the new one.  To do this, you just re-call the data-loading function (e.g., `texts_from_folder`, `texts_from_array`, etc.).

If all else fails, you can just retrain and re-create the predictor files (model and preproc), which is the ML equivalent of rebooting your computer.

**Comment by amaiya** [comment]
Today, I encountered this same problem in one of the unit tests.  I solved it by re-training the model and re-creating the predictor objects.  But, downgrading ktrain or re-generating and replacing just the `preproc` object should also work.

Will close this issue. Thanks.
