### ISSUE TITLE
AttributeError: 'IndexTransformer' object has no attribute 'te_model'

### ISSUE THREAD

**Issue by sflin** [amaiya/ktrain#107]
When trying to load an existing predictor self.te_model (l. 72) as well as self.use_elmo (l.75) are not defined:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-98367c1062a6> in <module>()
----> 1 pred3 = ktrain.load_predictor('/content/drive/My Drive/MT/predictor')

1 frames
/usr/local/lib/python3.6/dist-packages/ktrain/text/ner/anago/preprocessing.py in __setstate__(self, state)
     70     def __setstate__(self, state):
     71         self.__dict__.update(state)
---> 72         if self.te_model is not None: self.activate_transformer(self.te_model, layers=self.te_layers)
     73         else:
     74             self.te = None

AttributeError: 'IndexTransformer' object has no attribute 'te_model'
```

**Comment by amaiya** [comment]
In the latest release, the `NERPreprocessor` object was updated to include BERT and Elmo embeddings - neither of which existed when you originally saved your `NERPreprocessor` instance.    To resolve this error, you can do one of the following:


1. Using the current version of krain (v0.12.0), re-create the `preproc` object from a scratch and replace the old `preproc` you previously saved with the new one. To do this, you just re-call the data-loading function (e.g., texts_from_folder, texts_from_array, etc.).
2. Install the same version of ktrain you used originally (not recommended)
3. Re-train and re-invoke `predictor.save` using the newer version of *ktrain*, if all else fails.

**Comment by amaiya** [comment]
In 0.12.3, I've made a slight change so that the changes are backwards compatible with previously-saved preproc objects. Hopefully, the existing predictor should load.
