### ISSUE TITLE
Is it possible to use pyLDAvis to visualize Topic Modelling from ktrain

### ISSUE THREAD

**Issue by WeiyangSun** [amaiya/ktrain#111]
Hi,

I am trying to use pyLDAvis to visualize the topic model from ktrain (in addition to the inbuilt visualize_documents function already existing).

In order to do this, I need 5 things: 1. topic term distribution, 2. document topic distributions, 3. document lengths, 4. vocabulary and 5. term frequency.

I was wondering if there is any way of retrieving these information from the ktrain function for topic modeling.

Thanks.

**Comment by amaiya** [comment]
Yes, you can easily visualize the ktrain `TopicModel` with  **pyLDAvis**.

If `tm` is the ktrain `TopicModel` object, then `tm.model` is the LDA model and `tm.vectorizer` is the vectorizer.  From those, you can access or derive all the things you need.

pyLDAvis has an sklearn module that makes it easy.  This worked for me (visualization is available at ```localhost:8888```):

```python
import ktrain
import pyLDAvis
import pyLDAvis.sklearn

# collect data
from sklearn.datasets import fetch_20newsgroups
remove = ('headers', 'footers', 'quotes')
newsgroups_train = fetch_20newsgroups(subset='train', remove=remove)
newsgroups_test = fetch_20newsgroups(subset='test', remove=remove)
texts = newsgroups_train.data +  newsgroups_test.data

# build model
tm = ktrain.text.get_topic_model(texts, n_features=10000, n_topics=75)

# visualize
dtm = tm.vectorizer.fit_transform(texts) 
prepared = pyLDAvis.sklearn.prepare(tm.model, dtm, tm.vectorizer)
pyLDAvis.show(prepared, port=8888)
```
