### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by basque21** [amaiya/ktrain#113]
Hi, I'm running in an error when importing the library. I'm getting this:

```
ImportError: dlopen: cannot load any more object with static TLS
___________________________________________________________________________
Contents of /var/lib/jupyter/.local/lib/python3.6/site-packages/sklearn/__check_build:
__init__.py               setup.py                  __pycache__
_check_build.cpython-36m-x86_64-linux-gnu.so
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.
```

I had a similar issue with pytorch, and i could solve it importing first sklearn and then torch, but if I try to do so my kernel is dying. I know this is not your issue, but could you help me, please? I'm amazed with the library and can't use it :(

**Comment by amaiya** [comment]
Hi: Happy to try to help.

When you google this error, all references are related to PyTorch, not TensorFlow.  I have a feeling this is a PyTorch issue.  The reason it might be coming up here, is because *ktrain* uses the AllenNLP library (which uses PyTorch) to generate Elmo embeddings.

Do you by, any chance, have `allennlp` installed on your system?    If so, *ktrain* may be trying to import PyTorch indirectly.  **Can you try uninstalling allennlp and see if the problem occurs?**

Otherwise, have you tried uninstalling and  re-installing `scikit-learn`?

What OS/system are you using?

Does the kernel die simply by importing scikit-learn and nothing else?

**Comment by basque21** [comment]
Hi! thanks for early answering! I'm going to answer your questions:
- I don't have `allennlp` package installed on pip.
- I tried uninstalling scikit-learn and installing from source, but the problem persists.
- I'm using a linux debian OS, exactly ` 'Linux-3.16.0-4-amd64-x86_64-with-debian-8.7'`
- If I import first `sklearn` and then ktrain the kernel is dying without any python error, but if I try to import first ktrain I'm getting the error mentioned above.

I have seen that some people solved this kind of problem (with other libraries, not only with PyTorch) importing firstly `cv2` library. I'm trying to do so, but I'm getting the same error...

**Comment by amaiya** [comment]
Have you tried installing scikit-learn with pip?  `pip3 install scikit-learn==0.21.3`.

Included an older version of scikit-learn in the above command also.

**Comment by basque21** [comment]
yes, I tried with pip and from source, none of them worked, same error...

**Comment by amaiya** [comment]
Perhaps you can try installing from scratch in a virtual environment without Jupyter notebook to see what happens. On the command-line, do the following:

```
$ python3 -m venv mytestenv
$ cd mytestenv
$ source bin/activate
$ pip3 install -U pip
$ pip3 install tensorflow==2.1.0
$ pip3 install ktrain
```
After doing the above, run `ipython` and try importing `ktrain` and/or `scikit-learn`.  What happens?

Make sure you are in  your virtual environment when you run `ipython`.

**Comment by basque21** [comment]
This solved my problem! Thanks!!
