### ISSUE TITLE
ktrain not installing - PEP 517 Error

### ISSUE THREAD

**Issue by samwalkow** [amaiya/ktrain#114]
Hi, 

I'm trying to install ktrain to my base environment and I get this error:

<img width="660" alt="Screen Shot 2020-04-07 at 10 52 42 AM" src="https://user-images.githubusercontent.com/38114494/78691417-336b2280-78be-11ea-8adb-beec356f238d.png">

I'm on a mac mojave OS, python version 3.7.3, and pip3 version 20.0.2. I tried installing it in my terminal and in a jupyter notebook with no luck. I appreciate any help!

**Comment by amaiya** [comment]
Hi there:  

Everything works on Linux (and Windows according to users), so it may be a Mac issue.  Moreover, it appears to be an issue with the `transformers` library.  See [this issue  on the `transformers` GitHub repo](https://github.com/huggingface/transformers/issues/2831), which describes the issue and various proposed solutions.

[This post](https://github.com/huggingface/transformers/issues/2831#issuecomment-592724471), in particular, describes a solution for Mac users that appears to work based on the number of people who "liked" the post.  The post says:

> Hi, I had the same problem and resolved it by installing rust.
"error: Can not find Rust compiler"

> For MacOS, I used "curl https://sh.rustup.rs -sSf | sh". I also found that it needed a nightly version of rust, so you have to specify that in the install options.

Can you give this a shot to see if it solves the problem?

**Comment by amaiya** [comment]
[This solution](https://github.com/huggingface/transformers/issues/2831#issuecomment-595486000) or [this solution](https://github.com/huggingface/transformers/issues/2831#issuecomment-600141935) may also work based on comments in the thread.

**Comment by samwalkow** [comment]
https://github.com/huggingface/transformers/issues/2831#issuecomment-595486000 - this solution worked for me! 

I did have some more errors regarding the 'wrapt' library, but I was able upgrade and solve that issue. I still see some tensorflow related errors, but I can still import the ktrain into my jupyter notebook and it seems to be working. 

Thanks so much for your help!
