### ISSUE TITLE
 Exception: could not detect language in random sample of 32 docs. Are you sure you provided a list of strings?

### ISSUE THREAD

**Issue by bindulam** [amaiya/ktrain#115]
getting this error when i am trying to pre-process it
"
Exception: could not detect language in random sample of 32 docs. Are you sure you provided a list of strings?

"

**Comment by amaiya** [comment]
Are you providing a list of strings?

You haven't shared the code you're using.  But, assuming you're preprocessing the data with `t.preprocess_train(x_train...)` or something like `texts_from_array(x_train...)`, what do the values of `x_train` look like?

**Comment by amaiya** [comment]
Not sure if you resolved this, but the error was turned into a warning in the latest version.  If language can't be detected, it defaults to English.
