### ISSUE TITLE
Does ktrain supports training on multiple GPUs or TPU

### ISSUE THREAD

**Issue by tuner007** [amaiya/ktrain#122]
I want to try out a classification problem with multiple GPUs or TPU, can someone guide me here. 

Thanks !

**Comment by amaiya** [comment]
Multi-GPU training in TensorFlow2 involves placing a model within the scope of a Strategy.     For training on two GPUs, for example, you can do this:

```python
# use two GPUs to train
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID";
os.environ["CUDA_VISIBLE_DEVICES"]="0,1";  

# load text data
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
from sklearn.datasets import fetch_20newsgroups
train_b = fetch_20newsgroups(subset='train', categories=categories, shuffle=True)
test_b = fetch_20newsgroups(subset='test',categories=categories, shuffle=True)
(x_train, y_train) = (train_b.data, train_b.target)
(x_test, y_test) = (test_b.data, test_b.target)

# build, train, and validate model
import tensorflow as tf
mirrored_strategy = tf.distribute.MirroredStrategy()
import ktrain
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
with mirrored_strategy.scope():
    model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, batch_size=6)
learner.fit_onecycle(5e-5, 2)
learner.save_model('/tmp/my_model')
learner.load_model('/tmp/my_model', preproc=t)
learner.validate(val_data=val, class_names=t.get_classes())
```

However, as described in [this thread](https://github.com/amaiya/ktrain/issues/78), there were some TensorFlow 2 bugs that cause some issues (E.g., with validation, using more than 2 GPUs).  It may work better in the newest, unreleased version of TF.

I have not tried TPU training yet, but it involves [converting a tf.Keras model to a TPU model](https://www.dlology.com/blog/how-to-train-keras-model-x20-times-faster-with-tpu-for-free/) and training normally.  I have not tested supplying a TPU model to `Learner` yet.  If you try and experience problems, you can open an issue and I will try to resolve.

**Comment by tuner007** [comment]
> Multi-GPU training in TensorFlow2 involves placing a model within the scope of a Strategy. For training on two GPUs, for example, you can do this:
> 
> ```python
> # use two GPUs to train
> import os
> os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID";
> os.environ["CUDA_VISIBLE_DEVICES"]="0,1";  
> 
> # load text data
> categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
> from sklearn.datasets import fetch_20newsgroups
> train_b = fetch_20newsgroups(subset='train', categories=categories, shuffle=True)
> test_b = fetch_20newsgroups(subset='test',categories=categories, shuffle=True)
> (x_train, y_train) = (train_b.data, train_b.target)
> (x_test, y_test) = (test_b.data, test_b.target)
> 
> # build, train, and validate model
> import tensorflow as tf
> mirrored_strategy = tf.distribute.MirroredStrategy()
> import ktrain
> from ktrain import text
> MODEL_NAME = 'distilbert-base-uncased'
> t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names)
> trn = t.preprocess_train(x_train, y_train)
> val = t.preprocess_test(x_test, y_test)
> with mirrored_strategy.scope():
>     model = t.get_classifier()
> learner = ktrain.get_learner(model, train_data=trn, batch_size=6)
> learner.fit_onecycle(5e-5, 2)
> learner.save_model('/tmp/my_model')
> learner.load_model('/tmp/my_model', preproc=t)
> learner.validate(val_data=val, class_names=t.get_classes())
> ```
> 
> However, as described in [this thread](https://github.com/amaiya/ktrain/issues/78), there were some TensorFlow 2 bugs that cause some issues (E.g., with validation, using more than 2 GPUs). It may work better in the newest, unreleased version of TF.
> 
> I have not tried TPU training yet, but it involves [converting a tf.Keras model to a TPU model](https://www.dlology.com/blog/how-to-train-keras-model-x20-times-faster-with-tpu-for-free/) and training normally. I have not tested supplying a TPU model to `Learner` yet. If you try and experience problems, you can open an issue and I will try to resolve.

Thanks for quick response. Will try it with latest version of TF.

Also, when i tried training a Transformer model with Transformer wrapper i am not able to use GPU, if i am not wrong i can use **s.environ["CUDA_VISIBLE_DEVICES"]="0,1";** to force script to use GPU but still was not able to do so.

How can i force it to use GPU for training ? 
Thanks !

**Comment by agn-7** [comment]
@amaiya 
Is the following section needed in google-colab? or only set GPU as runtime is enough?

```
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID";
os.environ["CUDA_VISIBLE_DEVICES"]="0,1";  
```

**Comment by amaiya** [comment]
@agn-7 Those lines are not needed on Google Colab, as demonstrated in the example Colab notebooks in the README.  Thanks.

**Comment by warlord798** [comment]
@amaiya actually using a TPU as the scope of the strategy will throw an error, I tried the following code on Colab:

```
import ktrain
from ktrain import text
import tensorflow as tf
import os

tpu = tf.distribute.cluster_resolver.TPUClusterResolver()
tf.config.experimental_connect_to_cluster(tpu)
tf.tpu.experimental.initialize_tpu_system(tpu)

strategy = tf.distribute.experimental.TPUStrategy(tpu)
MODEL_NAME = 'distilbert-base-uncased'


with strategy.scope():
  t = text.Transformer(MODEL_NAME, maxlen=500, classes=["r","d"])
  
  trn = t.preprocess_train(x_train, y_train)
  
  val = t.preprocess_test(x_test, y_test)
  
  model = t.get_classifier()
  
  learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
```

and the error will appear when fitting(I used fit_onecycle):
begin training using onecycle policy with max lr of 5e-05...
Epoch 1/4
---------------------------------------------------------------------------
UnavailableError                          Traceback (most recent call last)
<ipython-input-8-303abc2d34ec> in <module>()
----> 1 learner.fit_onecycle(5e-5, 4)

15 frames
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

UnavailableError: 8 root error(s) found.
  (0) Unavailable: {{function_node __inference_train_function_31110}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1613421778.853934807","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1613421778.846075746","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[IteratorGetNext_1]]
	 [[IteratorGetNext_1/_10]]
  (1) Unavailable: {{function_node __inference_train_function_31110}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1613421778.853934807","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1613421778.846075746","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[IteratorGetNext_1]]
	 [[strided_slice_109/_150]]
  (2) Unavailable: {{function_node __inference_train_function_31110}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1613421778.853934807","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1613421778.846075746","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[IteratorGetNext_1]]
	 [[Pad_20/_164]]
  (3) Unavailable: {{function_node __inference_train_function_31110}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1613421778.853934807","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1613421778.846075746","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[IteratorGetNext_1]]
	 [[Pad_13/_102]]
  (4) Unavailable: {{function_node __inference_train_function_31110}} failed to connect to all addresses
Additio ... [truncated]

**Comment by amaiya** [comment]
@warlord798 It sounds like it may be related to [this open TensorFlow issue](https://github.com/tensorflow/tensorflow/issues/43037), which may be an incompatibility with `transformers`.
