### ISSUE TITLE
Error Visualizing Documents

### ISSUE THREAD

**Issue by samwalkow** [amaiya/ktrain#124]
Hello, 

I'm encountering an error when trying to visualize the results of my topic modeling code.

Here's my code:

```
ktrain.text.preprocessor.detect_lang = ktrain.text.textutils.detect_lang
df = df_ts_id
texts = df['cleaner_text']
tm = ktrain.text.get_topic_model(texts, n_topics=None, n_features=10000)

tm.print_topics()
tm.build(texts, threshold=0.25)

texts = tm.filter(texts)
df = tm.filter(df)

tm.visualize_documents(doc_topics=tm.get_doctopics())
```

And I'm getting this error:
<img width="1111" alt="Screen Shot 2020-04-17 at 11 07 39 AM" src="https://user-images.githubusercontent.com/38114494/79590234-548cf980-809c-11ea-9d12-4d58fc7527cc.png">
<img width="1066" alt="Screen Shot 2020-04-17 at 11 07 49 AM" src="https://user-images.githubusercontent.com/38114494/79590241-55be2680-809c-11ea-8299-d91e86b98865.png">

I've googled it and can't seem to find an error. I'm new to text analysis and topic modeling, and I can't tell if it's an issue in my code or an issue with software. Any help would be appreciated!

**Comment by amaiya** [comment]
A library used `bokeh` is used to generate the visualization, and the latest version released recently no longer supports `previewsave`.   I have just released a new version of ktrain (v0.14.1) that should work for you.  

Thanks for opening an issue and letting me know.

**Comment by samwalkow** [comment]
This worked! Thanks so much, and I'm happy I can help!

**Comment by amaiya** [comment]
Great!
