### ISSUE TITLE
Can't get 'bert' model to run

### ISSUE THREAD

**Issue by samlaws** [amaiya/ktrain#13]
[clean_sample (1).zip](https://github.com/amaiya/ktrain/files/3662412/clean_sample.1.zip)

Trying to use BERT in the ktrain.text.text_classifier results in the following error:

`ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[   0,    0,    0, ...,   73,   64, 5783],
       [   0,    0,    0, ...,   14,  183, 1045],
       [   0,    0,    0, ..., 1504,  196,  235],
       ...,
       [   0,    0,    0, ...,   12, ...`

My code works fine with both `fasttext` and `nbsvm`.

The last line results in the error, attached is the csv I am reading from

```DATA_PATH = '/content/clean_sample.csv'
NUM_WORDS = 50000
MAXLEN = 800
(x_train, y_train), (x_test, y_test), preproc = text.texts_from_csv(DATA_PATH,
                      'unfil', label_columns=list_,
                      val_filepath=None, # if None, 10% of data will be used for validation
                      max_features=NUM_WORDS, maxlen=MAXLEN,
                      ngram_range=1)`

model = text.text_classifier('bert', (np.array(x_train), np.array(y_train)), preproc=preproc)
learner = ktrain.get_learner(model, train_data=(x_train, y_train), val_data=(x_test, y_test))

learner.lr_find()

**Comment by amaiya** [comment]
BERT is a pretrained model and must be preprocessed in a specific way.  Add `preprocess_mode='bert'` to the `texts_from_csv` call:
```
(x_train, y_train), (x_test, y_test), preproc = text.texts_from_csv(DATA_PATH,
                      'unfil', label_columns=list_,
                      val_filepath=None, # if None, 10% of data will be used for validation
                      max_features=NUM_WORDS, maxlen=MAXLEN,
                      preprocess_mode='bert', #  NEEDED FOR BERT
                      ngram_range=1)
```

There is a note about this in the [text classification tutorial](https://github.com/amaiya/ktrain/blob/master/tutorial-04-text-classification.ipynb) that was recently added, and the next version of *ktrain* will perform an error check and inform the user if the data was not prepossessed appropriately.

**Comment by amaiya** [comment]
You might also want to lower your batch_size (by supplying `batch_size` argument to `get_learner`) and reduce `maxlen` value.  See [this blog post](https://towardsdatascience.com/bert-text-classification-in-3-lines-of-code-using-keras-264db7e7a358) for more information.

**Comment by samlaws** [comment]
Ok, thanks I've got it working with the `preprocess_mode` parameter. My mistake for not catching that in the documentation. I'll go ahead and close the issue.
