### ISSUE TITLE
Running GPU

### ISSUE THREAD

**Issue by am-h** [amaiya/ktrain#132]
How could I know that the model is using gpu? when I bert it is too slow, I used this to make sure that tensorflow is using gpu
# check your gpu is available:
# for tensorflow instance:
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))
But it seems that when I build the model using GPU or CPU it is same speed. 

Is there any other way to make sure of that?

**Comment by amaiya** [comment]
You can use [nvidia-smi](https://stackoverflow.com/questions/8223811/top-command-for-gpus-using-cuda) to examine GPU usage.
