### ISSUE TITLE
ktrain perdiction slow on AMD GPU

### ISSUE THREAD

**Issue by yashsinghal** [amaiya/ktrain#133]
The ktrain predictor works well on NVIDIA GPUs but really slows down on AMD ones. Is there a way to speed this up or could I shift it to keras. Even a temporary hack would work.

Thanks a lot

**Comment by amaiya** [comment]
Hello:  You'll need to provide more information.  What exactly is slow and for which model?

**Comment by yashsinghal** [comment]
I am trying to do NLP classification on a text using the AlBert model. I have already trained the model and saved its predictor using an Nvidia GPU. Now, I am trying to classify new text using my saved predictor on an AMD GPU. The prediction process is much slower on the AMD GPU than the Nvidia one. The GPUs are similar in performance.

**Comment by amaiya** [comment]
My guess is that it is not related specifically to the Predictor (or ktrain).  Have you verified  your TensorFlow installation for AMD is working correctly in general and correctly using GPU?  
I've never used an AMD GPU, but I recall  you need a [rocM-enabled TensorFlow](https://pypi.org/project/tensorflow-rocm/), I think.  When you install *ktrain*, though, it automatically installs [CUDA-enabled TensorFlow](https://pypi.org/project/tensorflow/). So, maybe try re-installing rocm TF?

**Comment by yashsinghal** [comment]
Thanks a lot. Will try that
