### ISSUE TITLE
Mobilenet bug

### ISSUE THREAD

**Issue by lambdaofgod** [amaiya/ktrain#135]
`model = vis.image_classifier('pretrained_mobilenet', train_data, val_data)
`

Throws

> NameError                                 Traceback (most recent call last)
> <ipython-input-11-3f0d478f6375> in <module>
> ----> 1 model = vis.image_classifier('pretrained_mobilenet', train_data, val_data)
>       2 learner = ktrain.get_learner(model=model, train_data=train_data, val_data=val_data, 
>       3                              workers=8, use_multiprocessing=True, batch_size=32)
> 
> /etc/conda/envs/ml/lib/python3.7/site-packages/ktrain/vision/models.py in image_classifier(name, train_data, val_data, freeze_layers, metric, optimizer_name, multilabel, multigpu_number, pt_fc, pt_ps, verbose)
>     193                                   activation=activation,
>     194                                   pt_fc = pt_fc,
> --> 195                                   pt_ps = pt_ps)
>     196         model.compile(optimizer=optimizer_name, loss=loss_func, metrics=[metric])
>     197         return model
> 
> /etc/conda/envs/ml/lib/python3.7/site-packages/ktrain/vision/models.py in build_visionmodel(name, num_classes, input_shape, freeze_layers, activation, pt_fc, pt_ps)
>     212                                   activation=activation,
>     213                                   pt_fc = pt_fc,
> --> 214                                   pt_ps = pt_ps)
>     215     elif name == CNN:
>     216         model = build_cnn(num_classes,
> 
> /etc/conda/envs/ml/lib/python3.7/site-packages/ktrain/vision/models.py in build_predefined(name, num_classes, input_shape, freeze_layers, activation, pt_fc, pt_ps)
>     301                            input_shape = input_shape)
>     302     elif name in [MOBILENET, PRETRAINED_MOBILENET]:
> --> 303         net = MobileNet(include_top=include_top, 
>     304                         weights=weights,
>     305                         input_tensor=input_tensor,
> 
> NameError: name 'MobileNet' is not defined

I'm using tensorflow-gpu==2.1.0 with ktrain==0.14.4

**Comment by amaiya** [comment]
Thanks for letting me know.  This is now fixed in v0.14.5.  Here is an [example notebook](https://github.com/amaiya/ktrain/blob/master/examples/vision/dogs_vs_cats-MobileNet.ipynb) that uses MobileNet.
