### ISSUE TITLE
How to train ktrain model in TPU?

### ISSUE THREAD

**Issue by aadityachapagain** [amaiya/ktrain#136]
How can i train ktrain models in TPU.

**Comment by amaiya** [comment]
In theory, you'd need to place whichever method you're using to create the classifier within the scope of `TPUStrategy` as described on the [TensorFlow page on TPUs](https://www.tensorflow.org/guide/tpu).  But, I haven't tried it. . See [this example](https://github.com/amaiya/ktrain/blob/master/examples/vision/mnist-tf_workflow.ipynb) for more information.
