### ISSUE TITLE
ktrain - latest release installation broken ?

### ISSUE THREAD

**Issue by GiavoDS** [amaiya/ktrain#138]
Hi all,

Today, I have updated ktrain with "pip install --upgrade ktrain" and ktrain broke comletely. 
Then I have completely uninstalled Anaconda and resintalled the latest version
-> created TensorFlow (2.1.0) environment as on TF website (all works perfectly) -> pip installed ktrain

when I import ktrain i get following results:

**>>> import ktrain
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\G\.conda\envs\tf_gpu_krain\lib\site-packages\ktrain\__init__.py", line 2, in <module>
    from .imports import *
  File "C:\Users\G\.conda\envs\tf_gpu_krain\lib\site-packages\ktrain\imports.py", line 210, in <module>
    import cchardet as chardet
  File "C:\Users\G\.conda\envs\tf_gpu_krain\lib\site-packages\cchardet\__init__.py", line 1, in <module>**

Is it possible that the latest release of ktrain broke and it doesn't work anymore?

Thank you !

**Comment by amaiya** [comment]
I tested on both on fresh Ubuntu and Google Colab and the latest version works fine.    What is the full error message and traceback?

**Comment by GiavoDS** [comment]
This is all I have: 

Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:22:21) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> import ktrain
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\G\.conda\envs\tf_gpu_krain\lib\site-packages\ktrain\__init__.py", line 2, in <module>
    from .imports import *
  File "C:\Users\G\.conda\envs\tf_gpu_krain\lib\site-packages\ktrain\imports.py", line 210, in <module>
    import cchardet as chardet
  File "C:\Users\G\.conda\envs\tf_gpu_krain\lib\site-packages\cchardet\__init__.py", line 1, in <module>
    from cchardet import _cchardet
ImportError: DLL load failed: The specified module could not be found.
>>>

**Comment by GiavoDS** [comment]
Maybe it is related to TF 2.1 installation, I have used this command:

conda create -n tf-gpu tensorflow-gpu
conda activate tf-gpu

I will retry installing and scpecify also cudatoolkit=10.0 lets see if it works

**Comment by GiavoDS** [comment]
I have created again a TF environment with: 

**conda create -n tf-gpu tensorflow-gpu cudatoolkit=10.1**

Then in tf-gpu env run pip install ktrain: 

**(tf-gpu_ktrain) C:\Users\g>pip install ktrain
Processing c:\users\g\appdata\local\pip\cache\wheels\d9\7d\5f\3195ee61bc44533e29658974b2b2d49f16d88137378f8b7a2c\ktrain-0.14.5-cp37-none-any.whl
Requirement already satisfied: tensorflow==2.1.0 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from ktrain) (2.1.0)
Processing c:\users\g\appdata\local\pip\cache\wheels\8d\b3\aa\6d99de9f3841d7d3d40a60ea06e6d669e8e5012e6c8b947a57\langdetect-1.0.8-cp37-none-any.whl
Collecting cchardet
  Using cached cchardet-2.1.6-cp37-cp37m-win_amd64.whl (115 kB)
Processing c:\users\g\appdata\local\pip\cache\wheels\a3\5e\7d\49405a043a4714a1b66bb7a16dfe16a1f0db9217baac7c4fe3\bokeh-2.0.2-cp37-none-any.whl
Processing c:\users\g\appdata\local\pip\cache\wheels\51\c6\a4\be1920586c49469846bcd2888200bdecfe109ec421dab9be2d\syntok-1.3.1-cp37-none-any.whl
Collecting joblib
  Using cached joblib-0.14.1-py2.py3-none-any.whl (294 kB)
Collecting packaging
  Using cached packaging-20.3-py2.py3-none-any.whl (37 kB)
Requirement already satisfied: requests in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from ktrain) (2.23.0)
Collecting scikit-learn>=0.21.3
  Using cached scikit_learn-0.22.2.post1-cp37-cp37m-win_amd64.whl (6.5 MB)
Collecting pandas>=1.0.1
  Using cached pandas-1.0.3-cp37-cp37m-win_amd64.whl (8.7 MB)
Processing c:\users\g\appdata\local\pip\cache\wheels\4f\32\0a\df3b340a82583566975377d65e724895b3fad101a3fb729f68\seqeval-0.0.12-cp37-none-any.whl
Collecting ipython
  Using cached ipython-7.14.0-py3-none-any.whl (782 kB)
Collecting fastprogress>=0.1.21
  Using cached fastprogress-0.2.3-py3-none-any.whl (12 kB)
Collecting transformers>=2.7.0
  Using cached transformers-2.8.0-py3-none-any.whl (563 kB)
Processing c:\users\g\appdata\local\pip\cache\wheels\af\e4\8e\5fdd61a6b45032936b8f9ae2044ab33e61577950ce8e0dec29\jieba-0.42.1-cp37-none-any.whl
Processing c:\users\g\appdata\local\pip\cache\wheels\bd\27\da\ffc2d573aa48b87440ec4f98bc7c992e3a2d899edb2d22ef9e\keras_bert-0.81.0-cp37-none-any.whl
Collecting tensorflow-datasets
  Using cached tensorflow_datasets-3.1.0-py3-none-any.whl (3.3 MB)
Collecting networkx>=2.3
  Using cached networkx-2.4-py3-none-any.whl (1.6 MB)
Collecting whoosh
  Using cached Whoosh-2.7.4-py2.py3-none-any.whl (468 kB)
Collecting matplotlib>=3.0.0
  Using cached matplotlib-3.2.1-cp37-cp37m-win_amd64.whl (9.2 MB)
Requirement already satisfied: astor>=0.6.0 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorflow==2.1.0->ktrain) (0.7.1)
Requirement already satisfied: keras-preprocessing>=1.1.0 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorflow==2.1.0->ktrain) (1.1.0)
Requirement already satisfied: numpy<2.0,>=1.16.0 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorflow==2.1.0->ktrain) (1.18.4)
Requirement already satisfied: google-pasta>=0.1.6 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorflow==2.1.0->ktrain) (0.2.0)
Requirement already satisfied: scipy==1.4.1; python_version >= "3" in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorflow==2.1.0->ktrain) (1.4.1)
Requirement already satisfied: grpcio>=1.8.6 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorflow==2.1.0->ktrain) (1.27.2)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorflow==2.1.0->ktrain) (1.1.0)
Requirement already satisfied: absl-py>=0.7.0 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorflow==2.1.0->ktrain) (0.9.0)
Requirement already satisfied: wrapt>=1.11.1 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorflow==2.1.0->ktrain) (1.12.1)
Requirement already satisfied: gast==0.2.2 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorflow==2.1.0->ktrain) (0.2.2)
Requirement already satisfied: protobuf>=3.8.0 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorflow==2.1.0->ktrain) (3.11.4)
Requirement already satisfied: six>=1.12.0 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorflow==2.1.0->ktrain) (1.14.0)
Collecting opt-einsum>=2.3.2
  Using cached opt_einsum-3.2.1-py3-none-any.whl (63 kB)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorflow==2.1.0->ktrain) (0.34.2)
Requirement already satisfied: tensorboard<2.2.0,>=2.1.0 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorflow==2.1.0->ktrain) (2.1.1)
Requirement already satisfied: tensorflow-estimator<2.2.0,>=2.1.0rc0 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorflow==2.1.0->ktrain) (2.1.0)
Requirement already satisfied: keras-applications>=1.0.8 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorflow==2.1.0->ktrain) (1.0.8)
Collecting Jinja2>=2.7
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting PyYAML>=3.10
  Using cached PyYAML-5.3.1-cp37-cp37m-win_amd64.whl (216 kB)
Collecting typing-extensions>=3.7.4
  Using cached typing_extensions-3.7.4.2-py3-none-any.whl (22 kB)
Collecting tornado>=5
  Using cached tornado-6.0.4-cp37-cp37m-win_amd64.whl (417 kB)
Collecting pillow>=4.0
  Using cached Pillow-7.1.2-cp37-cp37m-win_amd64.whl (2.0 MB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting regex
  Using cached regex-2020.4.4-cp37-cp37m-win_amd64.whl (271 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from requests->ktrain) (2020.4.5.1)
Requirement already satisfied: idna<3,>=2.5 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from requests->ktrain) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from requests->ktrain) (1.25.9)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from requests->ktrain) (3.0.4)
Collecting pytz>=2017.2
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting Keras>=2.2.4
  Using cached Keras-2.3.1-py2.py3-none-any.whl (377 kB)
Processing c:\users\g\appdata\local\pip\cache\wheels\98\b0\dd\29e28ff615af3dda4c67cab719dd51357597eabff926976b45\backcall-0.1.0-cp37-none-any.whl
Collecting colorama; sys_platform == "win32"
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting pygments
  Using cached Pygments-2.6.1-py3-none-any.whl (914 kB)
Collecting decorator
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting traitlets>=4.2
  Using cached traitlets-4.3.3-py2.py3-none-any.whl (75 kB)
Collecting jedi>=0.10
  Using cached jedi-0.17.0-py2.py3-none-any.whl (1.1 MB)
Requirement already satisfied: setuptools>=18.5 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from ipython->ktrain) (46.1.3.post20200325)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Using cached prompt_toolkit-3.0.5-py3-none-any.whl (351 kB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting tqdm>=4.27
  Using cached tqdm-4.46.0-py2.py3-none-any.whl (63 kB)
Collecting tokenizers==0.5.2
  Using cached tokenizers-0.5.2-cp37-cp37m-win_amd64.whl (1.0 MB)
Collecting filelock
  Using cached filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting boto3
  Downloading boto3-1.13.3-py2.py3-none-any.whl (128 kB)
     |████████████████████████████████| 128 kB 2.2 MB/s
Collecting sentencepiece
  Using cached sentencepiece-0.1.86-cp37-cp37m-win_amd64.whl (1.2 MB)
Processing c:\users\g\appdata\local\pip\cache\wheels\29\3c\fd\7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45\sacremoses-0.0.43-cp37-none-any.whl
Processing c:\users\g\appdata\local\pip\cache\wheels\26\98\13\a28402939e1d48edd8704e6b02f223795af4a706815f4bf6d8\keras_transformer-0.33.0-cp37-none-any.whl
Collecting tensorflow-metadata
  Using cached tensorflow_metadata-0.21.2-py2.py3-none-any.whl (31 kB)
Processing c:\users\g\appdata\local\pip\cache\wheels\19\49\34\c3c1e78bcb954c49e5ec0d31784fe63d14d427f316b12fbde9\promise-2.3-cp37-none-any.whl
Processing c:\users\g\appdata\local\pip\cache\wheels\59\b1\91\f02e76c732915c4015ab4010f3015469866c1eb9b14058d8e7\dill-0.3.1.1-cp37-none-any.whl
Processing c:\users\g\appdata\local\pip\cache\wheels\8b\99\a0\81daf51dcd359a9377b110a8a886b3895921802d2fc1b2397e\future-0.18.2-cp37-none-any.whl
Collecting attrs>=18.1.0
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.2.0-cp37-none-win_amd64.whl (57 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Requirement already satisfied: google-auth<2,>=1.6.3 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow==2.1.0->ktrain) (1.14.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow==2.1.0->ktrain) (0.4.1)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow==2.1.0->ktrain) (0.16.1)
Requirement already satisfied: markdown>=2.6.8 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow==2.1.0->ktrain) (3.2.1)
Requirement already satisfied: h5py in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from keras-applications>=1.0.8->tensorflow==2.1.0->ktrain) (2.10.0)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp37-cp37m-win_amd64.whl (16 kB)
Collecting ipython-genutils
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting parso>=0.7.0
  Using cached parso-0.7.0-py2.py3-none-any.whl (100 kB)
Collecting wcwidth
  Using cached wcwidth-0.1.9-py2.py3-none-any.whl (19 kB)
Collecting s3transfer<0.4.0,>=0.3.0
  Using cached s3transfer-0.3.3-py2.py3-none-any.whl (69 kB)
Collecting jmespath<1.0.0,>=0.7.1
  Using cached jmespath-0.9.5-py2.py3-none-any.whl (24 kB)
Collecting botocore<1.17.0,>=1.16.3
  Downloading botocore-1.16.3-py2.py3-none-any.whl (6.2 MB)
     |████████████████████████████████| 6.2 MB 1.7 MB/s
Requirement already satisfied: click in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from sacremoses->transformers>=2.7.0->ktrain) (7.1.2)
Processing c:\users\g\appdata\local\pip\cache\wheels\39\e2\e2\3514fef126a00574b13bc0b9e23891800158df3a3c19c96e3b\keras_position_wise_feed_forward-0.6.0-cp37-none-any.whl
Processing c:\users\g\appdata\local\pip\cache\wheels\5b\a1\a0\ce6b1d49ba1a9a76f592e70cf297b05c96bc9f418146761032\keras_pos_embd-0.11.0-cp37-none-any.whl
Processing c:\users\g\appdata\local\pip\cache\wheels\d1\bc\b1\b0c45cee4ca2e6c86586b0218ffafe7f0703c6d07fdf049866\keras_embed_sim-0.7.0-cp37-none-any.whl
Processing c:\users\g\appdata\local\pip\cache\wheels\54\80\22\a638a7d406fd155e507aa33d703e3fa2612b9eb7bb4f4fe667\keras_layer_normalization-0.14.0-cp37-none-any.whl
Processing c:\users\g\appdata\local\pip\cache\wheels\bb\df\3f\81b36f41b66e6a9cd69224c70a737de2bb6b2f7feb3272c25e\keras_multi_head-0.22.0-cp37-none-any.whl
Processing c:\users\g\appdata\local\pip\cache\wheels\2c\f9\7f\6eb87e636072bf467e25348bbeb96849333e6a080dca78f706\googleapis_common_protos-1.51.0-cp37-none-any.whl
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1.0->ktrain) (3.1.1)
Requirement already satisfied: rsa<4.1,>=3.1.4 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1.0->ktrain) (4.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1.0->ktrain) (0.2.7)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1.0->ktrain) (1.2.0)
Collecting docutils<0.16,>=0.10
  Using cached docutils-0.15.2-py3-none-any.whl (547 kB)
Processing c:\users\g\appdata\local\pip\cache\wheels\cc\dc\17\84258b27a04cd38ac91998abe148203720ca696186635db694\keras_self_attention-0.41.0-cp37-none-any.whl
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from rsa<4.1,>=3.1.4->google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1.0->ktrain) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow==2.1.0->ktrain) (3.0.1)
Installing collected packages: langdetect, cchardet, MarkupSafe, Jinja2, PyYAML, pyparsing, packaging, typing-extensions, tornado, pillow, python-dateutil, bokeh, regex, syntok, joblib, scikit-learn, pytz, pandas, Keras, seqeval, backcall, colorama, pygments, decorator, ipython-genutils, traitlets, parso, jedi, wcwidth, prompt-toolkit, pickleshare, ipython, fastprogress, tqdm, tokenizers, filelock, jmespath, docutils, botocore, s3transfer, boto3, sentencepiece, sacremoses, transformers, jieba, keras-position-wise-feed-forward, keras-pos-embd, keras-embed-sim, keras-layer-normalization, keras-self-attention, keras-multi-head, keras-transformer, keras-bert, googleapis-common-protos, tensorflow-metadata, promise, dill, future, attrs, tensorflow-datasets, networkx, whoosh, kiwisolver, cycler, matplotlib, ktrain, opt-einsum
  Attempting uninstall: opt-einsum
    Found existing installation: opt-einsum 0+untagged.56.g2664021.dirty
    Uninstalling opt-einsum-0+untagged.56.g2664021.dirty:
      Successfully uninstalled opt-einsum-0+untagged.56.g2664021.dirty
Successfully installed Jinja2-2.11.2 Keras-2.3.1 MarkupSafe-1.1.1 PyYAML-5.3.1 attrs-19.3.0 backcall-0.1.0 bokeh-2.0.2 boto3-1.13.3 botocore-1.16.3 cchardet-2.1.6 colorama-0.4.3 cycler-0.10.0 decorator-4.4.2 dill-0.3.1.1 docutils-0.15.2 fastprogress-0.2.3 filelock-3.0.12 future-0.18.2 googleapis-common-protos-1.51.0 ipython-7.14.0 ipython-genutils-0.2.0 jedi-0.17.0 jieba-0.42.1 jmespath-0.9.5 joblib-0.14.1 keras-bert-0.81.0 keras-embed-sim-0.7.0 keras-layer-normalization-0.14.0 keras-multi-head-0.22.0 keras-pos-embd-0.11.0 keras-position-wise-feed-forward-0.6.0 keras-self-attention-0.41.0 keras-transformer-0.33.0 kiwisolver-1.2.0 ktrain-0.14.5 langdetect-1.0.8 matplotlib-3.2.1 networkx-2.4 opt-einsum-3.2.1 packaging-20.3 pandas-1.0.3 parso-0.7.0 pickleshare-0.7.5 pillow-7.1.2 promise-2.3 prompt-toolkit-3.0.5 pygments-2.6.1 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2020.1 regex-2020.4.4 s3transfer-0.3.3 sacremoses-0.0.43 scikit-learn-0.22.2.post1 sentencepiece-0.1.86 seqeval-0.0.12 syntok-1.3.1 tensorflow-datasets-3.1.0 tensorflow-metadata-0.21.2 tokenizers-0.5.2 tornado-6.0.4 tqdm-4.46.0 traitlets-4.3.3 transformers-2.8.0 typing-extensions-3.7.4.2 wcwidth-0.1.9 whoosh-2.7.4

(tf-gpu_ktrain) C:\Users\g>python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:22:21) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ktrain
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages\ktrain\__init__.py", line 2, in <module>
    from .imports import *
  File "C:\Users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages\ktrain\imports.py", line 210, in <module>
    import cchardet as chardet
  File "C:\Users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages\cchardet\__init__.py", line 1, in <module>
    from cchardet import _cchardet
ImportError: DLL load failed: The specified module could not be found.
>>>**

**Comment by amaiya** [comment]
This appears to be some sort of Windows conda-related issue.   [This stackoverflow post](https://stackoverflow.com/questions/60784527/ktrain-importerror-dll-load-failed-the-specified-module-could-not-be-found) seems to have a solution to the problem, though.

The solution includes TF 2.0, but you can probably replace that with TF 2.1.

**Comment by GiavoDS** [comment]
Thanks a lot! The following command solved my issues:

conda install -c conda-forge cchardet

**Comment by amaiya** [comment]
Great.  This appears to be a bug in the latest release of `cchardet`: see [here](https://github.com/PyYoshi/cChardet/issues/61).   While `conda install -c conda-forge cchardet` is a solution, I have downgraded `cchardet` to v2.1.5 in v0.14.6 of *ktrain* in hopes that this will also address this issue.  Thanks for posting issue.

**Comment by Dipeshpal** [comment]
```
pip install cchardet==1.1.1
pip install ktrain===0.38.0

```
This fixed my issue.

Issues-
```
pip3 install -q ktrain
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\cchardet
      copying src\cchardet\version.py -> build\lib.win-amd64-cpython-311\cchardet
      copying src\cchardet\__init__.py -> build\lib.win-amd64-cpython-311\cchardet
      running build_ext
      building 'cchardet._cchardet' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cchardet
ERROR: Could not build wheels for cchardet, which is required to install pyproject.toml-based projects


```
