### ISSUE TITLE
How to add more layers after BERT for fine tune?

### ISSUE THREAD

**Issue by sunwei317** [amaiya/ktrain#14]
Thanks!

**Comment by amaiya** [comment]
The BERT model is just another Keras model, so you can remove last layer and add additional layers, just as you normally would do in Keras (e.g., as you would do for pretrained ImageNet models).  Maybe something like this (not tested - just provided to give you idea):

```
inputs = model.inputs[:2]
dense = model.get_layer('NSP-Dense').output
# add additional layers here
outputs = Dense(units=num_classes, activation='softmax')(dense)
model = Model(inputs, outputs)
model.compile(loss='categorical_crossentropy',
                       optimizer='adam',
                       metrics=['accuracy'])
```

**Comment by Moshiur-Rahman-Faisal** [comment]
Can you provide an example for the above question?

**Comment by amaiya** [comment]
For HF transformers only:

https://stackoverflow.com/questions/63201036/add-additional-layers-to-the-huggingface-transformers
[https://stackoverflow.com/](https://stackoverflow.com/questions/64156202/add-dense-layer-on-top-of-huggingface-bert-model)[questions/64156202/add-dense-layer-on-top-of-huggingface-bert-model](https://stackoverflow.com/questions/64156202/add-dense-layer-on-top-of-huggingface-bert-model)
https://stackoverflow.com/questions/65285054/how-to-add-a-multiclass-multilabel-layer-on-top-of-pretrained-bert-model
