### ISSUE TITLE
SOLVED: distributed_function - InternalError:  Blas GEMM launch failed

### ISSUE THREAD

**Issue by GiavoDS** [amaiya/ktrain#141]
TF: 2.1
Ktrain: latest (installed yeterday)
Loaded data with params:
(x_train, y_train), (x_test, y_test), preproc=text.texts_from_folder('path', 
                                                                    maxlen =120,
                                                                    preprocess_mode='bert',
                                                                    classes=['Positive', 'Negative'])

Hi,

I have trained a Classification model and saved it with command:

**predictor.save('path')**

Then I load the model again with:

**reloaded_predictor = ktrain.load_predictor('path')** 

Which gets reloaded, no I try the prediction on a sample sentence with this command:

**reloaded_predictor.predict('I love football')**

and get the following error:

---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<ipython-input-4-8039880ede0d> in <module>
----> 1 reloaded_predictor.predict('I love football')

~\.conda\envs\tf-gpu_ktrain\lib\site-packages\ktrain\text\predictor.py in predict(self, texts, return_proba)
     49         else:
     50             texts = self.preproc.preprocess(texts)
---> 51             preds = self.model.predict(texts, batch_size=self.batch_size)
     52 
     53         # process predictions

~\.conda\envs\tf-gpu_ktrain\lib\site-packages\tensorflow_core\python\keras\engine\training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1011         max_queue_size=max_queue_size,
   1012         workers=workers,
-> 1013         use_multiprocessing=use_multiprocessing)
   1014 
   1015   def reset_metrics(self):

~\.conda\envs\tf-gpu_ktrain\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in predict(self, model, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing, **kwargs)
    496         model, ModeKeys.PREDICT, x=x, batch_size=batch_size, verbose=verbose,
    497         steps=steps, callbacks=callbacks, max_queue_size=max_queue_size,
--> 498         workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
    499 
    500 

~\.conda\envs\tf-gpu_ktrain\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in _model_iteration(self, model, mode, x, y, batch_size, verbose, sample_weight, steps, callbacks, max_queue_size, workers, use_multiprocessing, **kwargs)
    473               mode=mode,
    474               training_context=training_context,
--> 475               total_epochs=1)
    476           cbks.make_logs(model, epoch_logs, result, mode)
    477 

~\.conda\envs\tf-gpu_ktrain\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    126         step=step, mode=mode, size=current_batch_size) as batch_logs:
    127       try:
--> 128         batch_outs = execution_function(iterator)
    129       except (StopIteration, errors.OutOfRangeError):
    130         # TODO(kaftan): File bug about tf function and errors.OutOfRangeError?

~\.conda\envs\tf-gpu_ktrain\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py in execution_function(input_fn)
     96     # `numpy` translates Tensors to values in Eager mode.
     97     return nest.map_structure(_non_none_constant_value,
---> 98                               distributed_function(input_fn))
     99 
    100   return execution_function

~\.conda\envs\tf-gpu_ktrain\lib\site-packages\tensorflow_core\python\eager\def_function.py in __call__(self, *args, **kwds)
    566         xla_context.Exit()
    567     else:
--> 568       result = self._call(*args, **kwds)
    569 
    570     if tracing_count == self._get_tracing_count():

~\.conda\envs\tf-gpu_ktrain\lib\site-packages\tensorflow_core\python\eager\def_function.py in _call(self, *args, **kwds)
    636               *args, **kwds)
    637       # If we did not create any variables the trace we have is good enough.
--> 638       return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
    639 
    640     def fn_with_cond(*inner_args, **inner_kwds):

~\.conda\envs\tf-gpu_ktrain\lib\site-packages\tensorflow_core\python\eager\function.py in _filtered_call(self, args, kwargs)
   1609          if isinstance(t, (ops.Tensor,
   1610                            resource_variable_ops.BaseResourceVariable))),
-> 1611         self.captured_inputs)
   1612 
   1613   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

~\.conda\envs\tf-gpu_ktrain\lib\site-packages\tensorflow_core\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1690       # No tape is watching; skip to running the function.
   1691       return self._build_call_outputs(self._inference_function.call(
-> 1692           ctx, args, cancellation_manager=cancellation_manager))
   1693     forward_backward = self._select_forward_and_backward_functions(
   1694         args,

~\.conda\envs\tf-gpu_ktrain\lib\site-packages\tensorflow_core\python\eager\function.py in call(self, ctx, args, cancellation_manager)
    543               inputs=args,
    544               attrs=("executor_type", executor_type, "config_proto", config),
--> 545               ctx=ctx)
    546         else:
    547           outputs = execute.execute_with_cancellation(

~\.conda\envs\tf-gpu_ktrain\lib\site-packages\tensorflow_core\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     65     else:
     66       message = e.message
---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
     68   except TypeError as e:
     69     keras_symbolic_tensors = [

~\.conda\envs\tf-gpu_ktrain\lib\site-packages\six.py in raise_from(value, from_value)

InternalError:  Blas GEMM launch failed : a.shape=(120, 768), b.shape=(768, 768), m=120, n=768, k=768
	 [[node model_1/Encoder-1-MultiHeadSelfAttention/MatMul (defined at C:\Users\g\.conda\envs\tf-gpu_ktrain\lib\site-packages\keras_multi_head\multi_head_attention.py:185) ]] [Op:__inference_distributed_function_40705]

Function call stack:
distributed_function

Any idea of how to fix this issue?
Note: this used to work in yesterday but doesn't work anymore without me touching it

**Comment by GiavoDS** [comment]
I have restarted my laptop and it worked again :)

**Comment by amaiya** [comment]
Great - you probably ran out of GPU memory from a previous Jupyter session.  Usually restarting Jupyter and runtime is sufficient.
