### ISSUE TITLE
Is there a support for roberta models for text classification?

### ISSUE THREAD

**Issue by KrishnaPriyaIITR** [amaiya/ktrain#143]

**Comment by amaiya** [comment]
Yes, if you use the `Transformer` API in *ktrain*:  see [this blog post](https://towardsdatascience.com/text-classification-with-hugging-face-transformers-in-tensorflow-2-without-tears-ee50e4f3e7ed) and [this tutorial](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A3-hugging_face_transformers.ipynb).  Another *ktrain* user just recently applied Roberta to a biomedial NLP problem.
