### ISSUE TITLE
Support for scoring NER against test set

### ISSUE THREAD

**Issue by NicoleJaneway** [amaiya/ktrain#145]
Does ktrain offer support for scoring NER against a test set?  I have reserved data in the conll2003 format, and I'd like to evaluate how well a predictor does on this dataset.  Something like spaCy's scorer (https://spacy.io/api/scorer)?  Thanks!

**Comment by amaiya** [comment]
Hi @NicoleJaneway:    The `preproc.preprocess_test` method can be used to preprocess the reserved data into an `NERSequence`object, which can then be passed to `learner.validate`.  Alternatively, you can also always just use `predictor.predict` to generate predictions on raw sentences from the reserved data and compute the metrics on `predicted` vs. `actual` directly/manually.
