### ISSUE TITLE
Support for RoBErta

### ISSUE THREAD

**Issue by msamwelmollel** [amaiya/ktrain#146]
First, I want to thank you for the wonderful work that you have done. My question is when we should expect to use Ktrain for Roberta pretrain, or Ktrain will not support this model at all?

**Comment by amaiya** [comment]
Thank you.

Roberta is already supported right now.  You can use most any [pretrained model](https://huggingface.co/transformers/pretrained_models.html) or [community-uploaded model](https://huggingface.co/models) with the `Transformer` API in *ktrain*:

```python
# load text data
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
from sklearn.datasets import fetch_20newsgroups
train_b = fetch_20newsgroups(subset='train', categories=categories, shuffle=True)
test_b = fetch_20newsgroups(subset='test',categories=categories, shuffle=False)
(x_train, y_train) = (train_b.data, train_b.target)
(x_test, y_test) = (test_b.data, test_b.target)

# build, train, and validate model (Transformer is wrapper around transformers library)
import ktrain
from ktrain import text
MODEL_NAME = 'roberta-base'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
learner.fit_onecycle(5e-5, 1)
```

Please see the tutorial notebooks and blog posts on the README page for more information.

**Comment by msamwelmollel** [comment]
Dear Amaiya

Thank you very much I appreciate your assistance.

Regards
