### ISSUE TITLE
Can ktrain be used for sentence pair classification task ?

### ISSUE THREAD

**Issue by vishalmodagekar** [amaiya/ktrain#149]
How can we use ktrain for sentence classification task using bert models ? 
For example, classify whether the given pair of sentence are similar.
sentence 1 : He said the food service pie business doesn 't fit the company 's long-term growth strategy .    
sentence 2 : The food service pie business does not fit our long-term growth strategy .
label : 1 (similar)

**Comment by amaiya** [comment]
Yes, sentence pair classification is supported.  Please see [this example notebook on paraphrase detection](https://github.com/amaiya/ktrain/blob/master/examples/text/MRPC-BERT.ipynb).  Note that you'll need to install `ktrain >= 0.15.1` for it to work.
