### ISSUE TITLE
How to handle imbalanced training set?

### ISSUE THREAD

**Issue by sunwei317** [amaiya/ktrain#15]
In Keras, there is a function class_weight.compute_class_weight. Is there a similar arg to autofit or other fit methods?

**Comment by amaiya** [comment]
*ktrain* is not currently passing `class_weight` parameter to `fit` and `fit_generator`, but it probably should.  This issue is marked as enhancement.

**Comment by amaiya** [comment]
In v0.4.2, you can pass `class_weight` parameter to all fit methods in *ktrain*.  You can use sklearn's `compute_class_weight`.

**Comment by sunwei317** [comment]
Thank you!
