### ISSUE TITLE
Processing Time Explainable AI in ktrain 

### ISSUE THREAD

**Issue by fabianoswald** [amaiya/ktrain#150]
Hi there, 

i am facing extremely long processing times when running the explain method `predictor.explain(doc)` (ca. 50sec on google colab and +5 minutes on local cpu's).

Can anyone provide an 'explanation' for this or even provide me with some advice to reduce processing time?

Thanks a lot!

**Comment by amaiya** [comment]
As of v0.15.2 of ktrain, the `TextPredictor.explain` method has an `n_samples` argument, which governs the number of samples that are generated and trained on to produce the explanation.  It used to be set to 5000.  I have lowered the default value to 2500.  If it is still too slow, you can manually lower it further to 500 or 1000:   `predictor.explain(text_data, n_samples=500)`.

**Comment by amaiya** [comment]
At `n_samples=500` on Google Colab, results are returned by `TextPredictor.explain` in roughly 5 seconds (versus 50 seconds at `n_samples=5000`.   Although, in theory, higher sample sizes produce better results, I didn't notice a drastic difference in my tests.
