### ISSUE TITLE
[Question] How to access preproc object?

### ISSUE THREAD

**Issue by NicoleJaneway** [amaiya/ktrain#152]
When using the interface

`t = text.Transformer(MODEL_NAME, maxlen=500, class_names=ft_cols)
trn = t.preprocess_train(train[TEXT_COL].values, y=train[ft_cols].values)
val = t.preprocess_test(val[TEXT_COL].values, y=val[ft_cols].values)`

how do I access the `preproc` object?  I need to use `preproc` in order to create a predictor.

**Comment by amaiya** [comment]
The `Transformer` object (i.e., `t` in your example) is a `Preprocessor` instance itself.  So, as shown in the [tutorial](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A3-hugging_face_transformers.ipynb), the `Predictor` instance is created as follows:

```python
predictor = ktrain.get_predictor(learner.model, t)
```
