### ISSUE TITLE
Parallelizing text pre-processing

### ISSUE THREAD

**Issue by ndolev** [amaiya/ktrain#153]
Hi, 

I am able to parallelize the pre-processing using Dask which gives a very significant speedup.

```{Python}
import dask
def preproc(x, labels = labels):
    MODEL_NAME = 'distilbert-base-uncased'
    t = text.Transformer(MODEL_NAME, maxlen=80, class_names = labels, multilabel=True)
    res = t.preprocess_train(x['text_a'].values.tolist(),x['label'].values.tolist(), verbose=0)
    return(res)

results = []
partitions = train.to_delayed()
for part in partitions:
    results.append(dask.delayed(preproc)(part))

results = client.compute(results)

trn = results[0].result()
x = [r.result().x for r in results]
y = [r.result().y for r in results]
numlabels = np.max([yy.shape[1] for yy in y])
y = [np.pad(yy,[0,numlabels - yy.shape[1]], 'constant', constant_values = 0) for yy in y]
trn.x  = np.concatenate(x, axis = 0)
trn.y  = np.concatenate(y, axis = 0)

```
One question and one comment. 

_Comment_:
Each partition produces a progress bar which slows the whole thing down (is it possible to add a flag for disabling that?). 
_Question_:
Do you see any issues with concatenating results computed in parallel like this?

**Comment by amaiya** [comment]
That's great.  Yes, it's possible to add a flag to disable the progress bar.  However, it may also make sense to add a flag to parallelize preprocessing within *ktrain* itself.  I don't think there is any issue with concatenating, but it would good for me to verify this using an example.  Do you have a self-contained example that can be used to test? Perhaps, you can modify this example below to demonstrate the speedup you're seeing:

```python
# load text data
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
from sklearn.datasets import fetch_20newsgroups
train_b = fetch_20newsgroups(subset='train', categories=categories, shuffle=True)
test_b = fetch_20newsgroups(subset='test',categories=categories, shuffle=True)
(x_train, y_train) = (train_b.data, train_b.target)
(x_test, y_test) = (test_b.data, test_b.target)

# preprocess training
import ktrain
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names)
trn = t.preprocess_train(x_train, y_train)
```

**Comment by ndolev** [comment]
Hi,

With pleasure. There are a couple caveats, with multilabel, I realize that the solution above requires a change:
```{Python}
def preproc(x, keyphrases = keyphrases):
    MODEL_NAME = 'distilbert-base-uncased'
    t = text.Transformer(MODEL_NAME, maxlen=80, class_names = keyphrases, multilabel=True)
    res = t.preprocess_train(x['text_a'].values.tolist(),x['label'].values.tolist(), verbose=0)
    return(res)

results = []
partitions = train.to_delayed()
for part in partitions:
    results.append(dask.delayed(preproc)(part))

results = client.compute(results)

trn = results[0].result()
x = [r.result().x for r in results]
y = [r.result().y for r in results]
numlabels = np.max([yy.shape[1] for yy in y])
y = [np.pad(yy,[0,numlabels - yy.shape[1]], 'constant', constant_values = 0) for yy in y]
trn.x  = np.concatenate(x, axis = 0)
trn.y  = np.concatenate(y, axis = 0)
```
So that the y's have the same shape. 

Also, there seems to be a problem downstream. If I setup the learner with my trn/val produced in the above way:

```{Python}
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=10, eval_batch_size=10,use_multiprocessing=True, multigpu=True)
tbCallBack = keras.callbacks.TensorBoard(log_dir='/home/ubuntu/tensorboard', histogram_freq=0, write_graph=True, write_images=True, update_freq = 1000)
```

And then run the training:

```{Python}
learner.autofit(lr = 2e-5, epochs = None, early_stopping = 3, reduce_on_plateau = 2, reduce_factor=3, checkpoint_folder= '/home/ubuntu/checkpoints/', callbacks=[tbCallBack], verbose = 1)
```

The training never seems to begin. Do you have any ideas by chance?

**Comment by amaiya** [comment]
OK - thanks.  The `learner.load_model` and `learner.save_model`  methods can be used to save and reload a model.  And, in your case, since you're using a `transformer` model, this is just a wrapper to `save_pretrained` and `from_pretrained`, which save and load the weights.  

Also, right now, the dataset is converted on-the-fly to a tf.data.Dataset right before training.  This was done to provide more flexibility and typically doesn't cause problems or take very long.  Out of curiosity, how many training examples are you using? Transfer learning with `transformers` typically doesn't need many training examples to perform well.

If you're able to send a self-contained example that I can use to test (e.g., using 20 newsgroups dataset),, I'm happy to test it and look into parallelizing  the preprocessing within *ktrain* and any other issues you're experiencing.

**Comment by amaiya** [comment]
> Still, the training takes a very long time to begin with the large set. Is there a way to load weights from a previously saved checkpoint and continue training?

[This FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-resume-training-from-a-saved-checkpoint) has been added to answer this question. Thanks.
