### ISSUE TITLE
save behaviour

### ISSUE THREAD

**Issue by Guillermogsjc** [amaiya/ktrain#155]
Hi,

when saving a model, it would be a nice to have feature that everything is stored inside the path indicated.

Right now `.preproc` file is being stored outside from the stablished path.

Regards.

**Comment by amaiya** [comment]
@Guillermogsjc   In v0.15.3 of *ktrain*, for all models including `Transformer` models, the supplied `fpath` argument to `predictor.save`  is now used to create a folder where both the model and the `.preproc` is saved.  However, the `load*` functions like `ktrain.load_predictor` will still attempt to load models and `.preproc` objects the old way if the new way fails (so, things should be backwards compatible with models/predictors saved using an older version of *ktrain*).  The `learner.save_model` and `learner.load_model` methods were also changed accordingly.  Thanks.
