### ISSUE TITLE
preproc file with distilbert

### ISSUE THREAD

**Issue by sathish331977** [amaiya/ktrain#156]
While i was able to train using distilbert (using tutorial-A3-hugging_face_transformers.ipynb)  , the predictor.save call produced a folder with the model and a json file. While loading the model for inference it looks for .preproc file and get an exception missing .preproc file. Please let me know if i am missing something.

**Comment by amaiya** [comment]
The latest release of *ktrain* (v0.15.3) saves the `.preproc` file within the specified folder (instead of of one level above the model folder) producing a folder that looks like this:
```python
predictor.save(('/tmp/my_predictor`)
!ls /tmp/my_predictor
# output of ls
# config.json  tf_model.h5  tf_model.preproc
p = ktrain.load_predictor('/tmp/my_predictor`)
p.predict('computer monitor is blurry')
# output
# comp.graphics
```
For `transformer` models, there is also a `config.json` file saved in the specified folder. This should not be a breaking change,  If loading the `.preproc` file from the new location fails, *ktrain* will attempt to load the model and `.preproc` file from the old location (if things were saved using an older version of *ktrain*).

I just tested the above on Google Colab and everything worked as expected.

Please tell me with the exact code/steps you're using to produce the error.

**Comment by sathish331977** [comment]
Thank you , first i noticed is i am on older version, will update to new version and try it out
Below is the code( main parts of code used for training) 
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID";
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1";
import tensorflow as tf
import ktrain
from ktrain import text

train_d,test_d = get_train_test() # custom method to get data in required format
(x_train,y_train) = (train_d.get('data'),train_d.get('target'))
(x_test, y_test) = (test_d.get('data'), test_d.get('target'))

mirrored_strategy = tf.distribute.MirroredStrategy()
BATCH_SIZE = 12 * 2
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=512, class_names=['skip', 'noskip'])
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
with mirrored_strategy.scope():
    model = t.get_classifier()

learner = ktrain.get_learner(model, train_data=trn, batch_size=BATCH_SIZE)
learner.val_data=val
history = learner.autofit(1e-5, checkpoint_folder='../models/checkpoints/')
learner.save_model('../model7/m7_v1_05242020')
learner.load_model('../model7/m7_v1_05242020', preproc=t)
learner.validate(val_data=val, class_names=['skip', 'noskip'])

**Comment by sathish331977** [comment]
after completion of training i dont see a .preproc written, i see a h5 and a json file created.
i think i should be using predictor save not learner save.

**Comment by amaiya** [comment]
Yes, `learner.save_model` only saves the model and is typically used in interactive training.  

The `predictor.save` method saves both the model and the `preproc` object which is used to preprocess the input prior to feeding it to model to generate predictions.  Thus, `ktrain.load_predictor` will throw an error if it can't find the `.preproc` file.

Please use `predictor.save` to save the predictor (i.e., both the model and `Preprocessor` instance). Thanks.

**Comment by sathish331977** [comment]
thank you
