### ISSUE TITLE
How to save SimpleQA trained model?

### ISSUE THREAD

**Issue by DunnCreativeSS** [amaiya/ktrain#157]
Hi,

I've tried the provided sample for SimpleQA. In my output, it gave me:

<IPython.core.display.HTML object>                                     

which I assume is the:

#qa.display_answers(answers[:5])

if I re-run the sample code, it complains there's already a directory where it tries to create index (good). If I leave out everything and rerun:

qa = text.SimpleQA(INDEXDIR)

it starts training again,.. another three hours :(

This is my code now so I should get some output:

`# load 20newsgroups datset into an array
#from sklearn.datasets import fetch_20newsgroups
#remove = ('headers', 'footers', 'quotes')
#newsgroups_train = fetch_20newsgroups(subset='train', remove=remove)
#newsgroups_test = fetch_20newsgroups(subset='test', remove=remove)
#docs = newsgroups_train.data +  newsgroups_test.data

import ktrain
from ktrain import text

INDEXDIR = '/tmp/qa'

#text.SimpleQA.initialize_index(INDEXDIR)
#text.SimpleQA.index_from_folder('./Philosophy', INDEXDIR)

qa = text.SimpleQA(INDEXDIR)

answers = qa.ask('Why are we here?')
top_answer = answers[0]['answer']
print(top_answer)
top_answer = answers[1]['answer']
print(top_answer)
top_answer = answers[2]['answer']
print(top_answer)
top_answer = answers[3]['answer']
print(top_answer)
top_answer = answers[4]['answer']
print(top_answer)

#qa.display_answers(answers[:5])`

How to I reload my already trained model?

**Comment by amaiya** [comment]
The only state that needs to be persisted/saved is the search index.  So, what you need is already saved within the `INDEXDIR` in the code example you provided.  To reload,  you just need to re-instantiate the `SimpleQA` instance (which does **not** re-index anything):
```python
qa = text.SimpleQA(INDEXDIR)
```

If deploying to a different machine, you just need to copy the `INDEXDIR` folder to the deployment environment (and make sure *ktrain* is installed on the machine).

Running `qa = text.SimpleQA(INDEXDIR)` does not reindex (or retrain) anything. All it does is open a previously-created search index.

Please see this [Google Colab notebook](https://colab.research.google.com/drive/1tcsEQ7igx7lw_R0Pfpmsg9Wf3DEXyOvk) for a working example.  You'll see that calling `text.SimpleQA(INDEXDIR)` doesn't take too long.  It is the `index_from_folder` that actually indexes documents and may take a while. 

Also, the `display_answers` method will only work in Jupyter notebooks and Google Colab.

If `qa = text.SimpleQA(INDEXDIR)` is taking too long for you, then there might be some other problem.   Are you sure it is `SimpleQA(INDEXDIR)` that is taking 3 hours after you've already created the index and indexed documents?

**Comment by DunnCreativeSS** [comment]
I've been trying to set up my own REST interface on Flask for it.

I noted when I did qa = text.SimpleQA(INDEXDIR), nothing seemed to happen.

If I add 

answers = qa.ask('question') 

and

top_answer = answers[0]['answer']

it's now retraining again (I assume, it says Epoch 1/1 and it wants to take 7 hours).

this is after I already ran index_from_folder, which isn't in this code.

Am I missing a step?

Thank you for your very quick reply!

**Comment by DunnCreativeSS** [comment]
The first time I ran it with creating the index and indexing, I left it running while I was asleep and it popped out the html answer that would have worked on colab or jupyter.

**Comment by DunnCreativeSS** [comment]
Contents of index dir right now:

![image](https://user-images.githubusercontent.com/22843601/83568816-fefc9700-a4f9-11ea-9069-4ed7ffa2df72.png)

Seems to have finished updating a/o yesterday

**Comment by DunnCreativeSS** [comment]
Ah, it appears my dataset is much larger. Asking qs has a lot more work to do.

**Comment by amaiya** [comment]
The progress bar you're seeing when `ask` is invoked is simply the progress of trying to find the answer (e.g., parsing through paragraphs of the documents and running inferences).  It should not take 3 hours, though, as illustrated in the example notebook.  Are you sure you're using a GPU?  What are the specs of the system you're using in terms of CPU cores and memory?   The QA system uses BERT (large), which is a larger model with 340M parameters.

**Comment by DunnCreativeSS** [comment]
It's on a GCP instance with 14gb vgpu and many many gb of ram, 12 vcpu cores.

The data I trained it on was 17mb of philosophy texts

**Comment by DunnCreativeSS** [comment]
By the way if I make an ad-supported interface for SimpleQA what sort of attribution to original dev should I have?

**Comment by DunnCreativeSS** [comment]
Should I have my own text datasets to train, is there a model to follow to streamline the process? I just dumped a bunch of .txts into a directory and hoped for the best

**Comment by DunnCreativeSS** [comment]
![image](https://user-images.githubusercontent.com/22843601/83571805-da56ee00-a4fe-11ea-8a05-4bfb44f5bfc6.png)

And should the GPU footprint be larger?

**Comment by amaiya** [comment]
To answer your questions:
- Yes, you can just dump the `.txt` files into a directory.  
- Making an ad-supported interface using *ktrain* is fine. Attribution can be provided by mentioning *ktrain* (e.g., "powered by *ktrain*") and linking to this GitHub repository.

I just tested a larger dataset of 50K `.txt` files totaling 203MB and running `ask` was quite fast using a TITAN V GPU.  Do you have a smaller number of very large `.txt` files with lots of paragraphs?  If so, this may be part of the slowdown, as an inference must be run on each paragraph in the document returned by the keyword search.  The solution to this is to simply break up documents in to smaller pieces, which can also be done using *ktrain* if you go that route. So, if you have a small number of really large books, you can break them out into paragraphs and possibly have them in a folder structure like this that can, then, be indexed for the QA system:
```
book01/
      paragraph01.txt
      paragraph02.txt
      paragraph03.txt
      ...
book02/
      paragraph01.txt
      paragraph02.txt
      paragraph03.txt
...
```

**Comment by DunnCreativeSS** [comment]
Good stuff! How can I use ktrain to break up the files into this type of folder structure?

For context, I took famous dialogues from philosophers like Plato, Socrates and a bunch of 'newer' philosophers.

There are 13 files, totalling 17.9 MB. Most of these are the result of pdftotext conversion.

**Comment by DunnCreativeSS** [comment]
![image](https://user-images.githubusercontent.com/22843601/83576719-bc8e8680-a508-11ea-8a76-a56626bbe1c6.png)

woot

**Comment by amaiya** [comment]
Great and interesting application.  You can also use this:
```python
ktrain.text.textutils.paragraph_tokenize(document, join_sentences=True)
```
To create folder structure, you can just use `os.path.dirname` and `os.makedirs`.

**Comment by DunnCreativeSS** [comment]
I fed an AI context from banned books, from serial killers to Noam Chomsky to the occult and strange to some fairly complex manifestos.

Note - it's a question answering bot, not a chatbot. It has no context from your previous questions, and it's simply answering whatever new question it's given. It has no sense of 'self' and doesn't get questions like 'Have you read Brave New World?' (which also isn't a banned book, mind you).

Have a try: http://jare.cloud/banned-books-bot/

watch the questions and answers live: https://youtu.be/sEWGbw7dJGs

**Comment by DunnCreativeSS** [comment]
![image](https://user-images.githubusercontent.com/22843601/83587404-60862b00-a525-11ea-92fb-e78aa7991ea9.png)

**Comment by DunnCreativeSS** [comment]
you've enabled me reproducable scalable clickbait. Thank you.

**Comment by DunnCreativeSS** [comment]
![image](https://user-images.githubusercontent.com/22843601/83587453-83b0da80-a525-11ea-8d62-b32c5a8fe483.png)

**Comment by amaiya** [comment]
Really cool - thanks for sharing.  Btw, in the latest version of *ktrain*, some additional optional arguments have been added to `index_from_folder` and `index_from_list` that can be used to help speedup indexing if necessary (e.g., `procs=4, multisegment=True`).
