### ISSUE TITLE
Is 'xlm-roberta-base' not yet supported in Ktrain?

### ISSUE THREAD

**Issue by msamwelmollel** [amaiya/ktrain#158]
Dear Amaya

I am trying to use pre-trained model '**xlm-roberta-base**', but I keep on receiving the message that says 'TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType'. I don't know how to interpret this message. Is this because the model is not yet supported by ktrain library?

Thank you, and I hope to hear from you soon.

**Comment by amaiya** [comment]
Yes, it is supported.  

But, for reasons I don't know, the TensorFlow version of the model in the `transformers` library must be loaded like a community-uploaded model with the name `jplu/tf-xlm-roberta-base`.  

Here is a working example:

```python
# load text data
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
from sklearn.datasets import fetch_20newsgroups
train_b = fetch_20newsgroups(subset='train', categories=categories, shuffle=True)
test_b = fetch_20newsgroups(subset='test',categories=categories, shuffle=True)
(x_train, y_train) = (train_b.data, train_b.target)
(x_test, y_test) = (test_b.data, test_b.target)

# build, train, and validate model (Transformer is wrapper around transformers library)
import ktrain
from ktrain import text
MODEL_NAME = 'jplu/tf-xlm-roberta-base'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
```

**Comment by amaiya** [comment]
In 0.15.4, I made a change that replaces `xlm-roberta-base` with `jplu/tf-xlm-roberta-base`  under the hood. So, if you update *ktrain* to v0.15.4, supplying `xlm-roberta-base` should work.
