### ISSUE TITLE
Spelling Correction

### ISSUE THREAD

**Issue by laxmimerit** [amaiya/ktrain#161]
I really like a lot ktrain package. This is like a life savior for me. I was looking to use it for spelling correction for English. Do you have any example or can you suggest where to start with ktrain?

**Comment by amaiya** [comment]
@laxmimerit  Thanks for your comments.   I don't have much experience with spelling correction models, but you can take a look at [this](https://github.com/MajorTal/DeepSpell) and [this](https://github.com/huseinzol05/NLP-Models-Tensorflow/tree/master/spelling-correction) and [this](https://github.com/vuptran/deep-spell-checkr). Thanks again.

**Comment by laxmimerit** [comment]
Thanks a lot. It helped.
