### ISSUE TITLE
how to avoid dowload of transformer files

### ISSUE THREAD

**Issue by sathish331977** [amaiya/ktrain#168]
how to avoid torch/tranformers files getting dowloaded when i switch to new environment. 
The files gets downloaded to /home/<user>/.cache/torch/transformers, when i try to load models. Is there a way i can specify the folder to look for these files.

**Comment by amaiya** [comment]
You can copy the models to the `<home_directory>/.cache/torch/transformers` directory of the new machine.  This is typically done when deploying to machines with no internet access, but can also be performed to avoid downloading the models on the new machine.

See [this stackoverflow post](https://stackoverflow.com/questions/62150139/how-to-use-ktrain-for-ner-offline) and [this previous issue](https://github.com/amaiya/ktrain/issues/164).

**Comment by amaiya** [comment]
Also, if you're loading a Predictor for text classification in the new environment (e.g, DistilBert for text classification), you typically only need to copy over a small vocabulary file from `<home_directory>/.cache/torch/transformers ` to avoid downloading anything:
```
$:~/.cache/torch/transformers$ du -sh 26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084 
228K	26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084

```

**Comment by sathish331977** [comment]
Thank you this helps. I was thinking to copy it to ktrain_data. For now i will stick your suggestion.
