### ISSUE TITLE
Unclear how does SimpleQA uses BERT

### ISSUE THREAD

**Issue by ab-10** [amaiya/ktrain#169]
Even though [example QA notebook](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/examples/text/question_answering_with_bert.ipynb) claims in the title that it uses BERT to retrieve answers, looking at the code of `SimpleQA` it looks to me like the code does not use BERT and uses whoosh search alone for QA. The only exception is `predict_squad` and it has not been used in the example notebook.

Did I miss something or is the notebook title erroneous? I'm asking since I'd be curious to see how can BERT be incorporated in search based QA, so if you have any ideas/materials beyond those implemented I'd be interested in incorporating those into this library.

**Comment by amaiya** [comment]
Hello @ab-10 

Yes, you must have missed something, as `SimpleQA` does indeed use BERT to do QA.  The way it uses BERT is described in [this Medium post](https://towardsdatascience.com/build-an-open-domain-question-answering-system-with-bert-in-3-lines-of-code-da0131bc516b). More specifically, the `ask` method, which is invoked in the notebook, performs the following steps:

1. Uses the search index (i.e., `whoosh`) to locate documents that contain words in the question
2.  Extracts paragraphs from these documents for use as contexts and uses a BERT model pretrained on the SQuAD dataset to parse out candidate answers
3. Sorts and prunes candidate answers by confidence scores and returns results

So, you seemed to have missed STEP 2 somehow.  The example notebook invokes the `ask` method, which, in turn, invokes all three steps above (and invokes `predict_squad`. as part of STEP 2).

**Comment by ab-10** [comment]
Thanks a lot for the explanation.
