### ISSUE TITLE
OSError: Can't load weights from 'distilbert-base-uncased'

### ISSUE THREAD

**Issue by rajdeepbasu** [amaiya/ktrain#171]
Hi,

I have used your package to train a text classifier that works well on a laptop without a firewall. However, when I try to do the same on another laptop behind a firewall, I receive an error that says "OSError: Can't load weights for 'distilbert-base-uncased'. The error arises when I invoke the t.getclassifier() function. 

I have read the other solved issues and placed the transformer folder with the downloaded files from one laptop to another in the .cache/torch/transformers location. Yet, the problem persists.

**Comment by amaiya** [comment]
The other solution in the solved issue works if you train the model on a machine with an internet connection, then **save the Predictor**, and then load the Predictor on a a new machine with no internet connection. 

 However, if you're looking to just download the files on the machine with internet and then move them to the second machine behind a firewall with no internet to train the model, then you can try this:

Please try the following:

**STEP 1:  On machine with INTERNET, do this:**
```python
import ktrain
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=list_of_class_labels)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val)
learner.save_model('/tmp/mymodel')
```

**STEP 2: copy the following to the machine with NO INTERNET**
1. contents of `/tmp/mymodel`
2. contents of `<home_directory>/.cache/torch/transformers`

**STEP 3: On machine with NO INTERNET, invoke `get_classifier` with `fpath` argument:**
```python
import ktrain
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=list_of_class_labels)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier(fpath='/tmp/mymodel')
```

I've tested the above and it works.  If you have issues, please let me know.  Note that, with the solution above,  I think you only need the downloaded tokenizer/vocabulary file(s) from `.cache/torch/transformers` that are downloaded when you invoke `t.preprocess_train`.

P.S.  It's unclear why `transformers` library is still trying to access internet when files exist in cache. 
 There's a `local_files_only` argument in `transformers` library, but it doesn't seem to work here as the error is still thrown.

**Comment by amaiya** [comment]
It looks like this error is the result of a bug in the `transformers` library that affects TensorFlow `transformer` models.  The above workaround I posted should work until they fix the problem.

**Comment by rajdeepbasu** [comment]
Hey Amaiya, thank you for the quick response and the debugging. I will try that out. However, something that worked for me on the laptop with internet was I changed the downloaded .h5 file from the random name to tf_model.h5 and the json to config.json. That somehow worked for me. I will go through the code once again and try and check. Thank you once again
