### ISSUE TITLE
ZeroShotClassifier not found

### ISSUE THREAD

**Issue by TolgaGSK** [amaiya/ktrain#173]
Hi, 

I have Pytorch installed but I still get 'module 'ktrain.text' has no attribute 'ZeroShotClassifier' error. Any suggestion? ( Great library for NLP by the way, thanks for your work!)

**Comment by amaiya** [comment]
Hello: Are you sure you're using the latest version of *ktrain* (v0.16.3 as of today)?

What does this output?
```python
import ktrain
print(ktrain.__version__)
```
If you copy and paste this into Google Colab (and set Runtime to GPU) it works with no problem:
```python
!pip3 install -q ktrain
from ktrain import text 
zsl = text.ZeroShotClassifier()
topic_strings=['politics', 'elections', 'sports', 'films', 'television']
doc = 'I am unhappy with decisions of the government and will definitely vote in 2020.'
zsl.predict(doc, topic_strings=topic_strings, include_labels=True)
```

**Comment by TolgaGSK** [comment]
I'm using Spyder for this one and apparently my ktrain version is 0.14.6. I installed it via pip before, how can I upgrade to 0.16.3?

**Comment by amaiya** [comment]
OK - that's the issue then, as `ZeroShotClassifier` wasn't added until v0.16.0.  You can upgrade to current version using either  ```pip3 install -U ktrain``` (or ```pip3 install ktrain==0.16.3``` for specific version).   It should work once you upgrade.  Thanks.

**Comment by TolgaGSK** [comment]
Ah that came out too easy, I though I had the recent version. Thanks so much!
