### ISSUE TITLE
Add new layers on top of BERT

### ISSUE THREAD

**Issue by YLi999** [amaiya/ktrain#178]
Hi, How can I add new layers on top of BERT using ktrain?

By the way, thanks for ktrain. It is really useful.

**Comment by amaiya** [comment]
Thanks.  BERT is supported in two different ways in *ktrain* right now: the `transformers` library (`Transformer('bert-base-uncased', ...)`) and the `keras_bert` package (`text_classifier('bert',..)`). See the `transformers` library source to see how to add layers.  For instance, `TFBertForSequenceClassiication` adds a layer on top of `TFBertModel`.  With `keras_bert`, I believe you can use the standard `tf.keras` functional API with something [like this](https://stackoverflow.com/a/41670915/13550699).
