### ISSUE TITLE
Trained Model Not Getting Saved on Drive

### ISSUE THREAD

**Issue by katreparitosh** [amaiya/ktrain#181]
I was trying to save a trained model using BERT on my preferred location on google drive. I ran the function multiple times, but the model is not appearing/getting saved on the drive. I tried many permutations while passing the path and model name, but it's not helping.

Previously, whenever I used the .save function, it worked smoothly. But, this time the model is not getting saved for hours together somehow.

Kindly help.

**Comment by amaiya** [comment]
It's difficult to help without more information.  Please provide more information in the form of the code/commands you're using.

**Comment by katreparitosh** [comment]
To summarize, I trained a BERT model for text classification purposes. The model was working just fine as expected. It gave expected outputs to sample sentences I passed in the .predict method. 

I went on to save the model using the predictor.save("filepath") method. This command computes and executes without giving any command/typo/argument errors. But when I open my google drive location, no model is present. I tried saving it at different locations on the drive. But, it won't help.

Kindly help. Thank you.

**Comment by amaiya** [comment]
There are two different ways to create BERT text classifiers in *ktrain*,  Which commands did you run to create the classifier?

**Comment by katreparitosh** [comment]
Followed the exact implementation https://github.com/amaiya/ktrain/blob/master/examples/text/20newsgroup-distilbert.ipynb from this ipynb. Just passed 'bert' as a parameter in text.text_classifier() method. The model functions correctly. 

Last week, for another project I created and saved a BERT model. It still works smoothly when I load it in a notebook.

**Comment by amaiya** [comment]
I wasn't able to reproduce this problem   I just tested this on Google Colab and Google Drive and everything worked perfectly.  The predictor files are in my Google Drive as expected.      Since no errors are being generated, perhaps it is saving the files, but you're looking in the wrong path/folder location.
