### ISSUE TITLE
Zero-Shot Learning with Multilingual models

### ISSUE THREAD

**Issue by basque21** [amaiya/ktrain#184]
Hi, thanks for your updates, the ZSL module is amazing!

I want to ask if there is any multilingual model available. I tested and the default model seems to work fine with Spanish, but I can't check if it is multilingual or not, and maybe some other would be better for this purpose.

Thanks again!

**Comment by amaiya** [comment]
Hi! The `ZeroShotClassifier` class takes the `model_name` as an argument.  By default, it uses `facebook/bart-large-mnli`, which I don't think is multilingual, as it was  pretrained on [this corpus](https://cims.nyu.edu/~sbowman/multinli/).  Interesting that it works well on Spanish.  I'm not sure if there are multilingual pretrained BART models in `transformers` yet, but you can monitor the repository of pretrained models to check on Hugging Face website. I believe I saw one or more open issues about this.

**Comment by srulikbd** [comment]
interesting.
I just used to huggingface new translation model for translating the wanted language to english, and then run the ZSL model on the english text.
surprisingly it worked quite well!
MarianMT
https://huggingface.co/transformers/model_doc/marian.html
I didn't find similar NLI corpus in other languages.

**Comment by basque21** [comment]
Hi, thanks for your answer!

I can't go to the link, but I understand the typical workaround of translating to English. What is the exact model you are using?

I also asked in Hugging Face Github whether there is some NLI multilingual model, but it seems that the answer is no.

**Comment by srulikbd** [comment]
yeah.
each model is about 298 MB on disk, there are 1,000+ models.
here is the link
https://huggingface.co/Helsinki-NLP

**Comment by amaiya** [comment]
@srulikbd, : Very interesting - thanks a lot for sharing.

@basque21 ,  it is called [MarianMT](https://huggingface.co/transformers/model_doc/marian.html).  I haven't used it myself, but see [this post](https://github.com/huggingface/transformers/issues/4395) for an example of how to use it.  The `Helsinki-NLP/opus-mt-ROMANCE-en` can evidently translate any romance langauge to English.

**Comment by srulikbd** [comment]
I compared it to Google translate and it's quite good!

**Comment by amaiya** [comment]
I've tested it myself and agree with @srulikbd  that `MarianMT` translations workw quite well.  Direct support for **language translation** has been added in *ktrain* v0.17.x.  See the [example notebook](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/develop/examples/text/language_translation_example.ipynb) for more information.

Thanks again, @srulikbd

**Comment by basque21** [comment]
Wow, it's amazing how quick you implemented, many thanks!!

**Comment by srulikbd** [comment]
@amaiya thanks for your amazing library!!
