### ISSUE TITLE
Deployment of Ktrain based Albert model

### ISSUE THREAD

**Issue by sridhar-rv** [amaiya/ktrain#185]
Hi ,

My environment details:

Centos 7.5
Python 3.7
Tensorflow 2.1
Ktrain 0.14.5

I have built a classifier (in training instance) using ALBERT transformer. (The model directory contains three files viz  json,tf_model.h5 and .preproc files)

Im able to do the prediction as follows. ( I get class name as result )

myModel = ktrain.load_predictor('model/')
question = sys.argv[1]
myAnswer =  myModel.predict(question)

 I have deployed the model  to QA instance now. I run the same prediction script and I get the following error

Traceback (most recent call last):
  File "albertPredict.py", line 7, in <module>
    myModel = ktrain.load_predictor('model/')
  File "/usr/local/lib/python3.7/site-packages/ktrain/core.py", line 1328, in load_predictor
    preproc = pickle.load(f)
  File "/usr/local/lib/python3.7/site-packages/transformers/tokenization_albert.py", line 185, in __setstate__
    self.sp_model.Load(self.vocab_file)
  File "/usr/local/lib/python3.7/site-packages/sentencepiece.py", line 118, in Load
    return _sentencepiece.SentencePieceProcessor_Load(self, filename)
****OSError: Not found:** **"/home/xxxx/.cache/torch/transformers/dd1588b85b6fdce1320e224d29ad062e97588e17326b9d05a0b29ee84b8f5f93.c81d4deb77aec08ce575b7a39a989a79dd54f321bfb82c2b54dd35f52f8182cf": No such file or directory Error #2****

Please let me know whether any prereq file needs to be available in QA instance. Apart from Python3.7, Ktrain, Tensorflow I do not have anything in this instance. What is it looking for in Cache dir ? Any vocab file for creating embeddings ???

Thanks
Sridhar

**Comment by amaiya** [comment]
If you're using a `transformers` model and loading a `Predictor` instance on a new machine, the vocab files need to be present in the cache on the new machine, which seems to be missing in your case.  Typically, the `transformers` library will download it to cache of new machine if it doesn't exist.  However, the error is saying that the it can't file one of the cached files required for tokenization on deployment instance.  

Not sure why `transformers` didn't download the required files.   But, the solution is to copy the cache folder (i.e., `<home_directory?/.cache/torch/transformers` to the QA instance).  Specifically, this file is important for Albert:
```
dd1588b85b6fdce1320e224d29ad062e97588e17326b9d05a0b29ee84b8f5f93.c81d4deb77aec08ce575b7a39a989a79dd54f321bfb82c2b54dd35f52f8182cf
```

If you open that file with vim or nano, you'll probably see that it's the vocab file for ALBERT.

If the deployment instance is being used to train/re-train a model, and doesn't have internet connection or is behind a firewall, then there are [additional considerations](https://github.com/amaiya/ktrain/blob/develop/FAQ.md#how-do-i-use-ktrain-without-an-internet-connection)
