### ISSUE TITLE
BERT model makes the same prediction for every input.

### ISSUE THREAD

**Issue by ccrupp** [amaiya/ktrain#186]
I am using the Ktrain library on a binary classification task, there are about 1400 documents with 862 positive documents and 538 negative documents. After loading the data from a pandas data frame and training the model using the .fit function, I tried making a few predictions and the model always makes a prediction of positive regardless of the input.

**Comment by amaiya** [comment]
As you can see from the [example notebooks](https://github.com/amaiya/ktrain/blob/master/examples/text/IMDb-BERT.ipynb), everything works as expected.  There's a problem in your code or data, but it's impossible to say without seeing either.  If you need further help, please provide more information.
