### ISSUE TITLE
Loading the saved learner as `.from_pretrained`

### ISSUE THREAD

**Issue by Guillermogsjc** [amaiya/ktrain#187]
Hi,

I have a ktrain learner that is made of a tokenizer and transformer from HuggingFace.

The use case I would want to have is:

- Train a classification with this learner.
- Save the learner in disk.
- Load the updated model  using transformers library classes using:
```python
AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
AutoTokenizer.from_pretrained(model_name_or_path, cache_dir=cache_dir)
```

By this way, you can update the transformer downloaded from huggingface using ktrain, and yet can save it and keep using it from other libraries in the ecosystem (like `sentence-transformers`, for example).

Is there any way of saving the models trained with ktrain so the *pretrained*  format files are in the same format than hugginface transformers and tokenizers standard?

Kind regards.

**Comment by amaiya** [comment]
Yes, you can do this easily, as *ktrain* is just a lightweight wrapper.  So, once you train the model, you can manage it directly using `transformers`, `tensorflow`, or use it with other libraries like `sentence-transformers`. There are several ways to do this.

After you train the model using the `Learner` object, you can save it with:
```python
learner.save_model('/tmp/some_path')
```
If the model you're saving is a Hugging Face `transformers` model, then the above command will simply save the model using `save_pretrained`, so it will be in the format expected by `transformers`.  This will create the folder `'tmp/some_path'` if it doesn't already exist.  

Alternatively, you can access the underlying `transormers` model directly and invoke `save_pretrained` explicitly with `learner.save_pretrained('/tmp/some_path')`.   See [here](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-obtain-the-word-or-sentence-embeddings-after-fine-tuning-a-transformer-based-text-classifier) for an example of this.  The underlying TensorFlow model is always directly accessible with `learner.model`.


Note that the above will save a `transformers` model in TF2 format.  If you need, you can convert it to a PyTorch model using the `transformers` library.

**Comment by amaiya** [comment]
Two additional comments:

*ktrain* does not save  tokenizers for `transformers` models, as they are not modified as part of training.  So, if you need them, you can load them directly using the `transformers` library in which case the tokenizer will be loaded from cache (and downloaded if necessary).

Also, when saving a `Predictor` instance for a `transformers` model, the model is also saved in the correct/expected format and can be re-loaded and used with other libraries:
```python
p = ktrain.get_predictor(learner.model, t)
p.save('/tmp/mypred')  # folder will contain the transformers model as tf_model.h5 (same as save_pretrained)

**Comment by Guillermogsjc** [comment]
Great! Thank you very much @amaiya
