### ISSUE TITLE
Error with input length

### ISSUE THREAD

**Issue by YLi999** [amaiya/ktrain#188]
I have successfully run the exact same code with exact same data last night, but it gave me the following error tonight. 

The code and error are shown below, thank you!
![error](https://user-images.githubusercontent.com/55957237/86176347-b518c800-bb1c-11ea-8c4e-ddc5acde2a8d.png)

**Comment by amaiya** [comment]
The `transformers` library was just updated to v3.0.0 yesterday.    I've tested sentence pair classification with v3.0.0 on [MRPC dataset](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/develop/examples/text/MRPC-BERT.ipynb) and everything still works.  So, I wasn't able to reproduce this problem. All other *ktrain* v0.17.3 tests pass with v3.0.0 of `transformers`, as well.

If you're using `transformers==3.0.0`, can you try downgrading to 2.11 and let me know what happens?

**Comment by YLi999** [comment]
> The `transformers` library was just updated to v3.0.0 yesterday. I've tested sentence pair classification with v3.0.0 on [MRPC dataset](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/develop/examples/text/MRPC-BERT.ipynb) and everything still works. So, I wasn't able to reproduce this problem. All other _ktrain_ v0.17.3 tests pass with v3.0.0 of `transformers`, as well.
> 
> If you're using `transformers==3.0.0`, can you try downgrading to 2.11 and let me know what happens?

After I downgrade transformers to 2.11.0, I can run the code.

**Comment by amaiya** [comment]
Are you training on a publicly available training set that you can share?

**Comment by YLi999** [comment]
> Are you training on a publicly available training set that you can share?
> 
> I think this is a bug in the v3.0.0 of `transformers`, but I'm not able to reproduce it on my end.

Here is the link for the publicly available training set I used:
https://figshare.com/articles/RumourEval_2019_data/8845580

Thanks

**Comment by amaiya** [comment]
Thanks - I looked at the link briefly, but it wasn't immediately clear to me how you preprocessed this dataset for sentence pair classification with three classes.  It sounds like `encode_plus` method in `transformers==3.0.0` isn't correctly truncating to `max_length` for at least one example in your dataset.

If you have `x_test` available and post it somewhere as CSV or something, I can look into it.  (It looks like the problematic example is in `x_test`.)

Otherwise, you can maybe add a `print` statement and post the text of the example that is throwing the error.  

Thanks.

**Comment by YLi999** [comment]
> Thanks - I looked at the link briefly, but it wasn't immediately clear to me how you preprocessed this dataset for sentence pair classification with three classes. It sounds like `encode_plus` method in `transformers==3.0.0` isn't correctly truncating to `max_length` for at least one example in your dataset.
> 
> If you have `x_test` available and post it somewhere as CSV or something, I can look into it. (It looks like the problematic example is in `x_test`.)
> 
> Otherwise, you can maybe add a `print` statement and post the text of the example that is throwing the error.
> 
> Thanks.

Hi, I have put the test data here:   https://github.com/YLi999/Test-data

**Comment by amaiya** [comment]
Thanks for help @YLi999 .  I found the cause of the problem after trying your CSV:  default truncation strategy in `transformers==3.0.0` was changed which breaks sentence pair classification.    The simple fix is to explicitly provide the truncation strategy. I've updated *ktrain*, so `transformers==3.0.0` should work with v0.17.4 of *ktrain*.
