### ISSUE TITLE
No matching tensforflow distribution (in kubuntu)

### ISSUE THREAD

**Issue by ECon87** [amaiya/ktrain#189]
I am on Kubuntu 20.04, KDE Plasma 5.18.5, and the latest version of pip.

I run:
```
pip install ktrain
```
and it returns

```
Collecting ktrain
  Using cached ktrain-0.17.3.tar.gz (25.2 MB)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.1.0 (from ktrain) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0)
ERROR: No matching distribution found for tensorflow==2.1.0 (from ktrain)
```
I was able to separately install tensorflow 2.2.0.

**Comment by amaiya** [comment]
Hi:

You need to upgrade pip first before installing *ktrain*: `pip3 install -U pip`

This is indicated in the [installation instructions](https://github.com/amaiya/ktrain#installation).

**Comment by amaiya** [comment]
Also, note that *ktrain* currently uses TensorFlow 2.1.0, not 2.2.0.  There are some breaking changes in TensorFlow 2.2.0 and required changes have not yet been added to *ktrain*.  Most things should work in TensorFlow 2.2.0, though.

**Comment by ECon87** [comment]
> Hi:
> 
> You need to upgrade pip first before installing _ktrain_: `pip3 install -U pip`
> 
> This is indicated in the [installation instructions](https://github.com/amaiya/ktrain#installation).

Yeah I did that, but it didn't work. I did again just to be sure.

Also I installed the tensorflow 2.2.0 after the ktrain installation failed just to make sure that it installs fine.

I am on python 3.8 if that matters.

I was able to install ktrain on my Mac High Sierra python 3.7 conda environment (though it's not imported but that's a problem with the tokenizer package). In the python 3.8 environment i realized that I get the same error message ("no matching distribution")

**Comment by amaiya** [comment]
Yes, the Python 3.8 does matter.  **TensorFlow 2.1.0 does not support Python 3.8**, which explains the error you're getting.  

Like I said, you can use TensorFlow 2.2.0 and most things in *ktrain* will still work.  There are a few things that won't right ow (e.g., `view_top_losses`, `set_weight_decay`), but everything else should work.  These breaking changes with TensorFlow 2.2.0 will be resolved in a future update.

To use *ktrain* with TensorFlow 2.2.0, you just install TensorFlow **after** *ktrain* is installed, as you've already done.

**Comment by amaiya** [comment]
I haven't tried installing *ktrain* with Python 3.8.  But, if the only problem is the incompatibility between TensorFlow 2.1.0 and Python 3.8, you can:

1. clone the *ktrain* repository
2. remove the TensorFlow 2.1.0 dependency from `setup.py`
3. Install TensorFlow 2.2.0 separately 
4. Using Python3.8 and run `python setup.py install` to install *ktrain*

**Comment by ECon87** [comment]
Thanks for the suggestions. I used python3.7 and it installed just fine. But it's good to know the above steps for the future.

**Comment by amaiya** [comment]
Great - *ktrain* will support Python 3.8 along with TensorFlow 2.2.0 in the near future.
