### ISSUE TITLE
Running pre-trained model with CPU

### ISSUE THREAD

**Issue by YLi999** [amaiya/ktrain#192]
Hi, I trained a BERT-based model using GPU and saved this model. Is it possible to use it in the CPU mode?

I have tried to install ktrain in the CPU mode of Google Colab, and used "ktrain.load_predictor" to load the pre-trained model, but I failed. 
The error is "Unable to load weights from h5 file. If you tried to load a TF 2.0 model from a PyTorch checkpoint, please set from_pt=True."

Many Thanks

**Comment by amaiya** [comment]
I don't think this has anything to do with loading a GPU-trained model on a CPU.  I just did this, and it worked for me with no problem.

That error is coming from `transformers` library directly.  If you provide more information (like the model and data you're using, a link to Colab notebook to reproduce the problem), I can try to investigate further.

**Comment by YLi999** [comment]
> I don't think this has anything to do with loading a GPU-trained model on a CPU. I just did this, and it worked for me with no problem.
> 
> That error is coming from `transformers` library directly. If you provide more information (like the model and data you're using, a link to Colab notebook to reproduce the problem), I can try to investigate further.

Yes, you are right. I tested it again this morning and it works. But I'm not sure what I did yesterday led to the error. Anyway, it works now.
Thanks!
