### ISSUE TITLE
custom tokenization

### ISSUE THREAD

**Issue by peterbayerle** [amaiya/ktrain#196]
the Bert classifier only considers at most the first 512 tokens. Seems like the ktrain algorithm considers the first of the maximum specified length. Is there any way to consider, say, the first 256 and the last 256? Thanks.

**Comment by amaiya** [comment]
You can try "pre-truncating" the text in the way you want prior to feeding the text to `preprocess_train` and `preprocess_test`.
It's only approximate though because transformer models tokenize some words into subwords.
