### ISSUE TITLE
Multiple classifications from the same dataset

### ISSUE THREAD

**Issue by cyberandy** [amaiya/ktrain#202]
Hi, this library is awesome 🦾 I am working on a text classification problem and I would like to predict two values: a single value for category A and a single value for category B, starting from the same text (120-130 words in English). 
Are there any examples that I can look at?

**Comment by amaiya** [comment]
Hi:  Thanks.  If the two values are not mutually exclusive (i.e., both Category A and Category B can have 99% softmax probability for same example), then this is a multilabel classification problem and you can look at the multilabel section of the [text classification tutorial](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-04-text-classification.ipynb).

If the probabilities are mutually-exclusive, you can get the "probabilities" of both classes using `return_proba=True`, which is also described/demonstrated in the same tutorial above (E.g., 95% for Category A, 5% for Category B).

**Comment by cyberandy** [comment]
Thanks will look more closely into it.

**Comment by mlaugharn** [comment]
Is it possible to have multiple indepedent multiclassification for each output? e.g. f(x) = [3, 2, 5] where the classes can be categories from 0 to 10 each?
