### ISSUE TITLE
Is there a way to use DistilBERT with ktrain's qa function?

### ISSUE THREAD

**Issue by mjoy296** [amaiya/ktrain#207]
I am trying to create a question answering application using Flask however the BERT model takes a while to return an answer and am looking for something a bit faster. I have been trying to use `transformers` `TFDistilBertForQuestionAnswering` instead of `TFBertForQuestionAnswering`. However, `TFDistilBertForQuestionAnswering` doesn't have the `token_type_ids` parameter. When I do this and ask a question, I get responses that have nothing to do with what was asked. 

I have tried:
  
      class QA(ABC):
             """
             Base class for QA
              """
              ##----------------changed model to distilbert------------------
             def __init__(self, bert_squad_model='distilbert-base-uncased-distilled-squad ', 
                       bert_emb_model='distilbert-base-uncased'):
                  self.model_name = bert_squad_model
                 #changed to TFDistilBERT
                 self.model = TFDistilBertForQuestionAnswering.from_pretrained(self.model_name)
                 self.tokenizer = DistilBertTokenizer.from_pretrained(self.model_name)
            ##----------------------------------------------------------
                 self.maxlen = 512
                 self.te = tpp.TransformerEmbedding(bert_emb_model, layers=[-2])
 
 
 
    def predict_squad(self, document, question):
            input_ids = self.tokenizer.encode(question, document)
            tokens = self.tokenizer.convert_ids_to_tokens(input_ids)
            sep_index = input_ids.index(self.tokenizer.sep_token_id)
            num_seg_a = sep_index + 1
            num_seg_b = len(input_ids) - num_seg_a
            segment_ids = [0]*num_seg_a + [1]*num_seg_b
            assert len(segment_ids) == len(input_ids)
            n_ids = len(segment_ids)

          ###-----removed token_type_id from self.model -----------
            if n_ids < self.maxlen:
                 start_scores, end_scores = self.model(np.array([input_ids]))
            else:  
                #TODO: use different truncation strategies or run multiple inferences
                 start_scores, end_scores = self.model(np.array([input_ids[:self.maxlen]]))
         ###------------------------------------------------------

            start_scores = start_scores[:,1:-1]
            end_scores = end_scores[:,1:-1]
            answer_start = np.argmax(start_scores)
            answer_end = np.argmax(end_scores)
            answer = self._reconstruct_text(tokens, answer_start, answer_end+2)
            if answer.startswith('. ') or answer.startswith(', '):
                answer = answer[2:]
            sep_index = tokens.index('[SEP]')
            full_txt_tokens = tokens[sep_index+1:]
            paragraph_bert = self._reconstruct_text(full_txt_tokens)
 
            ans={}
            ans['answer'] = answer
            if answer.startswith('[CLS]') or answer_end < sep_index or answer.endswith('[SEP]'):
                ans['confidence'] = LOWCONF
            else:
                #confidence = torch.max(start_scores) + torch.max(end_scores)
                #confidence = np.log(confidence.item())
                ans['confidence'] = start_scores[0,answer_start]+end_scores[0,answer_end]
            ans['start'] = answer_start
            ans['end'] = answer_end
            ans['context'] = paragraphs.  bert
            return ans
 
 
 
      class SimpleQA(QA):
            """
            SimpleQA: Question-Answering on a list of texts
            """
            ##---------------changed model down here too -----------------
                def __init__(self, index_dir,
                         bert_squad_model='distilbert-base-uncased-distilled-squad',
                         bert_emb_model='distilbert-base-uncased'):`

Do you have any suggestions as how to use DistilBERT with ktrain's qa? Thanks!

**Comment by amaiya** [comment]
If you install the latest version of *ktrain* (v0.18.5),  you should now be able to use `distilbert-base-cased-distilled-squad` without your manual adjustments.  You can also try using these alternative fine-tuned SQuAD models that should also be faster:

```python
# small
qa = text.SimpleQA(INDEXDIR, bert_squad_model='mrm8488/bert-small-finetuned-squadv2')
# or try tiny
qa = text.SimpleQA(INDEXDIR, bert_squad_model='mrm8488/bert-tiny-finetuned-squadv2')
```
Also, when using a different SQuAD model to speed things up, you don't also need to change the `bert_emb_model` parameter, as that does not impact overall speed of `ask`.

The candidate answers I got for `bert-small-finetuned-squadv2` and  `distilbert-base-cased-distilled-squad` were good in some cases, but not as good as BERT in a other cases.  They were all somewhat reasonable in that they were related to question though even when wrong.  You can try changing the extra parameters to `ask` to adjust/balance speed and quality.
