### ISSUE TITLE
Distributed with ktrain

### ISSUE THREAD

**Issue by neryacohen** [amaiya/ktrain#210]
Is there a way to use ktrain with distributed GPUs using MPI ?

**Comment by amaiya** [comment]
You place the model-creation step into an available strategy, which are all described on the TensorFlow [distributed training page](https://www.tensorflow.org/guide/distributed_training).   The [ParameterServerStrategy](https://www.tensorflow.org/guide/distributed_training#parameterserverstrategy) supports training on multiple machines, but support for this in `tf.Keras` isn't planned until TensorFlow 2.3, I think.
