### ISSUE TITLE
Unable to reload model

### ISSUE THREAD

**Issue by anmaxwell** [amaiya/ktrain#213]
Hi,
I successfully trained a model and used predictor.save() to generate tf_model.h5 and tf_model.preproc.

I have a new colab notebook and have uploaded both files to a new folder.  I am trying to reload the model from the folder they are saved to using:
 reloaded_predictor = ktrain.load_predictor('/content/callcommentbert')

I am getting the error 'ValueError: model must be of instance Model'

My ktrain version is 0.18.5 and my tensorflow is version 2.1.0

I am able to reload the model in the colab book where I trained the model so I know it works but I'm sure I've missed something when trying to reload it on its own.

Many thanks

**Comment by amaiya** [comment]
On the notebook that doesn't work, what is the output of:
```
!ls /content/callcommentbert
```

**Comment by anmaxwell** [comment]
Hi,

Thank you so much for getting back to me!

The folder just contains the 2 files ‘tf_model.h5’ and ‘tf_model.preproc’

**Comment by anmaxwell** [comment]
Just as an update to this - I have tried loading this locally rather than through colab and it seems to load sucessfully.  I am currently having an issue running it 'TypeError: 'TextPredictor' object is not callable' so i'm currently investigating that now as well.
Hope this helps.
