### ISSUE TITLE
Add support for custom tokenization in ktrain ner models

### ISSUE THREAD

**Issue by rohith93** [amaiya/ktrain#222]
Add support for custom tokenization in predict function of ktrain ner models. tokenization performed by  predict function uses all special character which breaks entities like date-time , mobile-number with extension, emailId into multiple parts which is not desirable.

**Comment by loge1998** [comment]
I am also facing the same issue. Can i create a pull request to resolve this?

**Comment by loge1998** [comment]
https://github.com/amaiya/ktrain/blob/53d79d9504ef2da9e8bb96a46e2fa67c607641f9/ktrain/text/textutils.py#L306
This is the function creating issue I think. It tokenize the word based on space and special characters which is a bad idea if we have date, email id as classes in classifier. During training process, It allow sentence to have own tokenization. but in predict function it tokenize word based on set of characters. it will be better if we can configure those characters based on our need. thank you so much. I hope you will close the issue asap.

**Comment by amaiya** [comment]
OK - we can add a parameter to `NERPredictor.predict` method to accept a custom tokenization callable in which case it will be used instead of the default tokenization.

@loge1998  Yes.  If you want to create a pull request for this, I'll merge.

**Comment by loge1998** [comment]
If thats the case, we also have to add parameter to preproc.preprocess function

**Comment by loge1998** [comment]
#223 created a PR for this issue. Please check and merge it

**Comment by amaiya** [comment]
Thanks @loge1998 .  This feature is now available in v0.19.3.
