### ISSUE TITLE
HuggingFace models cause ValueError: invalid name for text classification

### ISSUE THREAD

**Issue by jordan-bird** [amaiya/ktrain#224]
Hi,

In the medium article written by yourself it says "Next, we must select one of the pretrained models from Hugging Face, which are all listed here". In the colab example, if you change the model to a Huggingface transformer eg 'distilbert-base-uncased' from the article or the HF page, the following error occurs:

```
import ktrain
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
model = text.text_classifier(MODEL_NAME, (x_train, y_train), 
                             preproc=preproc)
learner = ktrain.get_learner(model, train_data=(x_train, y_train), val_data=(x_test, y_test), batch_size=32)
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-61fc86135b10> in <module>()
     10 
     11 model = text.text_classifier(MODEL_NAME, (x_train, y_train), 
---> 12                              preproc=preproc)
     13 learner = ktrain.get_learner(model, train_data=(x_train, y_train), val_data=(x_test, y_test), batch_size=32)

/usr/local/lib/python3.6/dist-packages/ktrain/text/models.py in text_classifier(name, train_data, preproc, multilabel, metrics, verbose)
    464     """
    465     if name not in TEXT_CLASSIFIERS:
--> 466         raise ValueError('invalid name for text classification: %s' % (name))
    467     if preproc is not None and not preproc.get_classes():
    468         raise ValueError('preproc.get_classes() is empty, but required for text classification')

ValueError: invalid name for text classification: distilbert-base-uncased
```

In text/models.py I see the following which don't include the ones mentioned in your article:
```
NBSVM = 'nbsvm'
FASTTEXT = 'fasttext'
LOGREG = 'logreg'
BIGRU = 'bigru'
STANDARD_GRU = 'standard_gru'
BERT = 'bert'
DISTILBERT = tpp.DISTILBERT
HUGGINGFACE_MODELS = [DISTILBERT]
LINREG = 'linreg' 
```

How does one go about using the pretrained models from HF transformers? Are they still supported?

Thank you!

https://towardsdatascience.com/text-classification-with-hugging-face-transformers-in-tensorflow-2-without-tears-ee50e4f3e7ed

**Comment by amaiya** [comment]
Hello,

It looks like you're mixing two different APIs in *ktrain*.  

**API 1**
The `text_classifier` API (described in [this tutorial](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-04-text-classification.ipynb)) only supports the models listed (which includes both non-transformer models and a small set of transformer models).  The `distilbert-base-uncased` model is supported in this API (by supplying `distilbert` to `text_classifier` function in addition to the data-loading function.  See [this notebook](https://github.com/amaiya/ktrain/blob/master/examples/text/20newsgroup-distilbert.ipynb) for how to use `distilbert-base-uncased` using this API.

**API 2**
The [article you mentioned](https://towardsdatascience.com/text-classification-with-hugging-face-transformers-in-tensorflow-2-without-tears-ee50e4f3e7ed) demonstrates the `Transformer` API in *ktrain* which allows you to use any `transformers` model for text classification.  Here is a self-contained example for how to use `distilbert-base-uncased` using the `Transformer` API (which is pretty much exactly what is also shown in the article):


```python
# load text data
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
from sklearn.datasets import fetch_20newsgroups
train_b = fetch_20newsgroups(subset='train', categories=categories, shuffle=True)
test_b = fetch_20newsgroups(subset='test',categories=categories, shuffle=True)
(x_train, y_train) = (train_b.data, train_b.target)
(x_test, y_test) = (test_b.data, test_b.target)

# build, train, and validate model (Transformer is wrapper around transformers library)
import ktrain
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
learner.fit_onecycle(5e-5, 1)
learner.validate(class_names=t.get_classes()) # class_names must be string values

```
