### ISSUE TITLE
provide a way to use parts of ktrain without tensorflow installed

### ISSUE THREAD

**Issue by MiniXC** [amaiya/ktrain#225]
## Tensorflow
Right now, tensorflow has to be installed even when I (as in my use case) only want to use zero shot learning, which only requires pytorch and huggingface transformers. I know it is still possible to install this without dependencies with
``pip install ktrain --no-deps``, but tensorflow is still imported even when I only import a module like zero shot learning that does not use it.
Thanks for making this amazing library available and maintaining it!

**Comment by amaiya** [comment]
Thanks for your comments.  Out of curiosity, why is having TensorFlow installed a problem? Do you want to simply maintain a smaller footprint on the machine being used or is there some other problem?

**Comment by amaiya** [comment]
In v0.19.4, you can use `ZeroShotClassifier` without having TensorFlow installed as follows:

```python
# install ktrain with --no-deps option and manually install torch and transformers
# Then, import and use zsl module as follows:

import importlib
import pathlib
import sys
import types


def import_module_from_path(path) -> types.ModuleType:
  """Import a module from the given path."""
  module_path = pathlib.Path(path).resolve()
  module_name = module_path.stem  # 'path/x.py' -> 'x'
  spec = importlib.util.spec_from_file_location(module_name, module_path)
  module = importlib.util.module_from_spec(spec)
  sys.modules[module_name] = module
  spec.loader.exec_module(module)
  return module

# Import `my_module` without executing `/path/to/__init__.py`
my_module = import_module_from_path('/path/to/ktrain/text/zsl/core.py') # replace with path on your system
zsl = my_module.ZeroShotClassifier()
topic_strings=['politics', 'elections', 'sports', 'films', 'television']
doc = 'I am unhappy with decisions of the government and will definitely vote in 2020.'
print(zsl.predict(doc, topic_strings=topic_strings, include_labels=True))



```
