### ISSUE TITLE
Generating Word/Sentence Embeddings from fine-tuned BERT model?

### ISSUE THREAD

**Issue by larry33legend** [amaiya/ktrain#226]
Similar to Bert as a Service, is there any in-house way to generate these embeddings with ability to control context (Pooling = None)?

**Comment by amaiya** [comment]
Yes, there is.  Please see [this FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-obtain-the-word-or-sentence-embeddings-after-fine-tuning-a-transformer-based-text-classifier), for example.

**Comment by larry33legend** [comment]
Thanks a lot, can't believe I missed that. Sorry for wasting your time. Great work on this library.
