### ISSUE TITLE
Albert MODEL compression

### ISSUE THREAD

**Issue by sridhar-rv** [amaiya/ktrain#231]
Hi,

Is there any wrapper available to compress the trained model. I found that QUANTIZATION available for TF, Keras and Pytorch. How can this be applied to Pytorch based transformers when Ktrain wrapper is used ?

Thanks
Sridhar

**Comment by amaiya** [comment]
You'll be able to do this directly with `transformers` with [this PR](https://github.com/huggingface/transformers/pull/6089), but it may not have been been officially released yet.
