### ISSUE TITLE
Logo for Ktrain

### ISSUE THREAD

**Issue by vimal-quilt** [amaiya/ktrain#235]
Hi Arun,
Thanks for your great effort in bringing this library to a novice like me. I would suggest a logo so that i shall credit with the link with the blog post / training material i am preparing.

**Comment by amaiya** [comment]
Hi @vimal-quilt.   Thanks for comments and suggestion.   The logo for ktrain is [here](https://github.com/amaiya/ktrain/blob/develop/ktrain_logo_200x100.png).
