### ISSUE TITLE
Quantization of MarianNMT models within KTRAIN

### ISSUE THREAD

**Issue by xirect** [amaiya/ktrain#236]
Hi!

I was wondering if the torch.quantization.quantize_dynamic() would be use able within the Translator object. Right now translation takes around 1.7 seconds per article, maybe you know a different method to speed it up?

**Edit**
I tried to use the torch quantization method myself, resulting in errors.

Below the code which I tried it with.

```
import torch
from transformers import MarianMTModel, MarianTokenizer

model_name = "Helsinki-NLP/opus-mt-nl-en"
tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name).to("cuda")
torch.quantization.quantize_dynamic(
    model, qconfig_spec=None, dtype=torch.qint8, mapping=None
)
```

This results in the following error message.

`RuntimeError: Could not run 'quantized::linear_prepack' with arguments from the 'UNKNOWN_TENSOR_TYPE_ID' backend. 'quantized::linear_prepack' is only available for these backends: [QuantizedCPU].`

**Edit 2**
I tried it without the .to("cuda"), which creates a quantized model on CPU, still can't get it to work op GPU.

**Comment by amaiya** [comment]
Hi @xirect :  You can maybe try to quantize using the `transformers` library itself with [this PR](https://github.com/huggingface/transformers/pull/6089).

**Comment by xirect** [comment]
Still couldn't get it working.

**Comment by amaiya** [comment]
If the goal is a 1-time translation of many articles, you might get more of a speedup if splitting up the documents and translating them using multiple GPUs in parallel using cloud computing environments like AWS and Google Colab.  If you still want to try quantization, you can try asking the question on the `transformers` [help forum](https://discuss.huggingface.co/).

**Comment by xirect** [comment]
@amaiya the goal would be a one time translation for a major batch of texts, plus on collection of new data, so scaling in the cloud would not really be feasible. Any other idea's to speed up performance?

I was also able to quantize the model for CPU usage, the time increase is not enough for me to use.

**Comment by amaiya** [comment]
The translator tokenizes document into sentences and feeds the list of sentences to the model as a single batch.  If you have lots of smaller articles, the small number of sentences means a lower batch size is used.  In v0.21.0 of *ktrain*, there is a `translate_sentences` method that accepts a list of sentences to translate.  You can tokenize your articles into sentences yourself and feed larger batches of sentences to `translate_sentences` in order to make better use of the GPU, which may speed things up.
