### ISSUE TITLE
Got installation error messages when installing into venv on Linux Mint 19.3

### ISSUE THREAD

**Issue by dwvisser** [amaiya/ktrain#237]
Repro Steps:

1. `python3 -m venv ktrain`
2. `source ktrain/bin/activate`
3. `pip install -U pip`
4. `pip install ktrain`

I got the following error messages:

```shell
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

google-auth 1.20.1 requires setuptools>=40.3.0, but you'll have setuptools 39.0.1 which is incompatible.
tensorboard 2.1.1 requires setuptools>=41.0.0, but you'll have setuptools 39.0.1 which is incompatible.
tensorflow 2.1.0 requires scipy==1.4.1; python_version >= "3", but you'll have scipy 1.5.2 which is incompatible.
tensorflow-metadata 0.23.0 requires absl-py<0.9,>=0.7, but you'll have absl-py 0.10.0 which is incompatible.
```

Those last two are probably really tensorflow 2.1.0 dependency issues, but perhaps the installation instructions should also specify doing a `pip install -U setuptools` before installing ktrain.

**Comment by dwvisser** [comment]
In the above venv:

```shell
$ python --version
Python 3.6.9
```

**Comment by dwvisser** [comment]
I just tried with a new venv with step 3 above changed to `pip install -U pip setuptools`, and the error message reduces to just this:

```shell
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

tensorflow-metadata 0.23.0 requires absl-py<0.9,>=0.7, but you'll have absl-py 0.10.0 which is incompatible.
```

**Comment by dwvisser** [comment]
I also noticed that if I do a `pip install wheel`, many of the dependency installations go much quicker.

**Comment by amaiya** [comment]
Thanks,

These errors are really coming from `pip install tensorflow`, as the default `setuptools` in your virtual environment is out-dated.  For whatever reason, Google doesn't seem to require upgrading `setuptools` in [their installation instructions](https://www.tensorflow.org/install/pip), so it was never included in the installation instructions for *ktrain* either.

Note that these errors you're seeing don't really affect *ktrain* operation. So, everything should work fine without upgrading `setuptools`. 

But, changing the *ktrain* installation instructions to include `pip install -U pip setuptools` would probably be a good idea.

**Comment by amaiya** [comment]
In v0.21.x of *ktrain*, TensorFlow 2.1 is no longer automatically installed, which allows *ktrain* to be used with whatever version of TensorFlow 2 the user has chosen to install.
