### ISSUE TITLE
Supporting Electra-architecture models

### ISSUE THREAD

**Issue by mapmeld** [amaiya/ktrain#238]
Currently if you load an Electra-based model such as https://huggingface.co/monsoon-nlp/hindi-bert in ktrain, Transformers raises an error because of an issue with `TFElectraForSequenceClassification`

I looked into this:
If model_type is "electra", that's not in the list of `TRANSFORMER_MODELS` in `text/preprocessor.py`, so ktrain uses the AutoModel fallback, `TFAutoModelForSequenceClassification`.

The master branch of Transformers on GitHub can map this to `TFElectraForSequenceClassification`, but the current pip release (3.0.2, released July 6 2020) does not. So if someone is running this code today, I'd advise them to `pip install ktrain` and then afterward `git clone https://github.com/huggingface/transformers` and `pip install .` from source.

I tried extending ktrain to connect models to `(ElectraConfig, TFElectraForSequenceClassification, ElectraTokenizer, TFElectraModel)`, but also I cannot import these from the current pip release of Transformers

Sample notebook: https://colab.research.google.com/drive/1mSeeSfVSOT7e-dVhPlmSsQRvpn6xC05w

I also found some success in changing the model_type of an Electra model to "bert" - the architecture is very similar.
When the next Transformers release comes out, I'd recommend updating setup.py to the latest version

**Comment by amaiya** [comment]
Very interesting work!   

Yes, the current version of **transformers** has `ElectraForSequenceClassification` (PyTorch), but not `TFElectraForSequenceClassification` (TensorFlow).  As you said, it looks like `TFElectraForSequenceClassification` will be included in the next release of **transformers**.  So, when the next version of **transformers** is released, we can modify `setup.py` and require latest **transformers**, as you suggested, to ensure these models will work with no problem.

**Comment by amaiya** [comment]
In v0.21.x of *ktrain*,  `transformers>=3.1.0` is required which includes `TFElectraForSequenceClassification`.
