### ISSUE TITLE
Problems with loading some huggingface models

### ISSUE THREAD

**Issue by lambdaofgod** [amaiya/ktrain#239]
When I try to use roberta-base-openai-detector 
```

MODEL_NAME = 'roberta-base-openai-detector'
transformer = ktrain.text.Transformer(MODEL_NAME, maxlen=90)

model = transformer.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=32, workers=8)
```

I get
---------------------------------------------------------------------------

OSError                                   Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/transformers/modeling_tf_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    461                 if resolved_archive_file is None:
--> 462                     raise EnvironmentError
    463             except EnvironmentError:

OSError: 
```


During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)

3 frames

/usr/local/lib/python3.6/dist-packages/transformers/modeling_tf_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    467                     f"- or '{pretrained_model_name_or_path}' is the correct path to a directory containing a file named one of {TF2_WEIGHTS_NAME}, {WEIGHTS_NAME}.\n\n"
    468                 )
--> 469                 raise EnvironmentError(msg)
    470             if resolved_archive_file == archive_file:
    471                 logger.info("loading weights file {}".format(archive_file))

OSError: Can't load weights for 'roberta-large-openai-detector'. Make sure that:

- 'roberta-large-openai-detector' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'roberta-large-openai-detector' is the correct path to a directory containing a file named one of tf_model.h5, pytorch_model.bin.


```

I'm pretty sure this is a valid Huggingface model, and it's actually downloaded, because I can run the following without any problems:
```

from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("roberta-base-openai-detector")

model = AutoModelForSequenceClassification.from_pretrained("roberta-base-openai-detector")

```

Is there a way to sidestep this? For example use `AutoModelForSequenceClassification` somewhere in ktrain model wrapper?

**Comment by amaiya** [comment]
Thanks for letting me know about this.  This will be fixed soon and released as an update to *ktrain*.   I will reply to this thread when it is available.

**Comment by amaiya** [comment]
This now works if you upgrade to `v0.20.2`.  Note that this model  appears to be configured/fine-tuned to only output two classes: real vs fake.
