### ISSUE TITLE
Translational method deprecated in transformers 3.1.0

### ISSUE THREAD

**Issue by xirect** [amaiya/ktrain#240]
Hi @amaiya,

I just wanted to notify you that with the new transformers update batch prepare has changed.

This is now the format
`self.model.generate(**self.tokenizer.prepare_seq2seq_batch(sentences).to(self.torch_device))`

This is what is in place
`self.model.generate(**self.tokenizer.prepare_translation_batch(sentences).to(self.torch_device))`

This should also speed up the translation a little bit.

**Comment by amaiya** [comment]
Thanks a lot, @xirect.  An update will be pushed and released soon.

**Comment by amaiya** [comment]
Thank you - this is fixed in `ktrain>=0.21.0`.
