### ISSUE TITLE
Saving models as SavedModel format

### ISSUE THREAD

**Issue by taylorshin** [amaiya/ktrain#241]
Hello,

I've noticed that the `learner.save_model` function saves models as a `h5` file (weights). Would it be possible to add support for saving models in SavedModel format? I'm trying to convert my TensorFlow model to TensorFlow Lite but I'm having trouble doing that with a `h5` weight file.

Thanks

**Comment by amaiya** [comment]
Hi!  Could you please let me know which model you are attempting to convert to TensorFlow Lite?  Is it a `transformers` model?

**Comment by taylorshin** [comment]
Yes, I fine-tuned `distilbert-base-uncased` on SST-2 and I'm trying to convert the resulting model to TFLite.

**Comment by taylorshin** [comment]
So I set/defined the model architecture and then loaded it with the weights of the fine-tuned model (the `h5` file) with the following block of code:
```
t = text.Transformer(model_name, maxlen=128, class_names=['0', '1'], batch_size=64)
train_data = t.preprocess_train(x_train, y_train)
model = t.get_classifier()
model.load_weights(in_file)
```
Is this the correct way to define the model architecture in `ktrain`? I assume it works because `ktrain` is a wrapper around `keras`. Also, I tried leaving out the preprocessing step but `ktrain` wouldn't let me so I left it there. Is there a way to define the model without the `preprocess_train` function call?

Once I set the model architecture and convert it to TFLite, using the `tf.lite.TFLiteConverter.from_keras_model` function, I get two sets of lengthy errors:

1. ```loc(callsite("tf_distil_bert_for_sequence_classification/distilbert/transformer/layer_._0/ffn/activation_10/Erf"("/Users/embodied/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py":742:0) at callsite("/Users/embodied/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py":3295:0 at callsite("/Users/embodied/anaconda3/envs/tf2/lib/python3.8/site-packages/transformers/modeling_tf_distilbert.py":70:0 at callsite("/Users/embodied/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py":427:0 at callsite("/Users/embodied/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py":985:0 at callsite("/Users/embodied/anaconda3/envs/tf2/lib/python3.8/site-packages/transformers/modeling_tf_distilbert.py":297:0 at callsite("/Users/embodied/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py":302:0 at callsite("/Users/embodied/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py":985:0 at callsite("/Users/embodied/anaconda3/envs/tf2/lib/python3.8/site-packages/transformers/modeling_tf_distilbert.py":347:0 at "/Users/embodied/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py":302:0)))))))))): error: 'tf.Erf' op is neither a custom op nor a flex op```

2. Not sure if these are error or debug messages but a tsunami of alphanumeric symbols (ex: `6F27AEBC6DF017BD4681B8BDBEB6D1BCB4B523BD0B3523BDF44810BDE34E57BD`) are outputted to the terminal.

Although there's nothing explicitly indicating failure, I assume the TFLite conversion failed because no `.tflite` file is generated.

**Comment by amaiya** [comment]
In the case of **transformers** models, `learner.save_model` simply calls `learner.model.save_pretrained` which produces the .h5 file (i.e., this is being done by `transformers` library not *ktrain*).  Note that the underlying models in *ktrain* are always directly accessible (e.g., `learner.model`, `predictor.model`) after fine-tuning.  Note also that the reason `preprocess_train` needs to be called is because the dataset is used to configure the model.  You can load a model directly with `transformers` and configure it yourself if you like.

I don't think the .h5 format is the cause of your problems, though.

If you need to convert a `transformers` model to TFLite, I would follow [this guide](https://github.com/huggingface/tflite-android-transformers).
