### ISSUE TITLE
Sentence Pair Classification with Extra Features

### ISSUE THREAD

**Issue by vishalmodagekar** [amaiya/ktrain#252]
Want to use bert-base-uncased or bert-base-cased transformer model for sentence pair classification (https://github.com/amaiya/ktrain/blob/master/examples/text/MRPC-BERT.ipynb) with extra features (categorical or numerical) as used in this [tutorial](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A4-customdata-text_regression_with_extra_regressors.ipynb)

I got the following error message:
AttributeError: Layer tf_bert_for_sequence_classification_2 has no inbound nodes.

Please provide a code snippet demonstrating how to combine the sentence pair model input and output with other models inputs and outputs for building and training a custom model.

**Comment by amaiya** [comment]
This is more of a `transformers`-related issue than a `ktrain` issue, but I will try to answer anyways.  

For `transformers` models, running `model.output` does not work (where `model` is a `TFBertForSequenceClassification` model, which is what is returned by *ktrain*).  This is why you're getting the error.   Instead, you should create a `BertModel` yourself and combine/concatenate the output with extra features of your choosing.  Most other steps in the tutorials will be exactly the same.

See [this Kaggle post](https://www.kaggle.com/c/google-quest-challenge/discussion/129978) for how to create a single model out of two separate `transformers` models, which includes some code snippets.  The process will be similar to creating a single model that combines the output of a single  `transformers` model with extra features.
