### ISSUE TITLE
ValueError: model must be of instance Model

### ISSUE THREAD

**Issue by FatimaMoqran** [amaiya/ktrain#258]
hello !
I try to deploy my model using ktrain with docker . I have this error 
`Call to keras.models.load_model failed.  Try using the learner.model.save_weights and learner.model.load_weights instead.
Error was: SavedModel file does not exist at: model_corps_mail_bert/{saved_model.pbtxt|saved_model.pb}`

my requirements : 
transformers ==  3.1
tensorflow == 2.1.0
ktrain == 0.21.4
Flask == 1.1.1

the code : 
`import` ktrain
from flask import Flask, request,jsonify
import json

app = Flask(__name__)
predictor = None

#we load our trained ktrainmodel
def load_predictor():
    global predictor
    predictor = `ktrain.load_predictor("model_corps_mail_bert")
   return predictor `

it was working on google collab and on local with ktrain 0.19.6 but I could not installed this version on my docker....
thank you for your help :-)

**Comment by amaiya** [comment]
Everything works on v0.21.4 for me.  Are you able to reproduce this problem on Google Colab with the latest version of **ktrain**?  If so, I can take a look.   Regardless, you might also consider sharing more of the code you used to train and save the model in one way or another to better provide assistance.

**Comment by FatimaMoqran** [comment]
hello !
Thank you for your response ! It was a problem with my model not with the new version of ktrain.
the problem is resolved thank you!
