### ISSUE TITLE
Is there a use case for using imblearn Smote with ktrain

### ISSUE THREAD

**Issue by MinuteswithMetrics** [amaiya/ktrain#260]
I was able to find one example of using `randomoversampling` and `randomundersampling` with ktrain transformers. However, I was not able to find or successfully use SMOTE with Ktrain. Will there be an example published in the near future?

**Comment by amaiya** [comment]
You can follow the SMOTE documentation directly and take the arrays representing your training data and feed it to SMOTE.  How to obtain the arrays will depend on the model you're trying to use.  With a vanilla text classification `tf.keras` model like `nbsvm` or `logreg`, you just do something like this (where `x_train` and `y_train` are the output of the `texts_from*` function:

```python
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=42)
x_train_smote, y_train_smote = sm.fit_sample(x_train, y_train)
```

For `transformers` models, you'll have to access the individual arrays stored within the returned `TransformerSequence` object and do the same thing.
