### ISSUE TITLE
Word embeddings

### ISSUE THREAD

**Issue by nn09** [amaiya/ktrain#261]
With ktrain, can we set "output_hidden_states=True" and access the word embeddings?

Thank you!

**Comment by amaiya** [comment]
Please see [this FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-obtain-the-word-or-sentence-embeddings-after-fine-tuning-a-transformer-based-text-classifier) for an example. Thanks.
