### ISSUE TITLE
When to use ktrain over spacy?

### ISSUE THREAD

**Issue by jboarman** [amaiya/ktrain#263]
For NLP projects, what are some of the scenarios where one would use ktrain in favor of spacy, and vice versa?  I realize that ktrain is more general purpose and not limited to NLP, but within the space of NLP, what are the advantages of ktrain over spacy?

**Comment by amaiya** [comment]
This would depend on what you're trying to do.  Even within the realm of NLP, the set of capabilities are not identical., and the projects have different goals. 

Spacy is a top-quality project that has many great features that **ktrain** doesn't support (e.g., [rule-based matching](https://spacy.io/usage/rule-based-matching), [dependency parsing](https://spacy.io/usage/linguistic-features#dependency-parse),  [out-of-the-box Part-of-Speech tagging](https://spacy.io/usage/linguistic-features#pos-tagging), lemmatizers, [entity linking](https://spacy.io/usage/linguistic-features#entity-linking), etc.).   Similarly, **ktrain** has some features that spacy currently doesn't support (e.g., wider and more versatile range of text classification models, Question-Answering, language translation, easy-to-use search engine, ZSL, more automated preprocessing, etc.).  For features that are the same or similar between the two, it could be a matter of preference or performance.   For instance, **ktrain** tries to expose a simple, unified, low-code interface to lots of different ML tasks that some people like, while others may prefer the spacy's elegant API and its support for aforementioned NLP tasks.
