### ISSUE TITLE
ValueError: Please call lr_find first.

### ISSUE THREAD

**Issue by nick-msca** [amaiya/ktrain#265]
After updating ktrain I get "ValueError: Please call lr_find first.".  

![image](https://user-images.githubusercontent.com/56486956/95817805-04f45700-0ce8-11eb-8779-1b04a934974a.png)

**Comment by amaiya** [comment]
As noted in the  [installation instructions](https://github.com/amaiya/ktrain#installation), there is a bug in TensorFlow 2.2 and TensorFlow 2.3 that causes the learning-rate-finder to keep running even after loss has diverged.  Google has fixed this in TensorFlow 2.4.   But, this means that, in TF 2.3.1 (current version of TF), you should use `max_epochs` argument with `lr_find`.  

In the latest version of **ktrain**, if running `lr_find` without the `max_epochs` argument, the `lr_find`  method prints a `warning` about this and  outputs nothing.   

Have you suppressed warnings from **ktrain** to cause the warning to not appear?

The warning should probably be changed to a raised exception to avoid this, and I will change this.

**Comment by nick-msca** [comment]
Thanks Arun, I indeed suppressed warnings, therefore didn't see the message.  Changing this to exception would've been better for me.  

I am now re-running with learner.lr_find(max_epochs=1024), but the behavior is still not the same (while using the same exact data).


With ktrain '0.3.1' I would get a lr_find convergence after just a few epochs:
simulating training for different learning rates... this may take a few moments...

Epoch 1/1024
6710/6710 [==============================] - 83s 12ms/step - loss: 0.6805 - acc: 0.5580
Epoch 2/1024
6710/6710 [==============================] - 77s 11ms/step - loss: 0.6774 - acc: 0.5578
Epoch 3/1024
6710/6710 [==============================] - 77s 11ms/step - loss: 0.6547 - acc: 0.6300
Epoch 4/1024
6710/6710 [==============================] - 74s 11ms/step - loss: 0.3294 - acc: 0.9411
Epoch 5/1024
6710/6710 [==============================] - 72s 11ms/step - loss: 0.0151 - acc: 0.9978
Epoch 6/1024
6656/6710 [============================>.] - ETA: 0s - loss: 0.0124 - acc: 0.9982
done.


Now running ktrain '0.21.4' - I can't get this to converge even after 100+ epochs.  Is there a way for me to get this to work as in the older version?

learner.lr_find(max_epochs=1024)

simulating training for different learning rates... this may take a few moments...
Epoch 1/1024
210/210 [==============================] - 22s 106ms/step - loss: 0.6845 - accuracy: 0.5495
*******
Epoch 116/1024
210/210 [==============================] - 22s 107ms/step - loss: 0.6641 - accuracy: 0.5952
Epoch 117/1024
210/210 [==============================] - 22s 106ms/step - loss: 0.6641 - accuracy: 0.6043
Epoch 118/1024
210/210 [==============================] - 23s 108ms/step - loss: 0.6637 - accuracy: 0.6049
Epoch 119/1024
148/210 [====================>.........] - ETA: 6s - loss: 0.6642 - accuracy: 0.6096

**Comment by amaiya** [comment]
As mentioned in my original answer, this is a [bug in TensorFlow 2.2 and 2.3](https://github.com/tensorflow/tensorflow/issues/41174#issuecomment-656330268), which causes the learning rate finder to run for as many as epochs you specify and ignore the divergence condition.  Since, you specified 1024 epochs, it'll take forever to run .  If you use the `max_epochs` argument, you should set it to something smaller like 5 epochs in your case. 

This issue will be fixed by Google in TenorFlow 2.4, but TF 2.4 has not been released yet.  **If you want it to work like before, you can temporarily downgrade TensorFlow to 2.1.0 until TensorFlow 2.4 is released.**  

Once TensorFlow 2.4 is released,  `lr_find` will stop at the appropriate moment again.

**Comment by nick-msca** [comment]
Thanks Arun.  I will use it with a small number of epochs

**Comment by amaiya** [comment]
This will be changed to a raised Exception in the next release.
