### ISSUE TITLE
ValueError: model must be of instance Model when trying to load Bert Model

### ISSUE THREAD

**Issue by Stamtiniakos** [amaiya/ktrain#266]
I have trained an NLP model using GPU on Azure Databricks.  When I try to load it on Azure it works fine but when I try to load it on my laptop I get a ValueError: model must be of instance Model.

I have tried to add `os.environ["CUDA_VISIBLE_DEVICES"]= "-1" `  at the top of my script as suggested on some other posts but I get the same error.

Any help will be much appreciated

**Comment by amaiya** [comment]
@Stamtiniakos This may be some sort of odd problem with TensorFlow or other dependencies. Other users that have reported this issue said that uninstalling and reinstalling everything from scratch solved the problem.  If you're experiencing this problem on your local computer, uninstall  **ktrain** and all its dependencies including TensorFlow and then reinstall everything from scratch.  Or, alternatively, create a new virtual environment and install everything from scratch:

```
python3 -m venv new_ktrain_venv
cd new_ktrain_venv
source bin/activate
pip install tensorflow
pip install ktrain
```
After that, try to load the predictor again:
```python
import ktrain
predictor = ktrain.load_predictor('bert_model')
```


If this is happening on Google Colab and you're loading predictor from your Google Drive, try running `load_predictor` again if you receive an error the first time (as this might be a bug with Colab/Drive).

**Comment by Stamtiniakos** [comment]
> @Stamtiniakos This may be some sort of odd problem with TensorFlow or other dependencies. Other users that have reported this issue said that simply uninstalling and reinstalling everything from scratch solved the problem. If you're experiencing this problem on your local computer, uninstall **ktrain** and all its dependencies including TensorFlow and then reinstall everything from scratch. Or, alternatively, create a new virtual environment and install everything from scratch:
> 
> ```
> python3 -m venv new_ktrain_venv
> cd new_ktrain_venv
> source bin/activate
> pip install tensorflow
> pip install ktrain
> ```
> 
> After that, try to load the predictor again:
> 
> ```python
> import ktrain
> predictor = ktrain.load_predictor('bert_model')
> ```
> 
> If this is happening on Google Colab and you're loading predictor from your Google Drive, try running `load_predictor` again if you receive an error the first time (as this might be a bug with TF/Colab/Drive).

@amaiya that worked, thanks a lot
