### ISSUE TITLE
Pruning or Quantization

### ISSUE THREAD

**Issue by Stamtiniakos** [amaiya/ktrain#268]
Can Pruning or Quantization used on a ktrain Bert or DistilBert model to make the models smaller and their inference faster? 
Pruning or Quantization seems to be an option on TensorFlow but I have not seen an example so far on how to use these techniques on ktrain.

**Comment by amaiya** [comment]
**ktrain** is just a thin wrapper around TensorFlow (and other libraries like `transformers`, etc.), so you can take the model (e.g., `learner.model` or `predictor.model`) and prune, quantize, convert to PyTorch, save/load it independently of **ktrain**, or anything else.  

The way it is done depends on which model you're using.  For instance creating a model with `text_classifier('distilbert'...`  or `Transformer(...` uses **transformers** library, but `text_classifier('bert',...` currently creates the model using the `keras_bert` package.  In the former case, you should refer to the the Hugging Face transformers documentation or discussion forums for how to quantize/prune.
