### ISSUE TITLE
ktrain and related package versions (on kaggle notebooks)

### ISSUE THREAD

**Issue by Alex-Lekov** [amaiya/ktrain#269]
I made a notebook for my students in which I show how easy it is to solve complex problems using your library. Alas, after some update the notebook became unplayable.
[https://www.kaggle.com/itslek/fine-tuning-bert-ktrain-sf-nlp-movie-genre-v2-0](https://www.kaggle.com/itslek/fine-tuning-bert-ktrain-sf-nlp-movie-genre-v2-0)

 Writes an error related to package versions. please check the package version relationship in your pip setup.py.

Thanks for your work. Your package is amazing!

**Comment by amaiya** [comment]
@Alex-Lekov Thanks for your comments.  Can you please provide the exact error messages you're receiving on Kaggle?

The current `setup.py` appears to be correct, as everything works on Google Colab (and locally on both Linux and Windows).  I'm not that familiar with Kaggle kernels, but, with a quick test, I've verified the latest version of **ktrain** works  on Kaggle, as well.

I did notice that, on Kaggle, I needed to manually ensure **transformers** is up-to-date (despite the fact that the current `setup.py` already specifies a minimum version of **transformers** that is greater than the default on Kaggle). 

Note also that the latest version of **ktrain**  assumes that TensorFlow 2 is already installed.
