### ISSUE TITLE
Unable to find downloaded files when running code in a docker container

### ISSUE THREAD

**Issue by premthomas** [amaiya/ktrain#271]
Hello,

I need some help with running a program using ktrain inside a docker container. I will be running shutting the container down and would like to keep the downloaded models so that on running a new / restarting the container, the models do not download again. 

I tried searching for the "torch" folder using bash. But was not able to find the folder where the models have been downloaded to. Can you please help me with this?

Thanks

**Comment by amaiya** [comment]
The files are being downloaded by `transformers`, not **ktrain**.  It should be in:
```
<home_directory>/.cache/torch/transformers
```
