### ISSUE TITLE
Re-create learner from saved predictor model files

### ISSUE THREAD

**Issue by YLi999** [amaiya/ktrain#274]
Version: ktrain 0.25.0, Platform: Google colab with GPU, Task: fine-tuning 'bert-base-multilingual-cased'.

Description:
I have fine-tuned a bert model and save it by `predictor.save`. (contains 3 files: .json, .h5, .preproc). I used the following code you suggested in another post to re-create the learner and continue training.

```
predictor = ktrain.load_predictor('/content/drive/My Drive/BERT_multilingual')
learner = ktrain.get_learner(predictor.model, train_data = (x_train, y_train), val_data=(x_val, y_val), batch_size = 16)
```

where `x_train` is a list of tuples of the form (str, str) for sentence pair classification, and `y_train` is a numpy array. 

However, it gave the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-7af88b85ff15> in <module>()
      1 predictor = ktrain.load_predictor('/content/drive/My Drive/BERT_multilingual')
----> 2 learner = ktrain.get_learner(predictor.model, train_data = (x_train, y_train), val_data=(x_val, y_val), batch_size = 16)

1 frames
/usr/local/lib/python3.6/dist-packages/ktrain/utils.py in data_arg_check(train_data, val_data, train_required, val_required, ndarray_only)
    341             err_msg = 'data must be tuple of numpy.ndarrays'
    342             if not ndarray_only: err_msg += ' or an instance of ktrain.Dataset'
--> 343             raise ValueError(err_msg)
    344     if val_data is not None and not is_iter(val_data, ndarray_only):
    345         if bad_data_tuple(val_data):

ValueError: data must be tuple of numpy.ndarrays or an instance of ktrain.Dataset
```

I do not understand this error. I thought the saved model had a preprocessor. Then I tried to create a new preprocessor and run the following code:

```
MODEL_NAME = 'bert-base-multilingual-cased'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=[0,1,2,3])
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_val, y_val)
predictor = ktrain.load_predictor('/content/drive/My Drive/BERT_multilingual')
learner = ktrain.get_learner(predictor.model, train_data = trn, val_data=val, batch_size = 16)

```
Then it could work. 

My questions are: 1) Is it the correct way to continue training? 2) Does it mean the learner is using the preprocessor that I newly create, instead of the saved one?

Thanks so much!

**Comment by amaiya** [comment]
Hello,

When you run `predictor = load_predictor`, the model is accessible as `predictor.model` and the `Preprocessor` is accessible  as `predictor.preproc` (where the `Preprocessor` is the original output of `t = text.Transofrmer`.  

There is no need to re-create a new `Preprocessor` instance.  The error you're getting is because you were supplying the **raw** data to `get_learner` instead of the preprocessed data.  So, please try this:

```python
predictor = ktrain.load_predictor('/content/drive/My Drive/BERT_multilingual')
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_val, y_val)
learner = ktrain.get_learner(predictor.model, train_data = trn, val_data=val, batch_size = 16)
```

After the above, you should be able to resume training with `learner.fit_onecycle` (or whatever training method you used).  Then, you can re-create and re-save the new predictor using the original `Preprocessor`:
```python
updated_predictor = ktrain.get_predictor(learner.model, predictor.preproc)
updated_predictor.save('/tmp/my_updated_predictor')
```

Re-saving the original `Predictor` instance after updating the `model` will also probably work:
```python
predictor.model = learner.model
predictor.save('/tmp/my_updated_predictor')
```

**Comment by YLi999** [comment]
Thanks so much for the quick reply! It works :)
