### ISSUE TITLE
Query on use case

### ISSUE THREAD

**Issue by Chokerino** [amaiya/ktrain#275]
Hello,

Suppose i wanted to use bert on data which belongs to a different language. For this, training data with this library would be correct or do i need to train my own custom bert using the hugging face library.

**Comment by amaiya** [comment]
You haven't specified the language.  But, you can most likely use **ktrain** for this.  

There are two different text classification APIs in **ktrain**.  The first is the `text_classifier` API shown in [this example](https://github.com/amaiya/ktrain/blob/master/examples/text/20newsgroups-BERT.ipynb).  By default, the `text_classifier` API will detect the language and use either the English model for English, the Chinese model for Chinese, or the  **multilingual** model if the language is something else.  The multilingual model supports over 100 languages [shown here](https://github.com/google-research/bert/blob/master/multilingual.md). 

The `Transformer` API is the second text classification API, which provides more control over which Hugging Face model used.  For instance, if the language is Arabic, you can use the `AraBERT` model as shown in [this example](https://github.com/amaiya/ktrain/blob/master/examples/text/ArabicHotelReviews-AraBERT.ipynb), which may potentially provide slightly better results than the  `multilingual` BERT model.  To find a pretrained model for your language, you can look [here](https://huggingface.co/models).

If you cannot find a model for your language and it is not supported by the multilingual model, you can pretrain/fine-tune your own BERT language model for your language using this [Hugging Face script](https://github.com/huggingface/transformers/tree/master/examples/language-modeling) or use a non-pretrained model like NBSVM.
