### ISSUE TITLE
learner: support for steps_per_epoch

### ISSUE THREAD

**Issue by mattivi** [amaiya/ktrain#276]
Will steps_per_epoch be added in learner.fit() in next releases? It would be valuable and helpful, especially with big datasets.
Thanks.

**Comment by amaiya** [comment]
Hello:  **ktrain** currently sets this automatically as you probably saw.  You mentioned it would be useful for big datasets.  Would you mind elaborating on your specific use case for setting the `steps_per_epoch` to a different value?

**Comment by amaiya** [comment]
> Will steps_per_epoch be added in learner.fit() in next releases?

Yes, it can be added as an user-adjustable parameter.

**Comment by mattivi** [comment]
I have a pre-trained transformer model and a very big dataset for the downstream classification task. 
The approach I am using for the downstream task is as in your notebook example: https://github.com/amaiya/ktrain/blob/master/tutorials/tutorial-A3-hugging_face_transformers.ipynb 

However, in my case the model is already overfitting after 2 epochs. One approach could be to downsample the original dataset, but I might lose some important training data.
The idea is to be able to use only a portion of the original training dataset, e.g. 25%. So the original dataset can be processed in 4 epochs and I would be able to find the best epoch for the downstream task, which could be e.g. 6 epochs (or original approach would be 1.5 epochs)

**Comment by amaiya** [comment]
Thanks a lot, @mattivi .  Will look into adding support for this in future release.

**Comment by mattivi** [comment]
Thanks a lot!

**Comment by raqueeb** [comment]
I have the similar issue. I wanted saving the training in steps, maybe 50% of 1 epoch. I can't stay connected for this long like 12 hours. Colab crashes sometime.

Thank you.

**Comment by amaiya** [comment]
@mattivi  and @raqueeb 

A `steps_per_epoch` argument has been added to `*fit*` methods.  It is available in the `develop` branch but is not tested.

If you want to try it out, you can install the `develop` branch with:
```python
pip install git+https://github.com/amaiya/ktrain@develop
```

**Comment by raqueeb** [comment]
Thank you.
