### ISSUE TITLE
NameError: name 'pre_incpeption' is not defined

### ISSUE THREAD

**Issue by kangPrayit** [amaiya/ktrain#279]
I already save the model into the folder and it gives me 2 files: (1) tf_model.h5 and (2) tf_model.preproc
but when I tried to load the predictor it gives me an error NameError: name 'pre_incpeption' is not defined.
Please help.
thank you.

![image](https://user-images.githubusercontent.com/6687727/100190592-8ff08000-2f29-11eb-8c40-69b8d393ecc3.png)

**Comment by amaiya** [comment]
Thanks for letting me know about this.  This is a bug/typo.  It has just been fixed in the `develop` branch (but not tested yet) and will be included in the next release.

If you'd like to try out the fix now, you can install the `develop` version of **ktrain** with:
``` 
pip install git+https://github.com/amaiya/ktrain@develop
```

**Comment by kangPrayit** [comment]
Thank You,
Its working now.
