### ISSUE TITLE
Distilbert with text regression task

### ISSUE THREAD

**Issue by Mokers1234** [amaiya/ktrain#282]
Hi,

Following the tutorial for text regression here:

https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/examples/text/text_regression_example.ipynb

My code:
```
trn,val,preproc = text.texts_from_array(x_train=self.train[self.comment_type].tolist(),y_train=self.train[self.label_method].tolist(), x_test=self.val[self.comment_type].tolist(), y_test=self.val[self.label_method].tolist(),maxlen=128)
model = text.text_regression_model('distilbert', train_data=trn, preproc=preproc)
```

..fails with:

```
  File "c:/Users/Mark/Documents/NLP_comments2/nlp1c.py", line 205, in get_vectorizer
    model = text.text_regression_model(self.ktrain_model, train_data=trn, preproc=preproc)
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python36\lib\site-packages\ktrain\text\models.py", line 502, in text_regression_model
    multilabel=False, classification=False, metrics=metrics, verbose=verbose)
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python36\lib\site-packages\ktrain\text\models.py", line 105, in _text_model
    raise ValueError('you are using a Hugging Face transformer model but did not preprocess as such (or vice versa)')
ValueError: you are using a Hugging Face transformer model but did not preprocess as such (or vice versa)
```

Any ideas please?

**Comment by amaiya** [comment]
Hello,

As indicated in the error message, you must specify `preprocess_mode='distilbert'` in the call to `texts_from_array` if using a `distilbert` model.  This is explained in detail in the [text classification tutorial](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-04-text-classification.ipynb).

Also, if using a **transformers** model, you can also use the `Transformer` API to train a DistilBert text regression model, which is demonstrated at the end of the [example notebook](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/examples/text/text_regression_example.ipynb) that you are following:

```python
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=75)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_regression_model()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=128)
learner.fit_onecycle(5e-5,  1)
```

**Comment by Mokers1234** [comment]
Thanks for the prompt response. That worked.

However, all of the predictions yielded are near-identical when the training data label range is -100 to 100. This is not the case when I use "linreg" instead of distilbert.

Also revealing is that when I run learner.lr_find() and learner.lr_plot() the graph shows a vertical line at 10^-8, which explains the bad performance.

```
trn,val,preproc = text.texts_from_array(x_train=self.train[self.comment_type].tolist(),y_train=self.train[self.label_method].tolist(), 
      x_test=self.val[self.comment_type].tolist(), 
      y_test=self.val[self.label_method].tolist(),maxlen=128,preprocess_mode=self.ktrain_model)
model = text.text_regression_model(self.ktrain_model, train_data=trn, preproc=preproc)
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=4)
learner.lr_find(max_epochs=1)
learner.lr_plot()
```
Where train is 40k text comments and continuous numeric labels, and val is 10k equivalent.

Might I be missing a bert-specific preprocessing step somewhere? Thanks

**Comment by amaiya** [comment]
As shown in the example notebooks, a `distilbert` model works with the wine price prediction dataset, and all tests pass. Can you post your dataset somewhere, so I can take a look?

**Comment by Mokers1234** [comment]
I'm testing the distilbert implementation according to https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/examples/text/text_regression_example.ipynb

When I run the above notebook as-is, and append to the end of the notebook after fit_oncycle:

```
predictor = ktrain.get_predictor(learner.model, preproc)
idx = np.random.randint(len(x_test))
print('Description: %s' % (x_test[idx]))
print('Actual Price: %s' % (y_test[idx]))
print(predictor.predict(x_test[idx]))
```

it yields the following error:

```
Description: Nice, rugged mountain Zin, with the briary, brambly tannins and peppery taste of wild berries freshly picked off the vine. Alcohol adds heat and structure, and time in the barrel has softened the tannins. This might just be the perfect backyard barbecue red wine.
Actual Price: 16.0
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-32-89091d16d7f8> in <module>()
      3 print('Description: %s' % (x_test[idx]))
      4 print('Actual Price: %s' % (y_test[idx]))
----> 5 print(predictor.predict(x_test[idx]))
      6 

/usr/local/lib/python3.6/dist-packages/ktrain/text/predictor.py in predict(self, texts, return_proba)
     49         if U.is_huggingface(model=self.model):
     50             tseq = self.preproc.preprocess_test(texts, verbose=0)
---> 51             tseq.batch_size = self.batch_size
     52             texts = tseq.to_tfdataset(train=False)
     53             preds = self.model.predict(texts)

AttributeError: 'tuple' object has no attribute 'batch_size'
```

**Comment by Mokers1234** [comment]
I have successfully run distilbert regression on the wine dataset, so it must be a leak in my code or data. I'll analyse and report back.
