### ISSUE TITLE
This package needs an API Documentation 🙂

### ISSUE THREAD

**Issue by amm98d** [amaiya/ktrain#287]

**Comment by amaiya** [comment]
Hello -  The tutorial/example notebooks and FAQ are currently serving as "documentation".  as most everything is documented there.   That said, I agree that it would be a good idea to generate API documentation from docstrings.  If you'd like to contribute, please open a PR.

**Comment by ilos-vigil** [comment]
`pdoc3` (https://pdoc3.github.io/pdoc/) can generate documentation from docstring. I've tried it on `ktrain` and the result is quite satisfying.
Last time i generate one, there's one or two minor error though.

**Comment by amaiya** [comment]
Thanks a lot, @ilos-vigil.  I'll check it out (and resolve those errors).

**Comment by amm98d** [comment]
> Hello - The tutorial/example notebooks and FAQ are currently serving as "documentation", as most everything is documented there. That said, I agree that it would be a good idea to generate API documentation from docstrings. If you'd like to contribute, please consider opening a PR.
> 
> I have labeled this issue as _Enhancement_ as a note for us to add API documentation - thank you.

Hi @amaiya, apologies for the late response. I'll open a PR and work on this.

**Comment by amm98d** [comment]
@amaiya, please consider creating a webhook and publishing the API on Read the Docs for free. For more info, check out this video: https://youtu.be/oJsUvBQyHBs. 

Please let me know if this sounds good and I'll create a pull request adding the Sphinx Docs.

**Comment by amaiya** [comment]
Thanks @amm98d! This sounds good to me.

**Comment by amaiya** [comment]
I followed @ilos-vigil  suggestion and used `pdoc3` to create API documentation.  There is now an [API Docs](https://amaiya.github.io/ktrain/index.html) link in the README.
