### ISSUE TITLE
class_names argument was ignored, as they were extracted from string labels in dataset: Is Multi-Label? False

### ISSUE THREAD

**Issue by raqueeb** [amaiya/ktrain#292]
Hi, 

This one is a life saver to use transformers for Bangla language. I had been using a multi-class model as you covered in "Tutorial A3: Text Classification with Hugging Face Transformers", it seems that - it is providing a warning; 

`UserWarning: class_names argument was ignored, as they were extracted from string labels in dataset
if self.get_classes(): warnings.warn('class_names argument was ignored, as they were extracted from string labels in dataset')

Is Multi-Label? False`

What might be the reason for it?

[My notebook is here](https://github.com/raqueeb/nlp_bangla/blob/master/Chap_7_transformers_bert_Bangla.ipynb).

Thank you.

**Comment by amaiya** [comment]
Hello,

It's meant to be informative and is not an error.  It just means the labels (ie.., 'life-style', 'technology',, etc.) already appear within the dataset itself, so `class_names` argument is not needed and ignored.  If your dataset was labeled with integers representing each category (or was one-hot-encoded), then only is the `class_names` argument needed to inform **ktrain** how integers map to class names.

**Comment by raqueeb** [comment]
Dear Amaiya,

Many thanks indeed. You have showed how to save and resume the model.

Since I'm using Colab and it flashes after 12 hours, if I interrupt and want to reload, will this work?

`MODEL_NAME = 'sagorsarker/bangla-bert-base'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names = categories)
trn = t.preprocess_train(X_train, y_train)
val = t.preprocess_test(X_test, y_test)
model = t.get_classifier()

# save model and Preprocessor instance after partially training
ktrain.get_predictor(model, preproc).save('/tmp/my_predictor')

# reload Predictor and extract model
model = ktrain.load_predictor('/tmp/my_predictor').model

# re-instantiate Learner and continue training
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)

learner.fit_onecycle(8e-5, 2)`

Thank you.
