### ISSUE TITLE
User question: ktrain without an internet connection, can't fine the folder, and resuming training

### ISSUE THREAD

**Issue by raqueeb** [amaiya/ktrain#294]
Hello Arun,

You have a very good documentation. I have 2 issues. I wanted to finish the training for such large dataset. Sometimes in Colab (I have already consumed 4 days of GPU in Colab) and home PC with 4 gb GPU - [My notebook](https://github.com/raqueeb/nlp_bangla/blob/master/Chap_7_transformers_bert_Bangla.ipynb)  . It's difficult but I want to finish it.

1. While I downloaded all files, tf_model.h5, config.json and vocab.txt and kept in 'Download/model', it still tries to get to huggingface jason file link or the local folder, **cant find it.** I'm on Windows 10, Anaconda and 

import ktrain
from ktrain import text
t = text.Transformer('Download/model', maxlen=500)

and,

2. While I was resuming the training from an interrupted (ctrl+c) and clicking on Colab, save and downloaded 3 files to resume it 

model = ktrain.load_predictor('Download/model').model

While I re-instantiate Learner and continue training

learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=2)

It asks me trn and val, and then I have to go back to start other items, and takes time once again

MODEL_NAME = 'sagorsarker/bangla-bert-base'
t = text.Transformer(MODEL_NAME, maxlen=500)

and this, takes 60 mins,

trn = t.preprocess_train(X_train, y_train)
val = t.preprocess_test(X_test, y_test)

and 

model = t.get_classifier() takes more time.

I needed to train, but I fell back to do all these.

learner.fit_onecycle(2e-5, 1)

Somewhere in your doc, you mentioned, 

from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
dummy_texts = ['আমি এক', 'তুমি এক', 'সে এক']
dummy_labels = ['আমি', 'তুমি', 'সে']
t = text.Transformer(MODEL_NAME, maxlen=500)
trn = t.preprocess_train(dummy_texts, dummy_labels)

And this one gets longer, I wanted to run it from local folder.

model = t.get_classifier()

Does that mean, I can always start with dummy text and labels just to get the trn value?

Thank you.

**Comment by amaiya** [comment]
Hello,


This question was just answered in #295 .  Basically, when loading a local model using `Transformer` you need to ensure the tokenizer files (which are very small) are included in the folder or you need to manually set the tokenizer yourself before calling `preprocess_train`.

Also, here is [an FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-resume-training-from-a-saved-checkpoint) that explains how to resume training.  This assumes you can get through a complete epoch on Google Colab.  If not, you'll need to use the `steps_per_epoch` argument that you requested earlier.

Thanks.

**Comment by raqueeb** [comment]
Thank you. You mean to say, I need to have small tokenizer file like dummy files, right? What would be the extension of those files?

I'll create the tokenizer files like, 

dummy_texts = ['hello world', 'goodbye world', 'hi world']
dummy_labels = ['hello', 'bye', 'hello']

and then call them by

trn = t.preprocess_train(dummy_texts, dummy_labels)

Will it create any files?

I'll try these. Thank you.

Thank you once again.

**Comment by amaiya** [comment]
Hi:

No, by "tokenizer files" I'm referring to files like `vocab.txt` that are downloaded directly from Hugging Face when doing something like: `tokenizer = AutoTokenizer.from_pretrained('distilbert-base-uncased')`.   But, I just saw in your post that you seem to already have that file (missed that before).   I know that if you name the download folder with the model name in it, Hugging  Face tries and fails to download from internet.  So, maybe try giving a more vague name like `/tmp/mymodel/`, if that's what is going on.

Please also see [this FAQ](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-use-ktrain-without-an-internet-connection) along with information in the other post I referenced, which may help.

**Comment by raqueeb** [comment]
Thank you. I'll try that too.
