### ISSUE TITLE
download "uncased_L-12_H-768_A-12.zip" behind a firewall

### ISSUE THREAD

**Issue by Xiaoping777** [amaiya/ktrain#3]
hi here, I would like to try your package, however, I have to work behind a firewall, so I cannot run function "texts_from_folder" due to this reason. I have tried to download package, and then unzipped and put into the working folder, but still have this issue.

Could you please let me know where I should the fold or specific file?

**Comment by amaiya** [comment]
The extracted `uncased_L-12_H-768_A-12` folder should reside in a folder called `ktrain_data` within your home directory.  In other words, on a Linux system, the full path will be:

`/home/username/ktrain_data/uncased_L-12_H-768_A-12`

where `/home/username` should be replaced with whatever `os.path.expanduser('~')` returns on your system.
