### ISSUE TITLE
Multi label (multi-hot-encoded) in preprocess_train function

### ISSUE THREAD

**Issue by NoraAlt** [amaiya/ktrain#300]
Hello,

I had been using a Sentiment Analyzer With AraBERT as you covered in [here](https://github.com/amaiya/ktrain/blob/master/examples/text/ArabicHotelReviews-AraBERT.ipynb).

My dataset looks like: 
<img width="928" alt="Screen Shot 2020-12-20 at 8 08 24 PM" src="https://user-images.githubusercontent.com/31368075/102721951-fee5ac80-430e-11eb-8034-36d87431f82c.png">

So I need to do a Multi label classification.

First, the data split as:
`df = df[['text','Optimistic','Thankful','Empathetic','Pessimistic','Anxious','Sad','Annoyed','Denial','Official','Surprise','Joking']] 
`
`df_train = df.sample(frac=0.85, random_state=42)`
`df_test = df.drop(df_train.index)`

I added the class_names argument to Transformer constructor as follows:
`t = text.Transformer(MODEL_NAME, maxlen=128,class_names=['Optimistic','Thankful','Empathetic','Pessimistic','Anxious','Sad','Annoyed','Denial','Official','Surprise','Joking'])`

**But I could not get how to pass it in the preprocess_train \ preprocess_test functions? What I should pass for the Y in the following:**
`trn = t.preprocess_train(df_train.text.values, Y)`
`val = t.preprocess_test(df_test.text.values, Y)`

Would greatly appreciate your help!

**Comment by amaiya** [comment]
Try something like this:


```python
label_list = ['optimistic', 'thankful', ...]
y_train = df_train[label_list].values
```
