### ISSUE TITLE
'self.lr_mult = (end_lr / start_lr) ** (1 / num_batches) ZeroDivisionError: division by zero'

### ISSUE THREAD

**Issue by KouateMuhamed** [amaiya/ktrain#305]
Hi, 
I have this problem and I'd like to know how to fix it, please.

`File "/root/anaconda3/envs/mvtec/lib/python3.6/site-packages/ktrain/lroptimize/lrfinder.py", line 94, in find
self.lr_mult = (end_lr / start_lr) ** (1 / num_batches)
ZeroDivisionError: division by zero`

ktrain==0.25.3

**Comment by amaiya** [comment]
Hello:  I was not able to reproduce this using TensorFlow 2.3 and the latest version of  `ktrain==0.25.3`.

You'll need to provide more information such as the version of TensorFlow, what model you're trying to train, how did you preprocess your dataset, and what does your dataset look like.  Ideally, you should provide a reproducible example on Google Colab.
