### ISSUE TITLE
error while loading saved model

### ISSUE THREAD

**Issue by Liranbz** [amaiya/ktrain#306]
Hi,
I trained a model and saved it in the regular way:
```
predictor = ktrain.get_predictor(learner.model, preproc)
predictor.save('/my/local/folder')
```
Once I did it, I got the _tf_model.h5_ and _tf_model.preproc_ in my local folder.
while loading the saved model in this way:
`model = ktrain.load_predictor('/my/local/folder')`
I got this error:

> Exception: Error detected: SavedModel file does not exist at: my/local/folder//{saved_model.pbtxt|saved_model.pb}

I working on TF 2.4.0 and ktrain 25.2 and h5py 3.0.0

Thank you

**Comment by amaiya** [comment]
Hello,

I was not able to reproduce this problem with BERT (keras_bert) or DistilBERT(using `transformers`) with TensorFlow 2.4 and ktrain 0.25.3.  Please provide more information, so I can reproduce.   For instance, it's not clear on what model you're using.   A shared Google Colab notebook reproducing the problem would be helpful.   See also [this FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#why-am-i-getting-a-model-must-be-of-instance-model-error-with-load_predictor), which may help.  Thanks.
