### ISSUE TITLE
How to delete an index in QA 

### ISSUE THREAD

**Issue by pradeepdev-1995** [amaiya/ktrain#308]
While ktrain QA, I have initialised index as follows

from ktrain import text
INDEXDIR = '/tmp/myindex'
text.SimpleQA.initialize_index(INDEXDIR) 

So how can delete/remove the index through the text.SimpleQA module?

**Comment by amaiya** [comment]
Hi:  You can just type `rm -rf /tmp/myindex` (or `!rm -rf /tmp/myindex` if you're in a notebook environment).
