### ISSUE TITLE
Regarding Incremental/Continual Learning using Ktrain for DL/TL 

### ISSUE THREAD

**Issue by katreparitosh** [amaiya/ktrain#311]
Hello,

It is said that DL/TL models and architectures are _incremental_ or _continual_ in nature because they learn from the **mini-batches** concept of gradient descent. 

**My query was:**

What is the method within Ktrain where I can **continuously update** the model with _newer_ incoming data and train on top of what it has already learned?

**Example:** 

Model A is trained on 1000 samples and is in action. Later, I want to update the model (not from scratch) by training it with 500 more samples. And continue with this procedure of model updates.

It would be great if you could help me on this. 

Thanks.

**Comment by amaiya** [comment]
Hello:  See [this FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-resume-training-from-a-saved-checkpoint). Thanks.

**Comment by katreparitosh** [comment]
Sure,

Thanks.
