### ISSUE TITLE
loading checkpoints that are in .ckpt format

### ISSUE THREAD

**Issue by bclee232** [amaiya/ktrain#315]
Similar to [Issue #62](https://github.com/amaiya/ktrain/issues/62), where WangHexie's model directory containing model.ckpt.data-00000-of-00001, model.ckpt.index, model.ckpt.meta was not working (not Ktrain-specific issue), I was wondering if there was a way to use Ktrain for models with Tensorflow checkpoints. These checkpoints are in the format described on the [official website](https://www.tensorflow.org/tutorials/keras/save_and_load). I'm not entirely sure how to convert from Tensorflow to Keras - similar to [this issue on the main Keras GitHub](https://github.com/keras-team/keras/issues/5273).

**Comment by amaiya** [comment]
This should be supported by default in TF2.  For instance, the following works:

```python
from ktrain import text as txt
model = txt.text_classifier('nbsvm', train_data=trn, preproc=preproc)
model.save_weights('/tmp/saved_weights/checkpoint')
model.load_weights('/tmp//saved_weights/checkpoint')
```
```
$ ls /tmp/saved_weights
checkpoint  checkpoint.data-00000-of-00001  checkpoint.index
```
