### ISSUE TITLE
NER Predictor.predict() throws error, when argument 'return_proba' is set to True

### ISSUE THREAD

**Issue by anischihi** [amaiya/ktrain#316]
ktrain version: 0.25.3
python_version=3.7

Currently, it seems not possible to output the probability distribution for each token. 
Example:
`ner_predictor = ktrain.load_predictor("path/to/predictor")`
`ner_predictor.predict("Initially, the anti-malariua drugs hydroxychloroquine and cloroquine were thought to be potential treatments for COVID-19 and the FDA granted Emegency Use Authorization.")`

--> works

`ner_predictor.predict("Initially, the anti-malariua drugs hydroxychloroquine and cloroquine were thought to be potential treatments for COVID-19 and the FDA granted Emegency Use Authorization.",return_proba=True)`

returns:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-10-d76cb1a9245f> in <module>()
----> 1 reloaded_predictor.predict("Initially, the anti-malariua drugs hydroxychloroquine and cloroquine were thought to be potential treatments for COVID-19 and the FDA granted Emegency Use Authorization.",return_proba=True)

/usr/local/lib/python3.6/dist-packages/ktrain/text/ner/predictor.py in predict(self, sentence, return_proba, merge_tokens, custom_tokenizer)
     57         if return_proba:
     58             #probs = np.max(y_pred, axis=2)[0]
---> 59             y_pred = y_pred[0].numpy().tolist()
     60             return list(zip(nerseq.x[0], y_labels, y_pred))
     61         else:

AttributeError: 'numpy.ndarray' object has no attribute 'numpy'
```

**Comment by amaiya** [comment]
Thanks for reporting this issue.  This should now be fixed in `develop` branch and will be included in next release (0.25.4).  Thanks again.
