### ISSUE TITLE
Receiving ValueError: len(set(targets) is 1 but len(list(range(int(max(targets)+1))) is  2

### ISSUE THREAD

**Issue by katreparitosh** [amaiya/ktrain#317]
Hi @amaiya, 

I have created a function that loads the saved model, passes a new text, label, and updates the model in a continual learning fashion. It's a binary text classification problem.

The functionality merged with an interactive flask app works perfectly when tested using Google Colab. However, when I deploy the exact same code on the AWS EC2 instance, I receive the below error - 

`ValueError: len(set(targets) is 1 but len(list(range(int(max(targets)+1))) is  2`

On the web-page, it also prompts that server might be overloaded.

I am unable to understand the meaning of the above error. I believe it appears [here](https://github.com/amaiya/ktrain/blob/236ed49f85324ff01a5cb100a8e292a25ccf2c8e/ktrain/utils.py#L608) in the code-base.

It would be great if you could explain and help. 

Let me know if more information is required.

Regards,
Paritosh.

**Comment by amaiya** [comment]
Hello:  The error is basically saying that the total number of different targets is 1, but it is expecting the training set to have 2 targets based on the class indices.  In other words, when training a model, **ktrain** currently assumes that there should be at least one example for every possible target.  In your case, it sounds like you have an example with target 1 but no training examples with target 0.    For continual learning, are you able to supply supplemental training sets that cover all possible targets?

**Comment by katreparitosh** [comment]
Hello,

My work-flow is 

1. Predict the class for input text. 
2. Pass the text and predicted class to the continual learning function based on [Method 1](https://github.com/amaiya/ktrain/blob/master/FAQ.md#method-1-using-predictor-api-works-for-any-model)
3. Somehow, this functionality works perfectly when I run on Google Colab but not when I deploy on EC2.

Basically, you mean to say that ktrain requires _at least_ **1** example from each class before it trains/fine-tunes any model from scratch or checkpoint? 

Kindly share your thoughts.

**Comment by amaiya** [comment]
I mean to say that there's a check to make sure there are examples with three different targets if the maximum target is 2 (i.e., 0,1,2), for example.  The check makes sense when training for first time to make sure the `Preprocessor` instance is constructed correctly, etc.  Not sure if this check makes sense for continual learning, though (if you make sure to use the original `Preprocessor` instance when initially training). So, perhaps it should be changed to warning.

As far as the difference between Colab and EC2:  are you sure the exact same data is being used?  It's difficult to say what's happening without observing your data, but I don't see a reason why the check would be triggered on EC2 but not on Colab if the data is the same.

**Comment by katreparitosh** [comment]
Thanks for the information @amaiya.

Please view a Colab notebook and the output. I loaded the saved model and passed a (text - label) as arguments to the CL function. 

It got successfully executed without me requiring to pass an example of the other class as required by the check.

[Notebook](https://colab.research.google.com/drive/1tUPKtR64Pk_j7FepyKOcFKlkitV4P2qs?usp=sharing) 

Looking forward to your comments.

**Comment by amaiya** [comment]
Hello:  Your example notebook isn't self-contained, so I can't run it.  I re-created your example using the 20-newsgroup dataset and was able to reproduce the error (when an example with any class other than 0 is supplied).  This is the current expected behavior, as training sets (even when resuming training) are assumed to have at least one example for each class.  If you're seeing different behavior between EC2 and colab, it may be a difference in your data or code between the two.

If you want to train in an online fashion, we can perhaps look into relaxing that assumption of `preprocess_train`.  In the mean time, you can probably just process your dataset with `preprocess_test`, which will transform your dataset into a format that can be used for training (without resetting any of the `preproc` values when you first called `preprocess_train` using examples from all classes).

**Comment by katreparitosh** [comment]
Hello @amaiya,

The continual learning bit is now working smoothly when I process new data with `preprocess_test`. Thanks for the help. 

I have two questions though:

1. How is `preprocess_train` and `preprocess_test` different in Ktrain?
2. Secondly, why is the check block required which gives the above error? How does the check benefit the overall ML flow within Ktrain or in general?

It would be great if you could elaborate on this too.

**Comment by amaiya** [comment]
1. It depends on the model.  With `transformers`, the differece is related to target processing. For instance, if targets are string labels then `preprocess_train`  fits a LabelEncoder, while `preprocess_test` just applies the LabelEncoder.
2. The reason for the check is that a model can't learn targets that it hasn't seen.  If you supply examples only with targets 0 and 3, then this implies there are 4 possible labels, and the model will not know how to deal with test examples with targets of 1 and 2.

**Comment by katreparitosh** [comment]
Thank you!
