### ISSUE TITLE
How to do transfer learning

### ISSUE THREAD

**Issue by talhaanwarch** [amaiya/ktrain#318]
Is there any example where we have data with 4 class, we trained a bert model for that data , then we use that pre-trained bert to train again on a data having two classes

**Comment by amaiya** [comment]
If you're trying to re-use the weights of the last Fully-Connected (i.e., Dense) layer in a 4-class classifier, I suppose you can add another randomly-initialized 2-class Dense layer at the end and fine-tune the whole thing on the 2-class dataset.  You'll have to refer to the `tf.keras` documentation on how to to do this, but [this notebook](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A4-customdata-text_regression_with_extra_regressors.ipynb) does something similar.

**Comment by talhaanwarch** [comment]
Sorry, my question is specific to transformers, once I saved the model, how can I load it back again here
```
import ktrain
from ktrain import text
MODEL_NAME = 'bert-base-multilingual-cased'
t = text.Transformer(MODEL_NAME, maxlen=512,classes=['real','fake'])
```
