### ISSUE TITLE
Question: How to show the data after preproc

### ISSUE THREAD

**Issue by kangPrayit** [amaiya/ktrain#319]
Hi, maybe this is a newbie question,
I want to know, how could we show our image after pre-processing using this code?

`(data_train, data_val, preproc) = vis.images_from_array(train_images, train_labels,
                                                        validation_data=[test_images, test_labels],
                                                        data_aug=vis.get_data_aug(rotation_range = 15, 
                                                                                  zoom_range=0.3),
                                                        random_state=42,
                                                        class_names=class_names)`

I want to see the resulting image after it gets augmentation, also actually what is preproc hold for?

Thanks,

**Comment by amaiya** [comment]
You can use the `vis.preview_data_aug` function, as described at the end of this [notebook](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A1-additional-tricks.ipynb):

```python
vis.preview_data_aug(DATADIR+'/train/cats/cat.10000.jpg', data_aug, n=8, rows=2)
```

The `preproc` objects are responsible for preprocessing the raw image (or text or graph or table) into the format expected by the model under consideration.
