### ISSUE TITLE
problem deploying transformer based model into other computers

### ISSUE THREAD

**Issue by davidrotor** [amaiya/ktrain#322]
I'm having trouble deploying model into another computer due to the fact that when I create the transformer model it hard codes paths to the distilbert model I used to my trained models configuration file and preproc file and when I run it I get the following error:

OSError: Can't load config for 'C:\Users\xxxxxxx\Desktop\Models\distilbert-base-multilingual-cased'. Make sure that:

- 'C:\Users\xxxxxx\Desktop\Model\distilbert-base-multilingual-cased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'C:\Users\xxxxxx\Desktop\Model\distilbert-base-multilingual-cased' is the correct path to a directory containing a config.json file

is there a way when loading a predictor to set the distilbert pretrained path again? If not I would need look for other alternatives due to this being an actual requirement due to the fact that no internet connection on computers I need to deploy it to

**Comment by amaiya** [comment]
There is [an entire FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-use-ktrain-without-an-internet-connection) on how to do this.

Also, when deploying models, you might also consider quantizing and exporting models to ONNX which results in a much smaller footprint (and no need to have ktrain, TensorFlow, or PyTorch installed on the deployment machine.  See the FAQ entry on [How do I make quantized predictions with transformers models?](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-make-quantized-predictions-with-transformers-models)

I will close this, but feel free to reply to this thread if there are further questions.

**Comment by amaiya** [comment]
Also, it's not clear which calls you invoked to setup and train the model.  If you trained the model as described in most of the tutorial/example notebooks, then there should be no hard-coded paths except to the Hugging Face cache, which is something `transformers` does.

However, if you initially trained the model by supplying your own path to the call to `Transformer` (e.g., supplying the path to a language model you fine-tuned), then you can simply use one of the methods described in [this additional FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-pretrain-a-language-model-for-use-with-ktrain) to load your `Predictor` on the deployment machine.

**Comment by davidrotor** [comment]
Hi frankly the FAQ did help me but not in the sense it was intended ok so when I finish finetuning for classification the resulting preproc points to the path where I had my pretrained distilbert model but the problem is that path did not exist on the new computer so what I did was after loading my predictor again I rename the model name to the new path

loaded_model.preproc.model_name = os.path.join(self.dir, 'distilbert-base-multilingual-cased')

self.dir being the executable folder where I roll out both new model and the pretrained hugginface model.
 and it worked

**Comment by davidrotor** [comment]
thanks for the help I should've been more explicit on what the problem was
