### ISSUE TITLE
ktrain uses GPU memory, but uses CPU to process in BERT (RTX 3080, CUDA 11.0, tensorflow-gpu 2.4.1, cuDNN 8.0)

### ISSUE THREAD

**Issue by Richard929292** [amaiya/ktrain#325]
I understand the 3000 series GPUs are new and Tensorflow itself is struggling with them, but is there any way I might fix this myself? The error feels very strange as it can clearly access the GPU, but will only use the GPU for its RAM. GPU memory usage jumps to 100%, CPU usage jumps from 2% to 50%, GPU usage stays at 0%. I used the BERT notebook example to test.

**Comment by amaiya** [comment]
Hello:  This is more of a TensorFlow installation issue than a **ktrain** issue.  **ktrain** suppresses a lot of warnings by default.  If you want to see them, you can add the following to the top of your script or notebook:

```python
import os
os.environ['SUPPRESS_DEP_WARNINGS'] = '0'
```

This may shed more light on what's going on.

**Comment by ppsoong** [comment]
I'm having the same issue when using ktrain's `ZeroShotClassifier()` but am able to use my GPU with Tensorflow and Transformer regularly. I did try suppressing warnings like suggested but did not see anything.

Windows 10
Nvidia Drivers: 461.72
Tensorflow: 2.4.1
CUDA: 11.2.1
CuDNN: 8.1.1
TensorRT: 7.2.3
