### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'str' : ktrain vis

### ISSUE THREAD

**Issue by KameniAlexNea** [amaiya/ktrain#330]
When the names of the different images consist only of numbers, the following sum does not pass.
Please cast the integer (the name) first before summing.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-6e9608d332a9> in <module>
      7                                                       # use a default data augmentation with horizontal_flip=True
      8                                                       data_aug=vis.get_data_aug(horizontal_flip=True),
----> 9                                                       random_state=41
     10                                                      )

~/.local/lib/python3.6/site-packages/ktrain/vision/data.py in images_from_csv(train_filepath, image_column, label_columns, directory, suffix, val_filepath, is_regression, target_size, color_mode, data_aug, val_pct, random_state)
    636                           color_mode=color_mode,
    637                           data_aug=data_aug,
--> 638                           val_pct=val_pct, random_state=random_state)
    639 
    640 

~/.local/lib/python3.6/site-packages/ktrain/vision/data.py in images_from_df(train_df, image_column, label_columns, directory, val_directory, suffix, val_df, is_regression, target_size, color_mode, data_aug, val_pct, random_state)
    511         train_df = train_df.copy()
    512         val_df = val_df.copy()
--> 513         train_df[image_column] = train_df.copy()[image_column].apply(lambda x : x+suffix)
    514         val_df[image_column] = val_df.copy()[image_column].apply(lambda x : x+suffix)
    515 

~/.local/lib/python3.6/site-packages/pandas/core/series.py in apply(self, func, convert_dtype, args, **kwds)
   4211             else:
   4212                 values = self.astype(object)._values
-> 4213                 mapped = lib.map_infer(values, f, convert=convert_dtype)
   4214 
   4215         if len(mapped) and isinstance(mapped[0], Series):

pandas/_libs/lib.pyx in pandas._libs.lib.map_infer()

~/.local/lib/python3.6/site-packages/ktrain/vision/data.py in <lambda>(x)
    511         train_df = train_df.copy()
    512         val_df = val_df.copy()
--> 513         train_df[image_column] = train_df.copy()[image_column].apply(lambda x : x+suffix)
    514         val_df[image_column] = val_df.copy()[image_column].apply(lambda x : x+suffix)
    515 

TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by amaiya** [comment]
@KameniAlexNea: Thank you - this is now fixed in the `develop` branch and will be included in the next release.
