### ISSUE TITLE
disable word embedding download

### ISSUE THREAD

**Issue by felixdittrich92** [amaiya/ktrain#331]
Hello,
if i use a trained NER model (with load model) in multiprocessing it downloads every process the bert word embeddings (~522mb) how can i disable the download ?
Best greetz
Felix

**Comment by amaiya** [comment]
Hi,

BERT word embeddings are contextual, so it should be an entire model that's being downloaded, not static word vectors.  The model is downloaded by **transformers**, not **ktrain**.  And, if the model already exists in the cache (i.e., usually in `<home_directory>/.cache/huggingface/transformers`), then **transformers** usually does not download it again - least of all in all four processes.    Are you sure the same files are being downloaded by every process and it is the BERT model that is being downloaded?

If you're referring to fasttext embeddings, these should also only be downloaded once (but do take some time to load into model):
```python
if os.path.isfile(wv_path_or_url) and wv_path_or_url.endswith('vec'): return wv_path_or_url
```

**Comment by felixdittrich92** [comment]
Hi,

thanks for your answer :) 
So it was a bug on my side
