### ISSUE TITLE
Parse .predict() output for visualization with displaCy  

### ISSUE THREAD

**Issue by NicoleJaneway** [amaiya/ktrain#332]
I'm working on an NER application.  I would like to visualize the output of the predictor.predict() function using displaCy.  Per the [instructions for manual rendering](https://spacy.io/usage/visualizers#manual-usage), I need to reformat the document and entities as follows:

```
ex = {
    "text": "Electrocardiogram findings reveal the patient suffered a myocardial infarction which was treated with ACE inhibitors.",
    "ents": [{"start": 0, "end": 17, "label": "TEST"}, {"start": 54, "end": 78, "label": "PROBLEM"}, {"start":101, "end":116, "label":"TEST"}]
}

html = displacy.render(ex, style="ent", manual=True)
```

By contrast, the output from the predictor function is a list of tuples.

I'm finding the reformat to be a challenge.  I'm working with multi-paragraph documents (clinical notes), and I'm not sure the best way to approach this effort.  Has anyone attempted this or something similar and would be able to point me in the right direction?

**Comment by amaiya** [comment]
Hello:  The list of tuples are essentially token indices (e.g., the first tuple is token 0, the second tuple is token 1, etc.).  So, it sounds like you basically want to convert the token indices to character indices (with single space separating tokens).  Perhaps do something like this:
```python
lst = [('James', 'B-PER'),
 ('Gandolfini', 'I-PER'),
 ('is', 'O'),
 ('my', 'O'),
 ('favorite', 'O'),
 ('American', 'B-GPE'),
 ('actor', 'O'),
 ('.', 'O')]

text = " ".join([t[0] for t in lst])
print("text joined with single space:\n%s\n\n" % (text))

total = 0
lst2 = []
for token in lst:
    start = total
    end = total+len(token[0])
    label = token[1]
    total += 1 + len(token[0])
    if label == 'O': continue
    lst2.append({'start':start, 'end':end, 'label':label})

print('converted to character indices:\n%s\n\n'% (lst2))
print('checking if character indicies are correct...')
for d in lst2:
    print(text[d['start']:d['end']])

```
If you want to combine multi-word entities into single entry, then you'll need to add some extra processing or use `merge_tokens=True` with `predict`.
