### ISSUE TITLE
issue loading predictor

### ISSUE THREAD

**Issue by issafuad** [amaiya/ktrain#333]
Hi

I am using the following versions

ktrain==0.25.4
transformers==3.5.1

I saved a predictor of fine tuned distil bert model. 

```
predictor = ktrain.get_predictor(learner.model, preproc=t)
predictor.save('drive/MyDrive/development_resources/distil_bert_128_tax_1_4_predictor')
```

and I am trying to load the predictor using 

```
reloaded_predictor = ktrain.load_predictor('drive/MyDrive/development_resources/distil_bert_128_tax_1_4_predictor')
```

however I am getting the following error

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/ktrain/text/preprocessor.py in _load_pretrained(self, mname, num_labels)
   1004             try:
-> 1005                 model = self.model_type.from_pretrained(mname, config=self.config)
   1006             except:

16 frames
<__array_function__ internals> in reshape(*args, **kwargs)

ValueError: cannot reshape array of size 33024 into shape (768,193)

During handling of the above exception, another exception occurred:

UnpicklingError                           Traceback (most recent call last)
UnpicklingError: invalid load key, 'H'.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/ktrain/text/preprocessor.py in _load_pretrained(self, mname, num_labels)
   1008                     model = self.model_type.from_pretrained(mname, config=self.config, from_pt=True)
   1009                 except:
-> 1010                     raise ValueError('could not load pretrained model %s using both from_pt=False and from_pt=True' % (mname))
   1011         else:
   1012             model = self.model_type.from_pretrained(mname, num_labels=num_labels)

ValueError: could not load pretrained model drive/MyDrive/development_resources/distil_bert_128_tax_1_4_predictor using both from_pt=False and from_pt=True
```

**Comment by amaiya** [comment]
Hello:  I wasn't able to reproduce this using the latest version of **ktrain** on my end.

What does the following print for you?

```python
import pickle
preproc_path = 'drive/MyDrive/development_resources/distil_bert_128_tax_1_4_predictor/tf_model.preproc'
with open(preproc_path, 'rb') as f: preproc = pickle.load(f)
print(preproc.model_name)
print(preproc.model_type.__name__)
print(preproc.get_classes())
```

**Comment by kkarthikvk** [comment]
Hey amaiya,

I am also facing the same issue .

Using the following  versions:
transformers == 3.1
tensorflow == 2.1
ktrain==0.25.4

Output of the code you mention above (I am not getting any error):
        distilbert-base-uncased
        TFAutoModelForSequenceClassification
        ['Other content', 'valid']

Only thing is i trained on Windows and can able to load in windows OS .  But while trying to load in Linux server facing this issue .

Thanks in advance !

**Comment by amaiya** [comment]
Hi @kkarthikvk 

Thanks for letting me know the output of the previous commands.  Can you please tell me what happens when you run these new command (below)?  
```python
from transformers import *
config = AutoConfig.from_pretrained('path/to/your/predictor/folder')
config.num_labels = 2
TFAutoModelForSequenceClassification.from_pretrained('path/to/your/predictor/folder', config=config)
```

Note that `path/to/your/predictor/folder` is the path to the folder containing `tf_model.h5`, `tf_model.preproc`, and `config.json`.  All three files should exist in that folder.

**Comment by kkarthikvk** [comment]
Hey ,
After running the code above i am getting this error :

Error was in 'model = TFAutoModelForSequenceClassification.from_pretrained('path/to/your/predictor/folder', config=config)'



AttributeError                            Traceback (most recent call last)
<ipython-input-8-2cbab52f5a8d> in <module>
      2 config = AutoConfig.from_pretrained('/home/perlzuser/Documents/Crexi_2model_DistilBert_classification/DistilBert_V_O_predictor')
      3 config.num_labels = 2
----> 4 model = TFAutoModelForSequenceClassification.from_pretrained('/home/perlzuser/Documents/Crexi_2model_DistilBert_classification/DistilBert_V_O_predictor', config=config)

~/Documents/Crexi_2model_DistilBert_classification/transformers/modeling_tf_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
   1513         for config_class, model_class in TF_MODEL_FOR_SEQUENCE_CLASSIFICATION_MAPPING.items():
   1514             if isinstance(config, config_class):
-> 1515                 return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
   1516         raise ValueError(
   1517             "Unrecognized configuration class {} for this kind of TFAutoModel: {}.\n"

~/Documents/Crexi_2model_DistilBert_classification/transformers/modeling_tf_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    606         # see https://github.com/tensorflow/tensorflow/blob/00fad90125b18b80fe054de1055770cfb8fe4ba3/tensorflow/python/keras/engine/network.py#L1339-L1357
    607         try:
--> 608             model.load_weights(resolved_archive_file, by_name=True)
    609         except OSError:
    610             raise OSError(

~/Documents/Crexi_2model_DistilBert_classification/tensorflow_core/python/keras/engine/training.py in load_weights(self, filepath, by_name, skip_mismatch)
    232         raise ValueError('Load weights is not yet supported with TPUStrategy '
    233                          'with steps_per_run greater than 1.')
--> 234     return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
    235
    236   @trackable.no_automatic_dependency_tracking

~/Documents/Crexi_2model_DistilBert_classification/tensorflow_core/python/keras/engine/network.py in load_weights(self, filepath, by_name, skip_mismatch)
   1218       if by_name:
   1219         hdf5_format.load_weights_from_hdf5_group_by_name(
-> 1220             f, self.layers, skip_mismatch=skip_mismatch)
   1221       else:
   1222         hdf5_format.load_weights_from_hdf5_group(f, self.layers)

~/Documents/Crexi_2model_DistilBert_classification/tensorflow_core/python/keras/saving/hdf5_format.py in load_weights_from_hdf5_group_by_name(f, layers, skip_mismatch)
    720   """
    721   if 'keras_version' in f.attrs:

**Comment by amaiya** [comment]
Thanks @kkarthikvk .  This error is coming directly from **tranfsormers**, not **ktrain**.  The error seems to indicate something about TPUs: `Load weights is not yet supported with TPUStrategy`.    Did you use a TPU?

**Comment by kkarthikvk** [comment]
Thanks @amaiya  . No , i haven't . I have trained with CPU . Now i have trained with Linux server (CPU) can not able load after training .  Getting the same error .

**Comment by amaiya** [comment]
@kkarthikvk I'm not able to reproduce this at all.  The error is coming directly from **transformers**, not **ktrain**.  If you post the entire code for how you trained model, I will try look into it further.

**Comment by amaiya** [comment]
https://github.com/tensorflow/tensorflow/issues/44467
