### ISSUE TITLE
 resume training

### ISSUE THREAD

**Issue by jorgeutd** [amaiya/ktrain#335]
Amaiya,

Like always, thank you for maintaining this library.

I have the following question in regards of resuming training, I am using the text.texts_from_df funcitons, is there a place in which my (x_train, y_train), (x_test, y_test) is saved? O I would have split the data again once that I want to resume training?

Thanks,

Jorge

**Comment by amaiya** [comment]
Hello:  The dataset is not saved anywhere, but you can re-split the data in the same way by supplying the `random_state` parameter to the `texts_from_df` function.   If you want, you can also save the preprocessed dataset yourself, which I've seen some people do.  Assuming you already have seen this, but [this FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-resume-training-from-a-saved-checkpoint) provides info on resuming training itself.

**Comment by jorgeutd** [comment]
Thank you @amaiya I will re-split the data using the random_state parameter.
