### ISSUE TITLE
Support for  Bert BETO 

### ISSUE THREAD

**Issue by aqp** [amaiya/ktrain#337]
Ktrain should document how to provide support to use other BERT models (models in other languages) like  BETO  bert-base-spanish-wwm-uncased

https://github.com/dccuchile/beto
https://huggingface.co/dccuchile/bert-base-spanish-wwm-uncased

Regards,

**Comment by amaiya** [comment]
[This tutorial](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A3-hugging_face_transformers.ipynb) explains how to run other models.  For instance, [this notebook](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/examples/text/ArabicHotelReviews-AraBERT.ipynb) uses the `AraBERT` model for Arabic.
