### ISSUE TITLE
Text preprocessing - Bert Classification

### ISSUE THREAD

**Issue by hritik5102** [amaiya/ktrain#338]
Hello @amaiya, is text preprocessing (expanding contraction, stopwords, punctuation, spell correction, HTML tags, links, tags, mention, emoticons, stemming, or lemmatization) is already done in the ktrain if yes then where is the code? , or do we have to pass preprocesses text to ktrain bert model.

![image](https://user-images.githubusercontent.com/44053202/110121305-3af3be00-7de4-11eb-9310-59ba659c3dd7.png)

The text must be preprocessed in a specific way for use with BERT. This is accomplished by setting preprocess_mode to ‘bert’. - _**[Medium article](https://towardsdatascience.com/bert-text-classification-in-3-lines-of-code-using-keras-264db7e7a358)**_

What is that argument doing? How it preprocesses the data?

<img src="https://miro.medium.com/max/1400/1*edasquwJ3ij3nP31HtjE9g.png"/>

Please help, Thank you :)

**Comment by amaiya** [comment]
The way things are handled depends on the model.  For **transformers** models, see [this guide](https://huggingface.co/transformers/tokenizer_summary.html) for how text is preprocessed and tokenized.  For **non-transformers** models (e.g., NBSVM), see the documentation on [Keras tokenizers](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/text/Tokenizer), where you can see what punctuation is being filtered out.

Most of the things you mentioned might be important for sklearn bag-of-words models, but may be less important (and even detrimental in some cases) for **transformers** models that are sequential and contextual.  Note that many of things you mentioned (e.g., punctuation, lemmatization, stopwords, etc.) do not need to be explicitly handled by you -  most especially with **transformers**-based models.  For instance, pretrained models include learning representations for punctuation so they shouldn't be filtered out when fine-tuning and can provide important context that improves results.  You should also avoid filtering out stopwords for the same reasons.  See the references I mentioned above for more information.  Filtering out HTML tags before calling `texts_from_folder` and fine-tuning may or may not be a good idea, so you'll have to experiment with that.
