### ISSUE TITLE
Error while importing Ktrain in Colab

### ISSUE THREAD

**Issue by katreparitosh** [amaiya/ktrain#339]
Hi, 

Importing ktrain in Google Colab gives an unseen `ImportError:cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' (/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py`

I imported ktrain after installing it with pip3. 

![image](https://user-images.githubusercontent.com/42617598/110427014-1857f280-80cd-11eb-8ceb-227ac6bd5bb6.png)

Kindly check and advise.

**Comment by amaiya** [comment]
@katreparitosh: Thanks for letting me know.  As @VELCpro  said,  `transformers==3.5.1` is not compatible with PyTorch 1.8.  

The latest version of **ktrain** (v0.26.0) now uses `transformers>4.0.0` (compatible with PyTorch 1.8), so this problem should now be resolved.  However, if using an older version of **ktrain**, you will need to downgrade PyTorch to 1.7.1, as @VELCpro stated.

**Comment by katreparitosh** [comment]
Thanks @VELCpro and @amaiya !
