### ISSUE TITLE
Which editor to use while manually editing the .preproc file?

### ISSUE THREAD

**Issue by katreparitosh** [amaiya/ktrain#340]
Hi, 

I updated ktrain, transformers, and allied to the latest versions as mentioned. 

After editing and saving the changes to the preproc file w.r.t the older distilbert model, the updated .preproc file jumbles up the text into garbage characters, thereby throwing the `'.preproc file not found'` error same as before when loading the models. (see image) 

This is with the inbuilt editor of WinSCP for EC2 deployment.

What is the ideal way to edit and which editor would you suggest using while editing the modules to the latest transformers structure as mentioned [here](https://github.com/amaiya/ktrain#news-and-announcements).

![image](https://user-images.githubusercontent.com/42617598/110605080-c2f41200-81ae-11eb-9ac1-f555f1f6cadd.png)

**Comment by amaiya** [comment]
If you ssh into your EC2 machine and edit the file using **vim** (or another local editor), it should work.  The integrated WinSCP editor [only supports Windows-formatted text files](https://winscp.net/eng/docs/task_edit#binary), I think. 

Alternatively, you can also try re-generating your `.preproc` file from scratch and then using it to re-create your Predictor (without re-training your model)
```python
# Step 1: preprocess the original training set (e.g., by invoking Transformer, texts_from_folder, etc.)
# NOTE:
# 1. if training set is large, you can use a sample containing at least one example for each class
# 2. labels must be in same format as you originally used
preproc = text.Transformer(MODEL_NAME, maxlen=500, class_names=class_names)
trn = preproc.preprocess_train(x_train, y_train)

# Step 2: load the transformers model from predictor folder
from transformers import *
model = TFAutoModelForSequenceClassification.from_pretrained('/tmp/my_predictor/')

# Step 3: re-create/re-save Predictor
predictor = ktrain.get_predictor(model, preproc)
predictor.save('/tmp/my_new_predictor')
```

**Comment by katreparitosh** [comment]
@amaiya Thanks for the info.
