### ISSUE TITLE
Tabular classification ValueError: could not convert string to float: '0_cls'

### ISSUE THREAD

**Issue by KameniAlexNea** [amaiya/ktrain#343]
processing train: 82095 rows x 32 columns
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-e412126d1672> in <module>
      1 trn, val, preproc = tabular.tabular_from_df(train, is_regression=False, 
----> 2                                              label_columns=list(targets), random_state=0)

~/.local/lib/python3.6/site-packages/ktrain/tabular/data.py in tabular_from_df(train_df, label_columns, date_columns, val_df, val_pct, is_regression, max_card, random_state, verbose)
     36     preproc = pp.TabularPreprocessor(predictor_columns, label_columns, date_columns=date_columns, 
     37                                      is_regression=is_regression, procs=procs, max_card=max_card)
---> 38     trn = preproc.preprocess_train(train_df, verbose=verbose)
     39     if verbose:
     40         integer_cats = []

~/.local/lib/python3.6/site-packages/ktrain/tabular/preprocessor.py in preprocess_train(self, df, mode, verbose)
    102             #label_columns.sort() # leave label columns sorted in same order as in DataFrame
    103             self.label_transform = U.YTransformDataFrame(label_columns, is_regression=self.is_regression)
--> 104             df = self.label_transform.apply_train(df)
    105             self.label_columns = self.label_transform.get_classes() if not self.is_regression else self.label_transform.label_columns
    106             self.cont_names, self.cat_names = cont_cat_split(df, label_columns=self.label_columns, max_card=self.max_card)

~/.local/lib/python3.6/site-packages/ktrain/utils.py in apply_train(self, df)
    710 
    711     def apply_train(self, df):
--> 712         return self.apply(df, train=True)
    713     def apply_test(self, df):
    714         return self.apply(df, train=False)

~/.local/lib/python3.6/site-packages/ktrain/utils.py in apply(self, df, train)
    705             df[col] = targets[:,i]
    706         df[new_lab_cols] = targets
--> 707         df[new_lab_cols] = df[new_lab_cols].astype('float32')
    708 
    709         return df

~/.local/lib/python3.6/site-packages/pandas/core/generic.py in astype(self, dtype, copy, errors)
   5546         else:
   5547             # else, only a single dtype is given
-> 5548             new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors,)
   5549             return self._constructor(new_data).__finalize__(self, method="astype")
   5550 

~/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py in astype(self, dtype, copy, errors)
    602         self, dtype, copy: bool = False, errors: str = "raise"
    603     ) -> "BlockManager":
--> 604         return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
    605 
    606     def convert(

~/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py in apply(self, f, align_keys, **kwargs)
    407                 applied = b.apply(f, **kwargs)
    408             else:
--> 409                 applied = getattr(b, f)(**kwargs)
    410             result_blocks = _extend_blocks(applied, result_blocks)
    411 

~/.local/lib/python3.6/site-packages/pandas/core/internals/blocks.py in astype(self, dtype, copy, errors)
    593             vals1d = values.ravel()
    594             try:
--> 595                 values = astype_nansafe(vals1d, dtype, copy=True)
    596             except (ValueError, TypeError):
    597                 # e.g. astype_nansafe can fail on object-dtype of strings

~/.local/lib/python3.6/site-packages/pandas/core/dtypes/cast.py in astype_nansafe(arr, dtype, copy, skipna)
    995     if copy or is_object_dtype(arr) or is_object_dtype(dtype):
    996         # Explicit copy, or required since NumPy can't view from / to object.
--> 997         return arr.astype(dtype, copy=True)
    998 
    999     return arr.view(dtype)

ValueError: could not convert string to float: '0_cls'

**Comment by amaiya** [comment]
You  haven't provided enough information to investigate this.  Can you please provide more information on the dataset that is generating this error?  What are the columns and column values in your dataset?  Most importantly, what do the labels look like in the original DataFrame?

**Comment by KameniAlexNea** [comment]
Sorry for the lack of information
The error occurs when I try to do multilabel classification with ktrain
The classes of each label are: 0_cls, 1_cls, ..., 5_cls

I think in the preprocessing, you try to convert all columns in the dataset to float32. Which is a problem.

When I work with only one column, I don't have this problem (prediction of each labe after the other)

**Comment by amaiya** [comment]
Thanks @KameniAlexNea.  If you have more than one label column, then the data in the DataFrame is assumed to be one-hot-encoded (multiclassification) or multi-hot encoded (multilabel classification). (So, float conversion should never be a problem.)  For multilabel problems in **ktrain**, the data must be in multi-hot-encoded format.  So, your label columns would look something like  this:
```
0_cls     1_cls     2_cls 
1          1           0 
0          1           1  
```
The first line above contains the column headers.  So, the first example has labels (0_cls and 1_cls) and the second example has labels (1_cls and 2_cls).

This is documented in the docstrings for other data types (text, images) but not for `tabluar_from_df`.  We'll need to add proper documentation for `tabular_from_df` to make this clear.  

If you run into problems after re-formatting your data as above, please do reply to this issue.  Thanks for letting me know.
