### ISSUE TITLE
Does ktrain support multi-GPU?

### ISSUE THREAD

**Issue by Cheng-Lily** [amaiya/ktrain#344]
Does ktrain support multi-GPU?

**Comment by amaiya** [comment]
Hello:  You can take a look at [this post](https://github.com/amaiya/ktrain/issues/122#issuecomment-614146404) and this [FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-train-using-multiple-gpus) for how to try multi-gpu training.  Thanks.
