### ISSUE TITLE
trying to work with tpu, any suggestions

### ISSUE THREAD

**Issue by mv96** [amaiya/ktrain#347]
everything works fine so far when I use GPU for bert training , however as soon as I shift to TPU weird things start to happen

I was following your text classification section on your medium blog : https://radiant-brushlands-42789.herokuapp.com/towardsdatascience.com/ktrain-a-lightweight-wrapper-for-keras-to-help-train-neural-networks-82851ba889c

The error message I get is:
 `UnimplementedError: File system scheme '[local]' not implemented (file: '/tmp/tmppmqqcpkv_temp/part-00000-of-00001')
	Encountered when executing an operation using EagerExecutor. This error cancels all future operations and poisons their output tensors.`

The code I used is as follows:

# the tpu part

`%tensorflow_version 2.x
import tensorflow as tf
print("Tensorflow version " + tf.__version__)

try:
  tpu = tf.distribute.cluster_resolver.TPUClusterResolver()  # TPU detection
  print('Running on TPU ', tpu.cluster_spec().as_dict()['worker'])
except ValueError:
  raise BaseException('ERROR: Not connected to a TPU runtime; please see the previous cell in this notebook for instructions!')

tf.config.experimental_connect_to_cluster(tpu)
tf.tpu.experimental.initialize_tpu_system(tpu)
tpu_strategy = tf.distribute.experimental.TPUStrategy(tpu)`

# the code taken from the blog
`import ktrain
from ktrain import text as txt

with tpu_strategy.scope():
  DATA_PATH = '/content/drive/MyDrive/testing_toxic.csv'
  NUM_WORDS = 50000
  MAXLEN = 150
  label_columns = ["toxic", "severe_toxic", "obscene", 
                  "threat", "insult", "identity_hate"]

  (x_train, y_train), (x_test, y_test), preproc =  txt.texts_from_csv(DATA_PATH,
                                  'comment_text',
                                  label_columns=label_columns,
                                  val_filepath=None, 
                                  max_features=NUM_WORDS, 
                                  maxlen=MAXLEN,
                                  ngram_range=1)

  model = txt.text_classifier('fasttext', (x_train, y_train), 
                              preproc=preproc)

  learner = ktrain.get_learner(model, train_data=(x_train, y_train),
                                    val_data=(x_test, y_test))

  #learner.lr_find()
  #learner.lr_plot()

  learner.autofit(0.0007, 8)`

# output received
`detected encoding: utf-8 (if wrong, set manually)
language: en
Word Counts: 196953
Nrows: 143613
143613 train sequences
train sequence lengths:
	mean : 67
	95percentile : 228
	99percentile : 567
x_train shape: (143613,150)
y_train shape: (143613, 6)
Is Multi-Label? True
15958 test sequences
test sequence lengths:
	mean : 67
	95percentile : 230
	99percentile : 571
x_test shape: (15958,150)
y_test shape: (15958, 6)
Is Multi-Label? True
compiling word ID features...
maxlen is 150
done.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py in __getattribute__(self, name)
    787     try:
--> 788       return super(OptimizerV2, self).__getattribute__(name)
    789     except AttributeError as e:

AttributeError: 'Adam' object has no attribute 'beta_1'

During handling of the above exception, another exception occurred:

UnimplementedError                        Traceback (most recent call last)
21 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in shape(self)
   1173         # `_tensor_shape` is declared and defined in the definition of
   1174         # `EagerTensor`, in C.
-> 1175         self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())
   1176       except core._NotOkStatusException as e:
   1177         six.raise_from(core._status_to_exception(e.code, e.message), None)

UnimplementedError: File system scheme '[local]' not implemented (file: '/tmp/tmppmqqcpkv_temp/part-00000-of-00001')
	Encountered when executing an operation using EagerExecutor. This error cancels all future operations and poisons their output tensors.`

**Comment by amaiya** [comment]
You can take a look at [this post](https://github.com/amaiya/ktrain/issues/212) and [this post](https://github.com/amaiya/ktrain/issues/136) for more information.    For instance, **ktrain** currently uses `tf.data.Dataset.from_generator` for `transformers` models which [may be problematic for TPUs](https://github.com/tensorflow/tensorflow/issues/32712).
