### ISSUE TITLE
What's the rationale swapping confidence after re-ranking on QA?

### ISSUE THREAD

**Issue by ilos-vigil** [amaiya/ktrain#350]
Specifically i mean this part (https://github.com/amaiya/ktrain/blob/master/ktrain/text/qa/core.py#L191)

```py
top_confidences = [a['confidence'] for idx, a in enumerate(answers) if a['confidence']> rerank_threshold]
# rerank code
answers = sorted(answers, key = lambda k:(k['similarity_score'], k['confidence']), reverse=True)
for idx, confidence in enumerate(top_confidences):
    answers[idx]['confidence'] = confidence
```

**Comment by amaiya** [comment]
It's just a trick that was borrowed from a discussion forum somewhere.  Top results are re-ranked based on question-answer similarity (and confidences are swapped accordingly).  You can disable it if desired by setting `rerank_threshold=None`.
