### ISSUE TITLE
Improve preprocessing functions

### ISSUE THREAD

**Issue by sisygoboom** [amaiya/ktrain#353]
I can't help but notice that (Transformer) .preprocess_train() and .preprocess_test() are very slow with large datasets and that these functions are single threaded.

I propose that multi-threading is used to improve the performance of these functions by the number of processor cores available.

A similar example of this being done can be seen in the [modin project](https://github.com/modin-project/modin) where the creators adapted pandas to use multi-threading.

**Comment by amaiya** [comment]
Hello:  Thanks - this is a good suggestion.  There aren't immediate plans to add parallelization, but please consider submitting a PR for this feature, if you'd like to see it added. 

In the mean time, [some have parallelized the preprocessing](https://github.com/amaiya/ktrain/issues/153#issue-620738843) of large datasets with dask using something like this:

```python
import dask
def preproc(x, labels = labels):
    MODEL_NAME = 'distilbert-base-uncased'
    t = text.Transformer(MODEL_NAME, maxlen=80, class_names = labels, multilabel=True)
    res = t.preprocess_train(x['text_a'].values.tolist(),x['label'].values.tolist(), verbose=0)
    return(res)

results = []
partitions = train.to_delayed()
for part in partitions:
    results.append(dask.delayed(preproc)(part))

results = client.compute(results)

trn = results[0].result()
x = [r.result().x for r in results]
y = [r.result().y for r in results]
numlabels = np.max([yy.shape[1] for yy in y])
y = [np.pad(yy,[0,numlabels - yy.shape[1]], 'constant', constant_values = 0) for yy in y]
trn.x  = np.concatenate(x, axis = 0)
trn.y  = np.concatenate(y, axis = 0)
```
