### ISSUE TITLE
Load and use trained model with ktrain

### ISSUE THREAD

**Issue by bulioses** [amaiya/ktrain#354]
I have a trained model in .h5 and preproc file format for racial recognition using ktrain library. How do I get to load and use the trained model at a later time.

**Comment by amaiya** [comment]
You can use a `Predictor` instance, which is demonstrated in [each of the tutorial notebooks](https://github.com/amaiya/ktrain/tree/master/tutorials) and the [example notebooks](https://github.com/amaiya/ktrain/tree/master/examples), as well.

**Comment by bulioses** [comment]
Your tutorials and example notebooks were very helpful.
But I am still unable to load and use my trained model on a new notebook or
at a later time after training on the ktrain library, except i have to
retrain from scratch.
After training I got a .h5 and a preproc file, which I saved on my google
drive. How do I go about loading and using the trained model without having
to start training all over again. I have tried the predictor instance, but
it can only work on a new notebook at a later time. Please I need your
assistance. Thanks.

**Comment by amaiya** [comment]
You stated the following:
> I have tried the predictor instance, but it can only work on a new notebook at a later time. 

It's not clear what you mean by this, so I don't understand the source of your confusion.  Once the `.h5` model and `.preproc` Preprocessor instance is saved, you can reload and make predictions either within the same notebook or a new notebook (without retraining the model):
```python
predictor = ktrain.load_predictor('/tmp/my_predictor')
predictor.predict(data)
```

See [this Google Colab notebook](https://colab.research.google.com/drive/1YxcceZxsNlvK35pRURgbwvkgejXwFxUt) for example.

**Comment by bulioses** [comment]
Thank you, I will do that.

**Comment by bulioses** [comment]
Thank you very much Maiya. I have been able to use the preprocessor
instance without retraining the model. The notebook was helpful.

Now, i'm trying to redeploy the ktrain model which is for computer vision
(race/gender estimation) on flask. How do I go about it? I only came across
your notebook for text classification.

**Comment by amaiya** [comment]
You can take a look at these resources:

https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-deploy-a-model-using-flask

https://blog.keras.io/building-a-simple-keras-deep-learning-rest-api.html

**Comment by bulioses** [comment]
Thanks alot. I will check them out and get back to you.

**Comment by fabulouz1** [comment]
> You stated the following:
> 
> > I have tried the predictor instance, but it can only work on a new notebook at a later time.
> 
> It's not clear what you mean by this, so I don't understand the source of your confusion. Once the `.h5` model and `.preproc` Preprocessor instance is saved, you can reload and make predictions either within the same notebook or a new notebook (without retraining the model):
> 
> ```python
> predictor = ktrain.load_predictor('/tmp/my_predictor')
> predictor.predict(data)
> ```
> 
> See [this Google Colab notebook](https://colab.research.google.com/drive/1YxcceZxsNlvK35pRURgbwvkgejXwFxUt) for example. Once the `.h5` and `.preproc` are saved, you can transport it to a different machine (e.g., your local laptop) and load it using the code above to make predictions at a later time.
> 
> If you're still having trouble, please provide more details on why the above does not resolve your problem.

Good day Amaiya, I just discovered I cant redeploy the model on a  new notebook (i'm sure i dont know  how to go about it). I'm replicating the age estimation task on your github notebook. But  I couldn't redeploy the saved model for a later use on a fresh notebook.
I keep getting the "NameError: name 'learner' is not defined" after calling the predictor instance. Do i need to convert the learner.model to a json file?.

**Comment by bulioses** [comment]
> You stated the following:
> 
> > I have tried the predictor instance, but it can only work on a new notebook at a later time.
> 
> It's not clear what you mean by this, so I don't understand the source of your confusion. Once the `.h5` model and `.preproc` Preprocessor instance is saved, you can reload and make predictions either within the same notebook or a new notebook (without retraining the model):
> 
> ```python
> predictor = ktrain.load_predictor('/tmp/my_predictor')
> predictor.predict(data)
> ```
> 
> See [this Google Colab notebook](https://colab.research.google.com/drive/1YxcceZxsNlvK35pRURgbwvkgejXwFxUt) for example. Once the `.h5` and `.preproc` are saved, you can transport it to a different machine (e.g., your local laptop) and load it using the code above to make predictions at a later time.
> 
> If you're still having trouble, please provide more details on why the above does not resolve your problem.

Good day Amaiya, I just discovered I cant redeploy the model on a  new notebook (i'm sure i dont know  how to go about it). I'm replicating the age estimation task on your github notebook. But  I couldn't redeploy the saved model for a later use on a fresh notebook.
I keep getting the "NameError: name 'learner' is not defined" after calling the predictor instance. Do i need to convert the learner.model to a json file?.

**Comment by amaiya** [comment]
It sounds like this is coding error on your end.  You don't need a `Learner` instance to reload the `Predictor` instance in a deployment scenario to make predictions on new data. If you post your entire code, I can try to help further.

**Comment by bulioses** [comment]
Okay, thanks. i will do just that.

**Comment by bulioses** [comment]
Here is the code I used for training training code
<https://colab.research.google.com/drive/1U1Sg4Oyjy-zatdeSynDRpirTJFozoAHG#scrollTo=gorIaIoEnJa1>

Here is a new notebook where i tried to load and use the saved model to
make further predictions load saved model
<https://colab.research.google.com/drive/1NbmsPNWShfD9hWdZGJoThKmOPftpxp1s>
Here is the folder containing the saved model (the .h5 and preproc file)
after training, just incase you need it

 age_Amaya
<https://drive.google.com/drive/folders/1f_pAgf3J1KLfBCcqZv6IvASqCg9s95kR>

I will be anticipating for a positive response from you, so i solve solve
further problems.
Thanks alot.

**Comment by amaiya** [comment]
Access to your notebooks was denied

**Comment by bulioses** [comment]
I'm sorry about that. I have given access now.
This is the trained model, containing the .h5 and preproc files

 Amaya_age_predict.ipynb
<https://colab.research.google.com/drive/1U1Sg4Oyjy-zatdeSynDRpirTJFozoAHG?ouid=106465896083804561239>
Here is the code for training
 age_Amaya
<https://drive.google.com/drive/folders/1f_pAgf3J1KLfBCcqZv6IvASqCg9s95kR>
Here is the new notebook where i tried to redeploy the model without
retraining.

 Redeploy_trained_model.ipynb
<https://colab.research.google.com/drive/1NbmsPNWShfD9hWdZGJoThKmOPftpxp1s?ouid=106465896083804561239>

Thanks.

**Comment by amaiya** [comment]
It sounds like you're not accessing your Google Drive folder in the correct way.  In other words, this is not an issue with **ktrain**.

After adding a shortcut to the folder you shared with me, I was able to load your predictor just fine:
```python
predictor = ktrain.load_predictor('/content/drive/MyDrive/age_predictormaya')
```
I would recommend that you go through some tutorials on how to access Google Drive with Google Colab.

**Comment by bulioses** [comment]
Thanks very much. I will do just that.
I hope I'm able to get it right this time.

**Comment by bulioses** [comment]
I have finally gotten it. I wasn't properly accessing my my drive from
google colab.
Thank you very much.
I will always get in touch with you as I progress.

**Comment by bulioses** [comment]
Good morning Amaiya. How are you doing?
Is it possible to augment my data with ktrain? I want to create several
samples of my image dataset at different angles.
If possible how do I go about it?
Thanks.

**Comment by bulioses** [comment]
And also convert rgb images to grayscale.
