### ISSUE TITLE
Need a help on steps to download config.json and vocab.txt

### ISSUE THREAD

**Issue by sonu1125** [amaiya/ktrain#355]
Dear Author,

I need a help on steps to be followed to download config.json and vocab.txt from the Model trained using Ktrain. I'm using the COLAB Environment. 

I'm trying to share the model through Hugging Face

**Comment by amaiya** [comment]
Go to the Hugging Face [model hub](https://huggingface.co/models), select a model (e.g., [distilbert-base-uncased](https://huggingface.co/distilbert-base-uncased)), and click [Files and Versions](https://huggingface.co/distilbert-base-uncased/tree/main).
