### ISSUE TITLE
Plot the training and validation accuracy 

### ISSUE THREAD

**Issue by laxmimerit** [amaiya/ktrain#356]
how to make use of this function learner.plot() for the saved model?

**Comment by amaiya** [comment]
Please see the docstring for the method  (type  SHIFT+TAB in Jupyter notebook or `help(learner.plot)` in iPython):
```python
    def plot(self, plot_type='loss', return_fig=False):
        """
        plots training history
        Args:
          plot_type (str):  one of {'loss', 'lr', 'momentum'}
          return_fig(bool):  If True, return matplotlib.figure.Figure
        Return:
          matplotlib.figure.Figure if return_fig else None
        """
```
It is also used in [this notebook](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A4-customdata-text_regression_with_extra_regressors.ipynb).
