### ISSUE TITLE
Predictor loading broken in 0.26

### ISSUE THREAD

**Issue by sisygoboom** [amaiya/ktrain#358]
ktrain.load_predictor() is broken in 0.26, had to downgrade to 0.25 to get it to work. The error mentions not being able to find tf_model.preproc

**Comment by amaiya** [comment]
The reason and the solution is documented in the README under NEWS & ANNOUNCEMENTS here:

https://github.com/amaiya/ktrain

The newest version of **ktrain** uses `transformers>=4.0` (and `transformers>=4.0` included a re-organization of the module structure).  

You'll need to edit (or re-generate) your `tf_model.preproc` if it was created using an older version of **ktrain**.
