### ISSUE TITLE
how to support for other language models like deberta / t5 ?

### ISSUE THREAD

**Issue by mv96** [amaiya/ktrain#360]
Code I put in Colab was:

`MODEL_NAME = **'microsoft/deberta-base'**

    t = text.Transformer(MODEL_NAME, maxlen=100, classes=le.classes_)

    trn = t.preprocess_train(x_train, y_train)
    val = t.preprocess_test(x_test, y_test)

    model = t.get_classifier()
    print(type(model))

    learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
    #learner.lr_find(show_plot=True,max_epochs=10)

    learner.fit_onecycle(2e-4, 10,
                         callbacks=[EarlyStopping(monitor='val_loss',patience=3, min_delta=0.0001)],
                         checkpoint_folder= os.getcwd())`

can you suggest how to use ktrain for other language models ? ,Thanks

`Unrecognized configuration class <class 'transformers.models.deberta.configuration_deberta.DebertaConfig'> for this kind of TFAutoModel: TFAutoModelForSequenceClassification.
Model type should be one of ConvBertConfig, DistilBertConfig, AlbertConfig, CamembertConfig, XLMRobertaConfig, LongformerConfig, RobertaConfig, BertConfig, XLNetConfig, MobileBertConfig, FlaubertConfig, XLMConfig, ElectraConfig, FunnelConfig, GPT2Config, MPNetConfig, OpenAIGPTConfig, TransfoXLConfig, CTRLConfig.`

**Comment by amaiya** [comment]
On the Hugging Face model hub, the `deberta-base` model is currently [uploaded only as  a PyTorch model](https://huggingface.co/microsoft/deberta-base/tree/main), which can be loaded like this:
```python
# works
from transformers import *
model = AutoModelForSequenceClassification.from_pretrained('microsoft/deberta-base')
```
**ktrain** can load PyTorch models as TensorFlow models using the `from_pt=True` argument, so this is not typically a problem.
Unfortunately, for this particular model, this functionality is not working:
```python
# returns the same error you saw
from transformers import *
model = TFAutoModelForSequenceClassification.from_pretrained('microsoft/deberta-base', from_pt=True)
```
This does not appear to be an issue with **ktrain**, as other PyTorch models can be loaded as TensorFlow models with no problem.  

 **ktrain** uses `transformers==4.3.3`, but the above is not working in the current `transformers==4.5.1` either.

So, perhaps it is a bug in `transformers`?
