### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by fabulouz1** [amaiya/ktrain#361]
I just discovered ktrain and and it is so unique!
Has anyone tried to deploy image classification model  with ktrain on flask? 
If yes, please help with the code.

**Comment by amaiya** [comment]
Hello,

Yes, people have served image classification models in **ktrain** using **Flask**.

You can take a look at these resources:

https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-deploy-a-model-using-flask

https://blog.keras.io/building-a-simple-keras-deep-learning-rest-api.html
