### ISSUE TITLE
How to save a model locally ?

### ISSUE THREAD

**Issue by mv96** [amaiya/ktrain#362]

**Comment by mv96** [comment]
Is it possible to download the model offline so that next time when running code it would not require to download model online, thanks

**Comment by amaiya** [comment]
If you'd like to download and use a model offline without internet connection, please see [this FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-use-ktrain-without-an-internet-connection).

That said, Hugging Face models are automatically cached in `<home_directory>/.cache/huggingface/transformers`.  So, they shouldn't be downloaded again after the initial download if you're on the same machine.
