### ISSUE TITLE
possibility to use SciBERT with ktrain ?

### ISSUE THREAD

**Issue by mv96** [amaiya/ktrain#363]
Hi amiya,

I was planning to use Scibert transformer model specifically trained on scientific articles in one of my first research paper for determining proofs, and theorems by reading the text, I was not very sure how to use it with Ktrain library ?

in the documentation they provide code implementation to make it work with the hugging face ?

```
from transformers import *

tokenizer = AutoTokenizer.from_pretrained('allenai/scibert_scivocab_uncased')
model = AutoModel.from_pretrained('allenai/scibert_scivocab_uncased')

tokenizer = AutoTokenizer.from_pretrained('allenai/scibert_scivocab_cased')
model = AutoModel.from_pretrained('allenai/scibert_scivocab_cased')
```

on this GitHub link - https://github.com/allenai/scibert

any help from your end would be much appreciated, I am following the text classification tutorials and one of your blogs on medium titled "Text Classification with Hugging Face Transformers in TensorFlow 2 (Without Tears)"

once again many thanks for this wonderful library it has really made it easy to solve NLP problems 😘

**Comment by amaiya** [comment]
Hello:  Yes, you can use SciBERT in **ktrain**.   

As described in the [blog post you mentioned](https://towardsdatascience.com/text-classification-with-hugging-face-transformers-in-tensorflow-2-without-tears-ee50e4f3e7ed), you can just set `MODEL_NAME` to `'allenai/scibert_scivocab_uncased'` (or whichever model you want).  The SciBERT model is actually in PyTorch format, but **ktrain** will automatically load it successfully as a TensorFlow model. (You can ignore the 404 client error, which indicates that no TensorFlow version exists for this model.)
