### ISSUE TITLE
Ktrain in docker container 

### ISSUE THREAD

**Issue by jorgeutd** [amaiya/ktrain#364]
Hello Amaiya,

First thank you for always helping with new requests.

I am trying to run ktrain==0.25.3 in docker container and for some reason I am getting the following error when it tries to install seqeval-0.0.19?

Do you have any why this could be happening? Or have any experience with a similar issue?

Thanks.

Downloading seqeval-0.0.19.tar.gz (30 kB)
#17 79.31     ERROR: Command errored out with exit status 1:
#17 79.31      command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-whtladpm/seqeval_58940b3cbde84109841b646dc7f993bf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-whtladpm/seqeval_58940b3cbde84109841b646dc7f993bf/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3sxwfjxe
#17 79.31          cwd: /tmp/pip-install-whtladpm/seqeval_58940b3cbde84109841b646dc7f993bf/
#17 79.31     Complete output (135 lines):
#17 79.31       WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)'))':

**Comment by amaiya** [comment]
Hello:

You can take a look at [this post](https://stackoverflow.com/questions/62952004/local-issuer-certificate-error-uniquely-in-docker-with-python), which may help.

If you have trouble, you may also be able to try something like this:
> If you experience SSL certificate problems with either pip or conda, run conda config --set ssl_verify false and replace all pip commands above with pip --trusted-host pypi.org --trusted-host files.pythonhosted.org.
