### ISSUE TITLE
Error no file named ['pytorch_model.bin', 'tf_model.h5'] found in directory /content/data/model_out or `from_pt` set to False

### ISSUE THREAD

**Issue by Kowsher** [amaiya/ktrain#365]
I fined tuned a classification task using Bert base. Now i want to train again this model using ktrain . My trained model dict has config,json, pytoch_model.bin, special_tokens_map.json, tokenizer_config.json, vocab.txt. When i call the dic by ktrain then i shows  Error no file named ['pytorch_model.bin', 'tf_model.h5'] found in directory /content/data/model_out or `from_pt` set to False. Although I have pytoch_model.bin in the dic

**Comment by amaiya** [comment]
It's not clear what code/commands you ran to generate the error.    I will say that **ktrain** saves fine-tuned text classification models as TensorFlow models (i.e., `tf_model.h5`), not PyTorch models( i.e., `pytorch_model.bin`).  So, not sure where your `pytorch_model.bin` came from.

[This FAQ entry](https://github.com/amaiya/ktrain/blob/develop/FAQ.md#how-do-i-resume-training-from-a-saved-checkpoint) shows how to reload a model to resume training.
