### ISSUE TITLE
Plans for speech2text and text2speech?

### ISSUE THREAD

**Issue by marsel171** [amaiya/ktrain#370]
Hi there!

Thank you for that simplified library! 
Do you plan to implement in ktrain speech2text and text2speech?

**Comment by amaiya** [comment]
Hi @marsel171:  Yes, this will likely be supported in one form or another.  No definite time frame for this, but I've marked this as enhancement.  Thanks!

**Comment by amaiya** [comment]
Hello:  The latest version of **ktrain** includes some support for speech-to-text:

```python
from ktrain.text.speech import Transcriber
transcriber = Transcriber()
afiles = ['sample.wav']
result = transcriber.transcribe(afiles)
print(result)
```
