### ISSUE TITLE
Predicting on a test sequence using a distilbert model

### ISSUE THREAD

**Issue by karim140995** [amaiya/ktrain#372]
When using texts_from_* function with a DistilBert model it returns a TransformerDataset object rather than a numpy array like in the Bigru,Fasttext and NBSVM implementation. Its therefore not possible to use the learner.model.predict() method to predict on a test sequence. How is it possible to use a TransformerDataset object to predict on a test sequence and is there an implementation for this?

Thanks in advance.
Karim.

**Comment by amaiya** [comment]
Hello,

This is covered in the [text classification tutorial](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-04-text-classification.ipynb).

You generate a `Predictor` instance to make predictions on test data:
```python
predictor = ktrain.get_predictor(learner.model, preproc)
predictor.predict(['Groundhog Day is my favorite movie of all time!'])
predictor.save('/tmp/my_predictor')
predictor = ktrain.load_predictor('/tmp/my_predictor')
```

You can also try transforming raw data into a `TransformerDataset` instance with:
```python
tst = preproc.preprocess_test(['Text of some document.'])
learner.evaluate(test_data=tst)
```

**Comment by karim140995** [comment]
> Hello,
> 
> This is covered in the [text classification tutorial](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-04-text-classification.ipynb).
> 
> You generate a `Predictor` instance to make predictions on test data:
> 
> ```python
> predictor = ktrain.get_predictor(learner.model, preproc)
> predictor.predict(['Groundhog Day is my favorite movie of all time!'])
> predictor.save('/tmp/my_predictor')
> predictor = ktrain.load_predictor('/tmp/my_predictor')
> ```
> 
> You can also try transforming raw data into a `TransformerDataset` instance with:
> 
> ```python
> tst = preproc.preprocess_test(['Text of some document.'])
> learner.evaluate(test_data=tst)
> ```

Hello, 

Thank you for the quick response. This will work but predicting on raw textual data isn't very effective for me given that my text is already preprocessed. It would be helpful if there was a method to convert the val TransformerDataset variable that is returned into a numpy array. I will do some research in Hugging face docs.
