### ISSUE TITLE
Wrong ML prediction inside the docker

### ISSUE THREAD

**Issue by laxmimerit** [amaiya/ktrain#375]
Hi,
I have trained `distilbert` model with `ktrain` and deployed it with docker. I am getting a very weird result inside the docker. ml prediction is completely different from what I am getting out of the docker. I had also gone inside the docker with the docker shell. I loaded the model there and tested but the result was again wrong. 

I don't understand how this could be possible? I am using this config inside and outside of the docker.

```
python 3.7
tensorflow 2.3
ktrain 0.25.2
transformers 4.3
pytorch 1.7
```

Any idea how this could be possible?

**Comment by amaiya** [comment]
Hello:  It's hard to say what's going on, but I don't think it's anything related to ktrain as others  have used docker with no problem..  It's also not clear what "weird" means.  Perhaps, it is a confirmation or installation issue with tensorflow.

**Comment by laxmimerit** [comment]
Yes it is not the issue of ktrain. I have been using it with docker and had never encountered this. Actually, the classification result is not correct inside the docker. for example
```
x = 'usb cable'
predictor.predict(x)
```
gives me this output if I run code outside the docker
```
{'category':{'computer accessories':0.99965}}
```
but it gives me this inside the docker
```
{'category':{'none':0.5423}}
```

I have shown here results with probs above 0.5.

**Comment by amaiya** [comment]
The `predict` method does not return results in the format you showed. So, perhaps it's a bug in whatever other code you added.

**Comment by laxmimerit** [comment]
I am getting these values in the output. The output format may not be correct as of the original format of ktrain. But this is the behavior which I am getting.
