### ISSUE TITLE
upgrade semantic search

### ISSUE THREAD

**Issue by amaiya** [amaiya/ktrain#376]
ktrain currently only supports semantic searches in the context of topic models and LDA.  This enhancement will add support for semantic searches using transformer embeddings.

**Comment by TejasKarkera10** [comment]
Hello @amaiya  , I would like to work on this.  Will you please elaborate more and give a brief where to start working

**Comment by amaiya** [comment]
This is being closed for now, as functionality is now being planned as part of separate project.
