### ISSUE TITLE
slow predict Bert model on GPU

### ISSUE THREAD

**Issue by trimbilrepo** [amaiya/ktrain#377]
hii... its not bug or error.

Just to asking question
1. is it possible to convert Bert model to DistilBERT or tinyBert without re-train again?
I have already train Bert Model on my dataset. However, I took a change to run on gcp GPU Nvidia-K80, it took 4.4 second to predict the outcome which not good for production env.
is there any chance to convert my model to smaller or reduce the prediction time?

2. is there any way to squeeze GPU memory used on ktrain? when I run my model, it took all the available memory of the GPU. so that I can't forking my script.

thank you

**Comment by amaiya** [comment]
Hello,

I know that there are ways to prune a trained BERT, but I don't recall ever trying it.  So, you might try doing a Google search on that.
> Pruning:  Removes unnecessary parts of the network after training. This includes weight magnitude pruning, attention head pruning, layers, and others. Some methods also impose regularization during training to increase prunability (layer dropout).  

However, you could also try converting the model to ONNX (or TFLite) and quantizing the model which may speed up predictions.  See [this notebook](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/develop/examples/text/ktrain-ONNX-TFLite-examples.ipynb). This will also make the model smaller (less memory).   Note that the example assumes you're running inferences on a CPU.
