### ISSUE TITLE
parallelize ktrain

### ISSUE THREAD

**Issue by terence92** [amaiya/ktrain#378]
Hello,

I wanted to know if it is possible to parallelize the work of ktrain on multiple threads, as explained in this link
https://huggingface.co/blog/bert-cpu-scaling-part-1

It's possible?

**Comment by amaiya** [comment]
Hello:  Yes, it's possible.  **ktrain** is just a lightweight wrapper, and you always have direct access to the original TensorFlow model.  If it's a Hugging Face model, you can also convert your model to PyTorch very easily.  In other words, you can try anything described in that article.

You might also look into quantizing and converting your model to ONNX, as described in [this notebook](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/develop/examples/text/ktrain-ONNX-TFLite-examples.ipynb).
