### ISSUE TITLE
Allow loading of downloaded BERT

### ISSUE THREAD

**Issue by julianmukaj** [amaiya/ktrain#38]
Small enhancement recommendation, allow loading of BERT embedding via an already downloaded zip file so the package doesn't always download its own.

**Comment by amaiya** [comment]
This is already supported but with the some caveats.   If you manually download the BERT zip file and store it in the `ktrain_data` folder (which is in your home directory),  *ktrain* will check to make sure everything needed is there.  If it looks good, then that unzipped folder is used, and the BERT zip file is not re-downloaded.  Arbitrary locations of zip files are not supported at this time.
