### ISSUE TITLE
support for roberta-large?

### ISSUE THREAD

**Issue by randomgambit** [amaiya/ktrain#380]
Hello @amaiya !

I was able to load the distilbert model from huggingface while being OFFLINE behind a firewall (thanks for the FAQ!). However, when I tried to download another model (`roberta-large`: https://huggingface.co/roberta-large/tree/main) I got the error :

`OSError: Couldn't reach server at 'C:\Users\me\ktrain_data\bert-large\config.json' to download configuration file or configuration file is not a valid JSON file. Please check network or file content here: C:\Users\me\ktrain_data\bert-large\config.json.`

The only difference I see is that we have a `vocab.json` instead of a `vocab.txt` (like for the distilbert model https://huggingface.co/distilbert-base-uncased/tree/main). Do you see an easy fix?

Thanks!

**Comment by amaiya** [comment]
Hello @randomgambit :  I just tried it and it worked for me (with internet turned off).  You may not have downloaded the files correctly (`config.json` in this case).    The downloaded config.json should look like this:

```
{
  "architectures": [
    "RobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 1,
  "type_vocab_size": 1,
  "vocab_size": 50265
}
```

Perhaps, you can open `config.json` to ensure it looks like the above.
