### ISSUE TITLE
ktrain complaining about torch?!

### ISSUE THREAD

**Issue by randomgambit** [amaiya/ktrain#383]
Hi @amaiya and sorry to bother but `ktrain` stopped working recently, asking about `torch`

```
import ktrain
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
learner.fit_onecycle(5e-5, 4)
learner.validate(class_names=t.get_classes()) # class_names must be string values
ModuleNotFoundError: No module named 'torch'
```

I only had used `tensorflow` with `ktrain` in the past, and everything worked great. Do you know what the issue is here?

Thanks!

**Comment by amaiya** [comment]
Hello:  None of the commands you posted use `torch`.  I created a fresh virtual environment using the latest ktrain and only TensorFlow installed (no torch) and wasn't able to reproduce this problem.  So, I'm not sure where that error is coming from. 
 Perhaps try re-creating your virtual environment from scratch.

**Comment by amaiya** [comment]
I will close this issue for now, but feel free to reply to this thread if needed.
