### ISSUE TITLE
skip stratify when splitting graph dataset

### ISSUE THREAD

**Issue by qqfox** [amaiya/ktrain#385]
Is it possible to customize the graph_nodes_from_csv ? In my case, remove the stratify param.
Many thanks

**Comment by amaiya** [comment]
Yes, it would be easy to add a `stratify` parameter. I have marked this as Enhancement.  If you'd like to implement this yourself, please submit a pull request and I'll merge it.

**Comment by qqfox** [comment]
that's great. Many thanks in advance!
