### ISSUE TITLE
Predictor values are always the name of the categories column

### ISSUE THREAD

**Issue by fcasadome** [amaiya/ktrain#39]
Sorry if this is a too basic question, I'm trying to learn about text classification and I've been dealing with this issue for a few days now.
I'm following the example you provided:
[https://github.com/amaiya/ktrain/blob/master/tutorial-04-text-classification.ipynb](https://github.com/amaiya/ktrain/blob/master/tutorial-04-text-classification.ipynb)

The only difference is that i have my data in CSV format and I use pandas library to load it:

df = pd.read_csv('Historical_EdD_EN-ES.csv', low_memory=False, encoding='utf-8')
df['labels'] = pd.cut(df['RelEditDistance_NOFT'], [0, 0.15, 1], labels=[1, 0], include_lowest=True)
df = df[['Source_NOFT', 'labels']]

So I create the categories (1 and 0) based on the 'RelEditDistance_NOFT' column values. Anything below 0.15 will be category 1 and the rest 0. And 'Source_NOFT' column contains the text sentences.

```
df.head()

Source_NOFT | labels
View the help system for the Adaptive Keys | 0
Zoom in or zoom out | 0
If the slots are faulty, seek technical assist... | 1
Installing a storage drive into drive bay 3 | 0
Lenovo ThinkServer RD650 server (data node) | 1
```

Then I follow your code to create the model:

(x_train, y_train), (x_test, y_test), preproc = text.texts_from_df(
    train_df=df, text_column='Source_NOFT', label_columns=['labels'], max_features=MAX_FEATURES, 
    maxlen=MAX_LENGTH, ngram_range=3, preprocess_mode='standard')

model = text.text_classifier('nbsvm', (x_train, y_train), preproc=preproc)

 learner:

learner = ktrain.get_learner(model, train_data=(x_train, y_train), val_data=(x_test, y_test))
learner.fit(0.001, 3, cycle_len=1, cycle_mult=2)

 and predictor:

predictor = ktrain.get_predictor(learner.model, preproc)

Here's when the problem arises:

data = [ 'This movie was horrible! The plot was boring. Acting was okay, though.',
         'The film really sucked. I want my money back.',
        'What a beautiful romantic comedy. 10/10 would see again!']
predictor.predict(data)

result:
['labels', 'labels', 'labels']

I was expecting to get the actual category values, 1 or 0.

Could you please give me some hint on what could be happening?
Is there something I'm doing wrong?

Thanks a lot in advance,
Fran.

**Comment by Bidek56** [comment]
I believe you need to create 2 columns in your DF: ['postive', 'negative'] and set them to 0 or 1, 

```
df['postive'] = df['labels'].apply(lambda x: 1 if x == 1 else 0)
df['negative'] = df['labels'].apply(lambda x: 1 if x == 0 else 0)
```

then call:
```
(x_train, y_train), (x_test, y_test), preproc = text.texts_from_df(
train_df=df, text_column='Source_NOFT', label_columns=['postive', 'negative'], max_features=MAX_FEATURES,
maxlen=MAX_LENGTH, ngram_range=3, preprocess_mode='standard')
```

then call:

`predictor.predict(data)`

**Comment by amaiya** [comment]
Thank you, @Bidek56 

Yes, the labels are expected to be 1-hot-encoded.  I have corrected the docstring for `texts_from_csv` and `texts_from_df` to make this clear.

 In addition to @Bidek56 's answer, see also [this example notebook](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/examples/text/ArabicHotelReviews-nbsvm.ipynb) for converting integer labels in a Pandas dataframe to be 1-hot-encoded.

**Comment by fcasadome** [comment]
Thank you very much for your quick responses @Bidek56 and @amaiya!
That makes sense I guess, I'm going to try right away

**Comment by fcasadome** [comment]
Works like a charm now!
Thank you very much again :)
