### ISSUE TITLE
PicklingError: Can't pickle <class 'types.TFAutoModelForSequenceClassification'>: attribute lookup TFAutoModelForSequenceClassification on types failed

### ISSUE THREAD

**Issue by MeethS591** [amaiya/ktrain#398]
![Screenshot_2021-11-12-22-40-19-871_com whatsapp](https://user-images.githubusercontent.com/42151075/141506866-0ea9b6bd-415c-4709-9e4a-cd3d7f5409e8.jpg)

Having issue while saving the model.

Code:
https://www.kaggle.com/meeths/text-classification-distilbert

**Comment by amaiya** [comment]
The default version of `transformers` on Kaggle is 4.5.1, which is causing the problem.  

Please upgrade transformers to 4.10.3 in the Kaggle notebook and things will work correctly:

```python
!pip install transformers==4.10.3
```
The next version of `ktrain` will pin to a higher version of **ktrain**.

**Comment by MeethS591** [comment]
Thanks for the solution.
