### ISSUE TITLE
NER examples note book

### ISSUE THREAD

**Issue by sathish331977** [amaiya/ktrain#4]
is it possible to provide a NER example notebook

**Comment by amaiya** [comment]
Yes, adding NER to *ktrain* is planned for a future release.

**Comment by sathish331977** [comment]
Thank you for your response, looking forward to it.

Thanks,
Sathish G.

**Comment by amaiya** [comment]
*ktrain* v0.3.0 includes [support for NER](https://github.com/amaiya/ktrain/blob/master/tutorial-06-sequence-tagging.ipynb) with a Bidirectional LSTM-CRF model.   Currently, it supports both randomly initialized embeddings and pretrained word2vec embeddings.  

Contextual/dynamic word embeddings like BERT/ELMO will be coming soon.

**Comment by sathish331977** [comment]
> _ktrain_ v0.3.0 includes [support for NER](https://github.com/amaiya/ktrain/blob/master/tutorial-06-sequence-tagging.ipynb) with a Bidirectional LSTM-CRF model. Currently, it supports both randomly initialized embeddings and pretrained word2vec embeddings.
> 
> Contextual/dynamic word embeddings like BERT/ELMO will be coming soon.

Thank you

**Comment by laxmimerit** [comment]
Hi,
Will it be possible to use DistilBERT for NER with ktrain?  Any example notebook is available?

**Comment by laxmimerit** [comment]
Update
Hi, I think got it. I was going through the notebook which explains what I wanted.
```
https://github.com/amaiya/ktrain/blob/master/examples/text/CoNLL2002_Dutch-BiLSTM.ipynb
```
