### ISSUE TITLE
training on a huge dataset in batches

### ISSUE THREAD

**Issue by laxmimerit** [amaiya/ktrain#400]
Hi,
I have 50M data samples and my GPU can handle a maximum 1M otherwise it is throwing an `OOM` exception. I would like to train it in batches of 1M data samples at a time. One way I can figure out is to train it with a blank model for the first 1M samples then load the model again for retraining on another 1M sample and so on.  But I am not confident about this approach? 
Is it the right approach or does `ktrain` have any dataset iterator to handle it internally?

**Comment by amaiya** [comment]
Hi @laxmimerit Yes, I think the approach you described is the way to handle it.
