### ISSUE TITLE
Currently tested stable environment still up to date?

### ISSUE THREAD

**Issue by patrick-frank-bsi** [amaiya/ktrain#401]
Hi,

is the currently tested stable setup still as stated in the README?

> This code was tested on Ubuntu 18.04 LTS using TensorFlow 2.3.1 and Python 3.6.9.

**Comment by amaiya** [comment]
Thanks.  **ktrain**  should work on newer versions of Python and Tensorflow on Linux and Windows.  If you have trouble with a particular OS or Python/Tensorflow version, please do open an issue and let us know.
