### ISSUE TITLE
The way concatenate distilBERT model

### ISSUE THREAD

**Issue by WodenWang820118** [amaiya/ktrain#403]
Hi, thank you for building the awesome library. I've tried to concatenate the distilBERT text classifier model with other tensorflow models, but got something like `AttributeError: Layer features has no inbound nodes`. How could I concatenate the layer properly? Thanks.

Regards,
Woden

**Comment by amaiya** [comment]
Hello,

Thank you for your comments.  Concatenation with transformer models works differently.  Please see [this notebook](https://github.com/cerlymarco/MEDIUM_NoteBook/blob/master/Siamese_Dual_BERT/Siamese_Dual_BERT.ipynb) for an example of how concatenation can be made to work with transformer models.

**Comment by WodenWang820118** [comment]
Thanks, I'll study it. Thank you.
