### ISSUE TITLE
Is it possible to train multi-label multi-tag model with ktrain?

### ISSUE THREAD

**Issue by pochocosta** [amaiya/ktrain#404]
Hi, I'm asking me if I can train a model for "Multi-Label Text Classification for Stackoverflow Tag Prediction" using ktrain.

There is some example? 

Thanks a lot!

**Comment by amaiya** [comment]
Hello,

There is an example of multilabel text classification shown in the [text classification tutorial notebook](https://nbviewer.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-04-text-classification.ipynb#Multi-Label-Text-Classification:--Identifying-Toxic-Online-Comments).

Thanks.
