### ISSUE TITLE
Elmo sequence_taggers not working

### ISSUE THREAD

**Issue by tareefroustom** [amaiya/ktrain#405]
Environment Google Colab
Training purpose > NER 
Ktrain version > 0.28.3
Allennlp version > 2.8.0

error> allennlp not installed
if name in sys.modules:
    print(f"{name!r} already in sys.modules")
'allennlp' already in sys.modules

model   = text.sequence_tagger('bilstm-crf-elmo', preproc, bert_model='dmis-lab/biobert-v1.1')#, wv_path_or_url = WV_URL)
Exception: To use ELMo embedings, please install allenlp:
pip install allennlp

**Comment by amaiya** [comment]
It looks like the `pip install allennlp` error message is being displayed if importing modules from allennlp fails for any reason.  In this case, using `bilstm-crf-elmo` eventually results in `allennlp` trying to do:
```python
from typing import OrderedDict
```
If your version of Python is less than 3.6, this will fail and output the `pip install allennlp` error message.  

To solve, you can either downgrade `allennlp` to an older version that support Python 3.6 or upgrade Python to 3.7 or 3.8.

Note, however, that we will likely remove support for ELMo NER embeddings in the future and replace it with better-performing and more efficient `transformers`-based approaches.

Thanks for posting an issue to make us aware.
