### ISSUE TITLE
RE: tok_dct method on StandardTextPreprocessor(TextPreprocessor) class

### ISSUE THREAD

**Issue by irineosv** [amaiya/ktrain#41]
Arun, firstly I want to say Happy New Year! Secondly, you have done an excellent job with ktrain and provided tensorflow users some very useful and easy to use new tools! 

In relation to the preproc.tok_dct method of the StandardTextPreprocessor class, I always get an empty dictionary even though I have "fitted" the data. How can I get the vocabulary created? Have I misinterpreted the method? preproc.max_features and preproc.tok works fine. Here is what I did:

(x_train, y_train), (x_test, y_test), preproc = text.texts_from_array(x_train=texts,
                                                                     y_train=test,
                                                                     val_pct=0.3,
                                                                     class_names=names,
                                                                     preprocess_mode='standard',
                                                                     maxlen=200,
                                                                     max_features=2000,
                                                                     random_state=1)

preproc.max_features --> this returns 2000
preproc.tok_dct --> this returns {} 
preproc.tok --> this returns <keras_preprocessing.text.Tokenizer at 0x7f8a77f58cf8>

**Comment by amaiya** [comment]
Everything you need should be in `preproc.tok`.  The vocabulary is available in `preproc.tok.word_index` and `preproc.index_word` dictionaries, for example.  See Keras Tokenizer documentation for more details.

The `tok_dct` dictionary in `StandardTextPreprocessor` is a little confusing and may be changed/removed in future releases.  For right now, it stores the mappings between bigrams/trigrams/etc. and word IDs.  Bigrams/trigrams are tacked onto the end of the sequence only when ngram_range>1, so this is why it is empty in your example.    Thanks and Happy New year
