### ISSUE TITLE
Add basic guideline/suggestion for contributing

### ISSUE THREAD

**Issue by ilos-vigil** [amaiya/ktrain#410]
After made few PR, i noticed there's no basic guideline/suggestion for contributing to ktrain library. I think it'd be great to add few basic guideline/suggestion (whether on README.md or separate file) such as,

* Don't change internal behavior of existing feature/function
* Maintain backward compatibility
* How to run test files

**Comment by amaiya** [comment]
Yes, I  totally agree - I've added an initial `CONTRIBUTING.md`  to the `develop` branch that you can feel free to add/edit, as necessary.  Thanks!
