### ISSUE TITLE
TransformerTextClassLearner should be a classifier!

### ISSUE THREAD

**Issue by abdelrahmaan** [amaiya/ktrain#412]
I want to make Voting Classifier for some ktrain models, but give me this error!

`ValueError: The estimator TransformerTextClassLearner should be a classifier.`
How can I solve this

**All code**

```
X_train, X_test, y_train, y_test = train_test_split(data.text.values, data.target.values, test_size=0.2, random_state=2022)
tf_idf = TfidfVectorizer(analyzer= 'word', max_features= 10000, ngram_range= (1, 3))
X_train = tf_idf.fit_transform(X_train)
X_test = tf_idf.transform(X_test)


estimators=[('m1', m1), ('m2', m2), ('m2', m3)]
ensemble = VotingClassifier(estimators, voting= 'hard')
ensemble.fit(X_train, y_train)
predictions = ensemble.predict(X_test)
print(classification_report(y_test, predictions))
```

**Comment by amaiya** [comment]
Helllo:

`VotingClassifier` is a part of the scikit_learn API.  It checks if a model is a classifier using this and also expects specific methods to exist.
```
   return getattr(estimator, "_estimator_type", None) == "classifier"
```
Some people have got Keras models working with this by wrapping the Keras model in `KerasClassifier` and manually adding the `_estimator` attribute as described in [this post](https://stackoverflow.com/questions/62894695/grid-search-voting-classifier-containing-a-keras-model).

However, it looks like you're using an underlying `transformers` model, which is not a "vanilla" Keras model.  So, if it doesn't work for this reason, you can inspect the `scikit-learn` code to see what methods are being called on `KerasClassifier` and then simply build a wrapper around either the ktrain learner or the underlying transformers model directly (i.e., `learner.model`).  I recall some other users may have done something similar in the past and achieved success.
