### ISSUE TITLE
preprocessing train problem if train and ( len(set(targets)) != int(max(targets)+1) ):

### ISSUE THREAD

**Issue by letmeseeletmesee** [amaiya/ktrain#413]
I am getting 

extracting pretrained BERT model...
done.

cleanup downloaded zip...
done.

preprocessing train...
language: en
done.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-880def3fc11e> in <module>()
      4                                                                        preprocess_mode='bert',
      5                                                                        maxlen=500,
----> 6                                                                        max_features=1000)

3 frames
/usr/local/lib/python3.7/dist-packages/ktrain/utils.py in apply(self, targets, train)
    638 
    639             if train and ( len(set(targets)) != int(max(targets)+1) ):
--> 640                 raise ValueError('len(set(targets) is %s but max(targets)+1 is  %s' % ( len(set(targets)), int(max(targets)+1) ))
    641             targets = to_categorical(targets, num_classes=len(self.get_classes()))
    642         if train: self.train_called=True

extracting pretrained BERT model...
done.

cleanup downloaded zip...
done.

preprocessing train...
language: en
done.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-880def3fc11e> in <module>()
      4                                                                        preprocess_mode='bert',
      5                                                                        maxlen=500,
----> 6                                                                        max_features=1000)

3 frames
/usr/local/lib/python3.7/dist-packages/ktrain/utils.py in apply(self, targets, train)
    638 
    639             if train and ( len(set(targets)) != int(max(targets)+1) ):
--> 640                 raise ValueError('len(set(targets) is %s but max(targets)+1 is  %s' % ( len(set(targets)), int(max(targets)+1) ))
    641             targets = to_categorical(targets, num_classes=len(self.get_classes()))
    642         if train: self.train_called=True

**Comment by amaiya** [comment]
If you're using integer labels, they need to be numbered starting from 0. The error simply means that the number of unique targets in your training set is different from the maximum.   The training set should include at least one example for every possible label.

**Comment by letmeseeletmesee** [comment]
e.g. 

encoding = {
    'joy': 0,
    'sadness': 1,
    'fear': 2,
}

and both train and test set must contain joy, sadness and fear labels?

**Comment by letmeseeletmesee** [comment]
I am getting another error

TypeError                                 Traceback (most recent call last)
<ipython-input-27-ddb8d4ee4d25> in <module>()
      4                                                                        preprocess_mode='bert',
      5                                                                        maxlen=500,
----> 6                                                                        max_features=35000)

5 frames
/usr/local/lib/python3.7/dist-packages/keras_bert/tokenizer.py in _tokenize(self, text)
    101     def _tokenize(self, text):
    102         if not self._cased:
--> 103             text = unicodedata.normalize('NFD', text)
    104             text = ''.join([ch for ch in text if unicodedata.category(ch) != 'Mn'])
    105             text = text.lower()

TypeError: normalize() argument 2 must be str, not float
