### ISSUE TITLE
error during preprocessing, please help indicate cause

### ISSUE THREAD

**Issue by letmeseeletmesee** [amaiya/ktrain#414]
I am getting an error during preprocessing step, I imported text file as utf-18, and dtype= string

TypeError Traceback (most recent call last)
in ()
4 preprocess_mode='bert',
5 maxlen=500,
----> 6 max_features=35000)

5 frames
/usr/local/lib/python3.7/dist-packages/keras_bert/tokenizer.py in _tokenize(self, text)
101 def _tokenize(self, text):
102 if not self._cased:
--> 103 text = unicodedata.normalize('NFD', text)
104 text = ''.join([ch for ch in text if unicodedata.category(ch) != 'Mn'])
105 text = text.lower()

TypeError: normalize() argument 2 must be str, not float

**Comment by amaiya** [comment]
You haven't provided enough information.  The error traceback is not complete and doesn't show the method/function invoked.  If you want assistance, please provide a dataset that is causing the issue in addition to the precise method/function invoked, so that it can be reproduced.

**Comment by amaiya** [comment]
Please see [this post](https://stackoverflow.com/questions/67360987/bert-model-bug-encountered-during-training/67375675#67375675) for the possible solution.
