### ISSUE TITLE
unhashable type: 'numpy.ndarray'

### ISSUE THREAD

**Issue by realonbebeto** [amaiya/ktrain#420]
TypeError: unhashable type: 'numpy.ndarray'

When running this: history = learner.fit(LR, n_cycles=EPOCHS, checkpoint_folder='./')
based on:
    # Preprocess training and validation data
    train_set = t.preprocess_train(X_train, y_train)
    val_set = t.preprocess_test(X_test, y_test)

where X_train  and X_test are lists while y_train, y_test are arrays

**Comment by realonbebeto** [comment]
This is another trial from the tutorial: https://nbviewer.org/github/amaiya/ktrain/blob/develop/tutorials/tutorial-A3-hugging_face_transformers.ipynb


# Set model parameters
MODEL_NAME = 'distilbert-base-uncased'
MAX_LEN = 256
BATCH_SIZE = 8
FOLDS = 3
LR = 2e-5
EPOCHS = 2

# List of class names
CLASS_NAMES = sorted(train.Labels.unique().tolist()) # ['neg', 'net', 'pos']

# Instantiate transformer with the provided parameters
t = text.Transformer(model_name=MODEL_NAME, maxlen=MAX_LEN, class_names=CLASS_NAMES, batch_size=BATCH_SIZE)

trn = t.preprocess_train(X_train.to_list(), Y_train.to_list())
val = t.preprocess_test(X_test.to_list(), Y_test.to_list())
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=BATCH_SIZE)


learner.fit_onecycle(LR, EPOCHS)


I face the same TypeError: unhashable type: 'numpy.ndarray'

**Comment by amaiya** [comment]
Please post the full error trace back and provide an example of what your dataset looks like (1st five rows).

**Comment by realonbebeto** [comment]
InvalidArgumentError                      Traceback (most recent call last)
/tmp/ipykernel_34/3871800743.py in <module>
----> 1 learner.fit_onecycle(LR, EPOCHS)

/opt/conda/lib/python3.7/site-packages/ktrain/core.py in fit_onecycle(self, lr, epochs, checkpoint_folder, cycle_momentum, max_momentum, min_momentum, class_weight, callbacks, steps_per_epoch, verbose)
    918                         checkpoint_folder=checkpoint_folder,
    919                         verbose=verbose, class_weight=class_weight, callbacks=kcallbacks,
--> 920                         steps_per_epoch=steps_per_epoch)
    921         hist.history['lr'] = clr.history['lr']
    922         hist.history['iterations'] = clr.history['iterations']

/opt/conda/lib/python3.7/site-packages/ktrain/core.py in fit(self, lr, n_cycles, cycle_len, cycle_mult, lr_decay, checkpoint_folder, early_stopping, class_weight, callbacks, steps_per_epoch, verbose)
   1400                                         shuffle=True,
   1401                                         class_weight=class_weight,
-> 1402                                         callbacks=kcallbacks)
   1403         if sgdr is not None: hist.history['lr'] = sgdr.history['lr']
   1404         self.history = hist

/opt/conda/lib/python3.7/site-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1182                 _r=1):
   1183               callbacks.on_train_batch_begin(step)
-> 1184               tmp_logs = self.train_function(iterator)
   1185               if data_handler.should_sync:
   1186                 context.async_wait()

/opt/conda/lib/python3.7/site-packages/keras/engine/training.py in train_function(iterator)
    851       def train_function(iterator):
    852         """Runs a training execution with one step."""
--> 853         return step_function(self, iterator)
    854 
    855     else:

/opt/conda/lib/python3.7/site-packages/keras/engine/training.py in step_function(model, iterator)
    839         return outputs
    840 
--> 841       data = next(iterator)
    842       outputs = model.distribute_strategy.run(run_step, args=(data,))
    843       outputs = reduce_per_replica(

/opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py in __next__(self)
    759   def __next__(self):
    760     try:
--> 761       return self._next_internal()
    762     except errors.OutOfRangeError:
    763       raise StopIteration

/opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py in _next_internal(self)
    745           self._iterator_resource,
    746           output_types=self._flat_output_types,
--> 747           output_shapes=self._flat_output_shapes)
    748 
    749       try:

/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py in iterator_get_next(iterator, output_types, output_shapes, name)
   2726       return _result
   2727     except _core._NotOkStatusException as e:
-> 2728       _ops.raise_from_not_ok_status(e, name)
   2729     except _core._FallbackException:
   2730       pass

/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6939   message = e.message + (" name: " + name if name is not None else "")
   6940   # pylint: disable=protected-access
-> 6941   six.raise_from(core._status_to_exception(e.code, message), None)
   6942   # pylint: enable=protected-access
   6943 

/opt/conda/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: TypeError: unhashable type: 'numpy.ndarray'
Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 247, in __call__
    return func(device, token, args)

  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 135, in __call__
    ret = self._func(*args)

  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 645, in wrapper
    return func(*args, **kwargs)

  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4167, in py_function_wrapper
    ret = self._func(*nested_args)

  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 945, in generator_next_fn
    flattened_types)

  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)

  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 739, in numpy_function
    return py_func_common(func, inp, Tout, stateful=True, name=name)

  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 626, in py_func_common
    result = func(*[np.array(x) for x in inp])

  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 892, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 714, in get_iterator
    return self._iterators[iterator_id]

TypeError: unhashable type: 'numpy.ndarray'


	 [[{{node EagerPyFunc}}]] [Op:IteratorGetNext]

**Comment by realonbebeto** [comment]
ID | Tweet | Label
2 | so chuga si tunakutana kesho kwenye nyamachoma... | 0
3 | asante sana watu wa sirari jimbo la tarime vi... | 1
5 | leo nimepata kitambulisho changu cha taifa as... | 1
6 | mgema akisifiwa tembo hulitia maji | 0
8 | ee mwenyezi mungu msamehe na umrehemu na umuaf... | 1

The Labels are [0,1, 2]

**Comment by amaiya** [comment]
I am not able to reproduce this problem on my end.  It sounds like it has to do [with your dataset format](https://stackoverflow.com/questions/51675151/appropriately).  I would recommend looking at the text classification tutorial. If you post a self-contained example of the problem on Google colab, I can help you look into it

**Comment by realonbebeto** [comment]
https://drive.google.com/file/d/1UKofE9cJe0ZC4-1mJH-yMevqh4eDqgk5/view?usp=sharing That is the Google colab

**Comment by amaiya** [comment]
I can't run your notebook because I don't have access to your data.  Please provide a self-contained example of the problem.

**Comment by realonbebeto** [comment]
how can i share data

**Comment by amaiya** [comment]
Sorry - I still have no idea how to access your dataset.

**Comment by realonbebeto** [comment]
> Sorry - I still have no idea how to access your dataset.

**Comment by realonbebeto** [comment]
Try it now

**Comment by amaiya** [comment]
This doesn't appear to be a ktrain isssue.  . Removing these lines gets things to work:
```python
tf.config.run_functions_eagerly(True)
tf.data.experimental.enable_debug_mode()
```

**Comment by realonbebeto** [comment]
Thanks
