### ISSUE TITLE
Question about Q&A (Cross Validation)

### ISSUE THREAD

**Issue by Steven-Palayew** [amaiya/ktrain#421]
> preproc  = text.Transformer(MODEL_NAME, maxlen=500)

Is called both inside and outside the cross validation loop [here ](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-do-cross-validation-with-transformers). Is this necessary? If not, is either/or acceptable? 

Thanks!

**Comment by amaiya** [comment]
Hello:  That looks like a typo.   Either outside or inside seems like it should be fine. But, I'll remove the outer one in the FAQ. Thanks for letting me know.
