### ISSUE TITLE
"Bi-LSTM Bert" NER model adding additional space for words containing special characters/punctuations

### ISSUE THREAD

**Issue by dummynov1** [amaiya/ktrain#426]
I was able to train `Bilstm-Bert` with "SciBERT" cased model using ktrain, but i have noticed that the Predict output adding additional space between decimals or words having special characters/punctuations in between words like `1.5 mg` --> `1 . 5 mg `, `1mg/10mL` --> `1mg / 10mL`.
Is there a way to avoid these additional spaces while using `Predict()` function with `merge_tokens=True`

I'm using the following code block

```Python
WV_URL = 'https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.vec.gz'
model = text.sequence_tagger('bilstm-bert', preproc, 
                            bert_model='allenai/scibert_scivocab_cased', wv_path_or_url=WV_URL)
```
```Python
text = '''
 75.5 mg tablet, twice a day 
 1 mg/ml solution for injection in a pre-filled syringe '''

predictor.predict(text,merge_tokens=True)  

```

Output:

```
[('75 . 5 mg', 'STRENGTH'),
 ('tablet', 'FORM'),
 ('1 mg / ml', 'STRENGTH'),
 ('solution for injection', 'FORM')]
```

**Comment by amaiya** [comment]
You can use the `custom_tokenizer` parameter and supply whatever tokenization scheme you want to the predictor.
