### ISSUE TITLE
Bilstm-Bert NER predict with Custom tokenizer

### ISSUE THREAD

**Issue by dummynov1** [amaiya/ktrain#427]
Thanks for your response on [#426](https://github.com/amaiya/ktrain/issues/426) 

I tried the following modified predict code (for the same usage as mentioned in #426 ) , but output is blank now when used `custom_tokenizer`  : 

```Python
predictor.predict(text,merge_tokens=True,custom_tokenizer = BertTokenizer.from_pretrained('bert-base-cased'))
```
Output : []

**Comment by amaiya** [comment]
As stated  in the docstring for `predict`, `custom_tokenizer` must be a callable.   The default is currently:
```python
re_tok = re.compile(f'([{string.punctuation}“”¨«»®´·º½¾¿¡§£₤‘’])')
def tokenize(s, join_tokens=False, join_char=' '):
    tokens = re_tok.sub(r' \1 ', s).split()
    if join_tokens: tokens = join_char.join(tokens)
    return tokens
```

**Comment by dummynov1** [comment]
> As stated in the docstring for `predict`, `custom_tokenizer` must be a callable. The default is currently:
> 

@amaiya : I tried using a callable tokenizer `nltk word_tokenizer`  on the text to check tokens : -

```python
text = '''
 75.5 mg tablet, twice a day 
 1 mg/ml solution for injection in a pre-filled syringe
'''
nltk.tokenize.word_tokenize(text)
```

output:  (as expected correctly tokenizing decimals and / )

```python
['75.5',
 'mg',
 'tablet',
 ',',
 'twice',
 'a',
 'day',
 '1',
 'mg/ml',
 'solution',
 'for',
 'injection',
 'in',
 'a',
 'pre-filled',
 'syringe']
```

But, when i pass the same tokenizer as `custom_tokenizer` in `predict()` function , i still get the same issue (decimals with space, and space around punctuations). is this due to `merge_tokens` ? :

```python
predictor.predict(text,merge_tokens=True,custom_tokenizer=nltk.tokenize.word_tokenize)

[('75 . 5 mg', 'STRENGTH'),
 ('tablet', 'FORM'),
 ('1 mg / ml', 'STRENGTH'),
 ('solution for injection', 'FORM')]
```

**Comment by amaiya** [comment]
I see the problem.  This seems common with `transformers` models if you run models like `pucpr/clinicalnerpt-quantitative`, which also inserts spaces between decimal points in  discovered quantities.  One way to address this is to use the character offsets of the entities to retrieve the original form of the entity from the original sentence.    The latest version of **ktrain** in the `develop` branch includes a `return_offsets` parameter:   `predictor.predict('75.5 mg tablet, twice a day', return_offsets=True, merge_tokens=True)`. 

When `return_offsets=True`, character offsets of each entity will be returned:
```python
sentence = '75.5 mg tablet, twice a day'
prediction =  [('75 . 5 mg', 'STRENGTH', (0,7)),  ('tablet', 'FORM', (8,14))]
```

Using the character offsets, you should be able to easily retrieve the correct form of the entity:
```python
for entity in prediction:
    word = entity[0]
    label = entity[1]
    start = entity[2][0]
    end = entity[2][1]
    corrected_word = sentence[start:end]
    print(f'{word} (tokenized form)  | {corrected_word} (original form)  |  {label}')

# 75 . 5 mg (tokenized form)  | 75.5 mg (original form)  |  STRENGTH
# tablet (tokenized form)  | tablet (original form)  |  FORM
```

The `return_offsets` parameter is experimental, so please test it out with your model and data and reply to this thread if you find issues.

**Comment by dummynov1** [comment]
@amaiya : Thanks :-)  . With the develop branch , `return_offsets` parameter, the output seems to be correct now.

```python
text = '''
 75.5 mg Tablet, twice a day 
 1 mg/ml solution for injection in a pre-filled syringe
'''
prediction = predictor.predict(text, return_offsets=True, merge_tokens=True)

for entity in prediction:
    word = entity[0]
    label = entity[1]
    start = entity[2][0]
    end = entity[2][1]
    corrected_word = text[start:end]
    print(corrected_word ,label)
```

output:

```
75.5 mg STRENGTH
Tablet FORM
1 mg/ml STRENGTH
solution for injection FORM
```

Looking for your future ktrain releases .
