### ISSUE TITLE
Cannot save intemediate weights with learner.fit()

### ISSUE THREAD

**Issue by ArinaBelova** [amaiya/ktrain#429]
Hello,

First of all, thank you for such an amazing framework as ktrain is!
I have an issue with saving intermediate weights of the model while calling learner.fit(5e-5, 1, cycle_len=5, checkpoint_folder='/tmp/distil_bert_saved_weights').
I have looked up how .fit() function saves these weights (https://github.com/amaiya/ktrain/blob/26de7fb42f9e576e768a22f9e5984d7d134b6bf0/ktrain/core.py#L796) and it seems to create a folder specified in checkpoint_folder argument. Unfortunately, it does not in my case and no weights are saved after the passed epoch.
Should I create a folder manually, so the function will know where to save the weights? 

Thank you!
Arina

**Comment by amaiya** [comment]
Hello,

Thanks for your comments.  I was not able to reproduce this problem using the latest version of **ktrain**.  The following code  automatically creates the folder `/tmp/distil_bert_saved_weights` correctly stores the weights in the folder.
```python
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
from sklearn.datasets import fetch_20newsgroups
train_b = fetch_20newsgroups(subset='train', categories=categories, shuffle=True)
test_b = fetch_20newsgroups(subset='test',categories=categories, shuffle=True)
(x_train, y_train) = (train_b.data, train_b.target)
(x_test, y_test) = (test_b.data, test_b.target)

# build, train, and validate model (Transformer is wrapper around transformers library)
import ktrain
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
learner.fit(5e-5, 2, cycle_len=1, checkpoint_folder='/tmp/distil_bert_saved_weights')
```

Are you able to reproduce this problem on Google Colab?  If so, please share the Colab notebook, so it can be investigated.  If not, perhaps provide more information to help reproduce the problem (code, data, information on OS and Python version ,etc.).
