### ISSUE TITLE
Question / Feature : Any plans of adding Next Sentence Prediction training framework on Ktrain

### ISSUE THREAD

**Issue by dummynov1** [amaiya/ktrain#430]
Thank you so much for building an amazing toolkit. , has been very helpful in quick solution building on various NLP use cases

I was wondering if there are any Next Sentence Prediction training framework planned for Ktrain, or if you could suggest any simple toolkit implementation of NSP ?

**Comment by amaiya** [comment]
Hi @dummynov1 :  Thanks for your comments.  This isn't supported in **ktrain**, but it seems like looking into [using transformers directly](https://stackoverflow.com/questions/66938274/bert-for-next-sentence-prediction) would make sense.
