### ISSUE TITLE
Load Ktrain model on macbook m1

### ISSUE THREAD

**Issue by Mokers1234** [amaiya/ktrain#434]
I've tried numerous methods to get Ktrain working on my macbook M1. I do have Tensorflow/Keras working however.

I have a Text regression model from Ktrain saved (.h5, .preproc files). Is there a way to load this model and predict on new data without using Ktrain > load_predictor? Is there an analog technique I can use, perhaps using just TF/Keras? Thanks

**Comment by amaiya** [comment]
Yes, you can convert your model to ether **ONNX** or **TensorFlow Lite**.  In the latter case, you will be able to make predictions using only TensorFlow.  In the former case, you can make predictions without even having TensorFlow installed.  Both are lightweight and are well-suited to environments requiring smaller footprints.  [This notebook](https://nbviewer.org/github/amaiya/ktrain/blob/develop/examples/text/ktrain-ONNX-TFLite-examples.ipynb) shows examples for both ONNX and TensorFlow Lite in **ktrain**.

That said, I know that others have successfully used Macbooks with **ktrain**, but sometimes there may be snafus in regards to the various dependencies.

**Comment by Mokers1234** [comment]
Thanks, this is exactly what I was looking for!

One problem. The text regression model_name for my model is ktrain's 'linreg' (for linear regression using embedding layers). So `tokenizer = AutoTokenizer.from_pretrained(model_name)` returns

OSError: Can't load config for 'linreg'. Make sure that:
- 'linreg' is a correct model identifier listed on 'https://huggingface.co/models'
- or 'linreg' is the correct path to a directory containing a config.json file

'linreg' isn't a listed model on https://huggingface.co/models, and I can't locate a config.json file exported from the model creation process. 

The .preproc file stems from ktrian.text.texts_from_array which uses 'standard' (normal tokenization): https://github.com/amaiya/ktrain/blob/master/ktrain/text/data.py

**Comment by amaiya** [comment]
The `linreg` model is not a Hugging Face model - it's just a vanilla `tf.keras` model.  So, the AutoTokenizers won't even come into play.   If you're just using a vanilla Keras model, you can just preprocess the data yourself and run it through the Keras model directly.  You can take a look at the source code of [StandardPreprocessor.preprocess_test](https://amaiya.github.io/ktrain/text/preprocessor.html#ktrain.text.preprocessor.StandardTextPreprocessor)  and replicate what it's doing.  What is the error traceback you are getting when using **ktrain** on your Macbook? I
