### ISSUE TITLE
Tensorflow seq2seq transformer tf.dataset to ktrain.TFDataset

### ISSUE THREAD

**Issue by JaeLee18** [amaiya/ktrain#438]
Hello,

I am doing a tutorial [https://keras.io/examples/nlp/neural_machine_translation_with_transformer/](https://keras.io/examples/nlp/neural_machine_translation_with_transformer/) but I am not sure how to convert tf.dataset to ktrain.TFDataset here.

In the tutorial, it created `train_ds ` so I tried to convert it by ktrain.TFDataset(train_ds ,n=???,y=???) but I cannot figure it out what is n and y for seq2seq..

Also, how can I import `TFDataset` ?
`AttributeError: module 'ktrain' has no attribute 'TFDataset'` on version 0.30

**Comment by amaiya** [comment]
Thanks for letting me know about this.  This was a change in v0.30.x that wasn't documented properly.  `TFDataset` must now be accessed with `ktrain.datset.TFDataset`:
```python
from ktrain.dataset import TFDataset
```
The Release Notes and A4 tutorial have been updated accordingly.

The `n` parameter is the number of examples in the dataset, and `y` is simply the y values in the dataset (to facilitate dataset inspection).  See [this tutorial](https://nbviewer.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A4-customdata-text_regression_with_extra_regressors.ipynb) for an example for how it is set.

Finally, if you just need to translate English to Spanish, you can use the [Translator](https://nbviewer.org/github/amaiya/ktrain/blob/master/examples/text/language_translation_example.ipynb#The-Translator-Class-for-Translating-to-and-from-Many-Languages) class in **ktrain**, which uses pre-fine-tuned models.

**Comment by amaiya** [comment]
Sorry, I misread part of your question.  The `TFDataset` class was really intended for classification and regression problems.  You may want to use the tf.Dataset API directly for seq2seq problems.
