### ISSUE TITLE
Assigning a tensorflow.dataset object as train_data in get_learner() 

### ISSUE THREAD

**Issue by irineosv** [amaiya/ktrain#44]
Hello Maiya, this more of a question, rather than an issue.
Am I able to assign tensorflow.dataset objects as the train_data in get_learner ?

**Comment by amaiya** [comment]
Good question. The short answer is not right now, but maybe later. 

 *ktrain* inspects datasets to make various decisions related to model configuration, training, etc.  When the dataset is the form of arrays or Keras data abstractions like `image.DirectoryIterator`, this is easy, but performing such inspections on tf.Datasets [seems more challenging](https://stackoverflow.com/questions/50737192/tf-data-dataset-how-to-get-the-dataset-size-number-of-elements-in-a-epoch).    TensorFlow datasets also behave strangely.  If you set the `batch_size` of an `image.DirectoryIterator`, it's still a `DirectoryIterator`.  With tf.Datasets, calling `batch` or `repeat` turns it into a new class which can no longer be inspected in the same way as before.


This will be revisited in future when investigating ways to better support custom data formats and models.  Thanks.
