### ISSUE TITLE
Text Extractor can't load PDF

### ISSUE THREAD

**Issue by akald** [amaiya/ktrain#444]
Hi when running 
```
text = TextExtractor().extract(r'C:\Downloads\downloaded_paper.pdf')
```
I receive the message
```
Error on  C:\Downloads\downloaded_paper.pdf
The command pdftotext 'C:\Downloads\downloaded_paper.pdf'  failed with exit code 127 -- stdout ---stderr
```

**Comment by amaiya** [comment]
Previous versions of **ktrain** used the **textract** package for text extraction, which uses `pdftotext`.  This works out-of-the-box on Linxux, but not on Windows.  It sounds like you don't have `pdftotext` installed on Windows in which case you need to install poppler for Windows.

However, the latest version of **ktrain** (v0.31.x just released) uses TIKA as the default, which is better suited for Windows, as only Java is needed.

So, you can either install `pdftotext` or upgrade **ktrain**.
