### ISSUE TITLE
Multiclass Regression using BERT Based models

### ISSUE THREAD

**Issue by VinayChaudhari1996** [amaiya/ktrain#447]
Hey @amaiya 

I am trying to solve a multi-class regression problem using ktrain. but I think ktrain only supports a single column as (target) dependent feature ,
how can I achieve the following results ktrain or using any other packages?

Eg:   
**Sentance                   |  positive   | Negative | Neutral** 
Today is a good day     | 80            | 9               | 11

**Training data :** Sentance Column (text) ["Today is a good day"]
**Output :**  Continuous values (int/flot)  [80,9,11]

Thanks

**Comment by amaiya** [comment]
Hello @VinayChaudhari1996 :  To do what you want, you can simply use a single column.  See [this example](https://huggingface.co/spentaur/yelp) that uses **ktrain** to predict YELP review scores between 1 and 5 (transformed to scale of -2 to +2, where 0 is neutral). If any questions, feel free to reply to this thread.

**Comment by VinayChaudhari1996** [comment]
Hi @amaiya ,
Actually my problem is about predicting continuous variables 

Eg :- 

Given sentence :-
Basically developers used Git and GitHub

**Comment by amaiya** [comment]
Hello: I understand your question now.  Multi-output regression isn't supported out of the box right now, unfortunately.  There would need to be some code changes to support this, since **ktrain** assumes a single scalar as the target for all regression problems.
