### ISSUE TITLE
valueError: connection error, when deploying distilbert model in lunix

### ISSUE THREAD

**Issue by rajnishrajput12** [amaiya/ktrain#448]
I trained my distilbert-uncased model for text classification on windows and then trying to deploy this model in Linux.
but getting connection error not sure why, because its our server and we cant open internet in it.
1. here is the code i used for training in windows--> code_wid.jpeg
![code_win](https://user-images.githubusercontent.com/43354631/168443718-633cf540-d94d-4509-9605-1e018e90fd81.jpeg)
   a.lib-versions-- window_version.jepg
![window_version](https://user-images.githubusercontent.com/43354631/168443724-1ad25e5b-8bf7-4578-93e8-0e4b7025667e.jpeg)
   b. files which got created in windows after calling predictor.save()
![window_files](https://user-images.githubusercontent.com/43354631/168443807-3fa10095-c0a1-4488-9246-58188dfa5d8c.jpeg)
  c. inside config file which got created after saving.
![config_windows](https://user-images.githubusercontent.com/43354631/168443959-036bda56-3227-48c4-8f0d-96c14df52b1e.jpeg)

2. here is the code i am trying in Linux
![linux_error](https://user-images.githubusercontent.com/43354631/168444186-c3b27932-2292-4d36-9f61-f9aa74ece33e.png)
  a. lib version linux--
![linux_version](https://user-images.githubusercontent.com/43354631/168444664-5ada71e4-1fb5-48cb-af73-f8d86a325bee.jpeg)

b. file which i placed in linux from windows.
 
![linux_model_files](https://user-images.githubusercontent.com/43354631/168444359-a170b4ed-c0fb-42fe-ad70-ffe9bc1551c6.jpeg)
c. inside linux config file
![config_linux](https://user-images.githubusercontent.com/43354631/168444533-5ec7a1e4-81f4-4417-b802-e1acdeee2ecd.PNG)

d. i also placed distilbert-uncased files in linux and same path is mentioned in linux_model config file 
![distil-bert-uncased](https://user-images.githubusercontent.com/43354631/168444522-53503552-ac7b-4bc6-b581-086fa36c1187.jpeg)

**Comment by amaiya** [comment]
Hello:  The version of **ktrain** you're using is very old.  Please upgrade to the latest version (v0.31), which includes many updates and fixes. If you're still seeing a problem after upgrading, please reply to this issue and we can look into it.

**Comment by rajnishrajput12** [comment]
i upgraded ktrain to 0.31.0, now i have ktrain==0.31.0, transformer==4.10.3, tensorflow==2.8.0,
![new_version](https://user-images.githubusercontent.com/43354631/168546220-d71af14f-2f71-4d1b-8119-7f00603bab34.jpeg)

now i am getting failed to load preproc file
![new_preproc_error](https://user-images.githubusercontent.com/43354631/168546233-b2afd12c-1205-47f9-973a-657b65a22750.jpeg)

I do see all .preproc..config and .h5 file in the above location.
![linux_model_files](https://user-images.githubusercontent.com/43354631/168546354-60ee3a17-0a58-47a3-9c9f-d5bb2333324a.jpeg)

**Comment by rajnishrajput12** [comment]
Thank you Amaiya,

i upgraded ktrain but now getting cant load tf_model.preproc file even
though its there.
detailed commnet :--
https://github.com/amaiya/ktrain/issues/448#issuecomment-1127352866

Thanks
Rajnish

**Comment by rajnishrajput12** [comment]
that's true i trained on ktrain 0.25.4. 
problem is in .preproc where it says disilbert-uncased path. if i edit this in linux and change to /folder/distilbert-base-uncased then it says couldn't load preproc i think while editing preproc gets corrupted in notepad.
![err_prep](https://user-images.githubusercontent.com/43354631/168624928-6a7f67c7-69fc-4661-ab71-1aef33264763.png)

is there anyway i can resolve this without retraining because it will take 12 days for me to train

**Comment by amaiya** [comment]
You can try your luck with these very old instructions from over a  year ago.

- **2021-03-10:**
  - ***ktrain*** **v0.26.x is released** and now supports `transformers>=4.0.0`.  
Note that, `transformers>=4.0.0` included a complete reogranization of the module's structure. This means that, if you saved a **transformers**-based `Predictor` (e.g., DistilBERT) in an older version of **ktrain** and **transformers**, you will need to manually edit the `tf_model.preproc` file before loading the `predictor` in the latest versions of **ktrain** and **transformers**.  
For instance, suppose you trained a DistilBERT model and saved the resultant predictor using an older version of **ktrain** with: `predictor.save('/tmp/my_predictor/')`.  After upgrading to the newest version of **ktrain**,  you will find that `ktrain.load_predictor('/tmp/my_predictor`) will throw an error unless you edit the file **/tmp/my_predictor/tf_model.preproc** to conform to the new **transformers** structure as follows:
    - change `transformers.configuration_distilbert` to `transformers.models.distilbert.configuration_distilbert`
    - change `transformers.modeling_tf_auto` to `transformers.models.auto.modeling_tf_auto`
    - change `transformers.tokenization_auto` to `transformers.models.auto.tokenization_auto`
  - If you're using PyTorch 1.8 or above with **ktrain**, you will need to upgrade to `ktrain>=0.26.0`. If you're using `ktrain<0.26.0`, then you will have to downgrade PyTorch with: `pip install torch==1.7.1`.

**Comment by rajnishrajput12** [comment]
Thank you Amaiya,

Two things here
1. Even if I keep all ktrain, transformer version in linux  same as windows
where it is working fine. I get connect error because model name not sure
how https is getting appended and thus it searches to download from
internet.
2. Manually I am trying to edit the. Preproc file but it's getting
corrupted and says can't load . Preproc either from post locsitont...

**Comment by amaiya** [comment]
If you use the latest version of **ktrain**, training a model in Windows and loading the trained predictor on Linux works perfectly  (just tested as sanity check with a distilbert model).  The HTTPS error is probably `transformers` trying to download the tokenizer files.  You can try manually downloading the tokenizers files into your predictor folder.  Like I said, this isn't a problem in the latest version of **ktrain**.
