### ISSUE TITLE
Getting an error while executing this code

### ISSUE THREAD

**Issue by man0007** [amaiya/ktrain#45]
(x_train, y_train), (x_test, y_test), preproc = text.texts_from_folder('C:\Users\anand.nataraj\Downloads\aclImdb', 
                                                                       maxlen=500, 
                                                                       preprocess_mode='bert',
                                                                       train_test_names=['train', 
                                                                                         'test'],
                                                                       classes=['pos', 'neg'])

ERROR:
======

File "<ipython-input-1-7dc071bdc9a5>", line 1
    (x_train, y_train), (x_test, y_test), preproc = text.texts_from_folder('C:\Users\anand.nataraj\Downloads\aclImdb',
                                                                          ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

Below is the dataset that I'm loading:
=========================
datset fil structure: http://prntscr.com/qng8k1

download link: https://ai.stanford.edu/~amaas/data/sentiment/

--------------------------------------------

please let me know the dataset and the file structure that i'm using is correct.

**Comment by amaiya** [comment]
I think the backslashes in your file path is causing the problem.  See [this stackoverflow post](https://stackoverflow.com/questions/37400974/unicode-error-unicodeescape-codec-cant-decode-bytes-in-position-2-3-trunca).  Try putting `r` before the file path string or change backslashes to forward slashes, as described in the post.
