### ISSUE TITLE
How to install ktrain from source ?

### ISSUE THREAD

**Issue by VinayChaudhari1996** [amaiya/ktrain#450]

**Comment by amaiya** [comment]
Hello:  The source archive for [0.31.2 is on PyPI](https://pypi.org/project/ktrain/0.31.2/#files).   You can install the archive using [these instructions](https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-from-local-archives), if that's what you're asking.

If you're having a particular problem with the normal `pip install ktrain`, then feel free to reply to this thread for further assistance.

**Comment by VinayChaudhari1996** [comment]
Hi @amaiya 
Actually, I am looking for single .whl file for OFFLINE local installation

**Comment by amaiya** [comment]
A `.whl` file will make the installation faster, and we can certainly make them available on PyPI.  But, if the goal is OFFLINE installation, then the instructions I provided previously should work.  Does that not work for you?  See also [these instructions](https://stackoverflow.com/questions/11091623/how-to-install-packages-offline) that work for installing any PyPI package offline.

**Comment by amaiya** [comment]
A `.whl` file for **ktrain** is [available on PyPI](https://pypi.org/project/ktrain/#files):
```python
pip install ktrain-0.31.2-py3-none-any.whl
```

**Comment by VinayChaudhari1996** [comment]
Hi @amaiya ,

It is not installeding offline.
![image](https://user-images.githubusercontent.com/42869040/174476359-060117ba-8643-4c41-a9c9-d29559c57020.png)

where the Internet is off on Kaggle :
![image](https://user-images.githubusercontent.com/42869040/174476382-2c8d9940-a057-4a83-a780-5820b6e7ca4d.png)


I guess there are some dependencies that required internet access.

So now how I can perform a **complete** offline installation?

Thanks

**Comment by amaiya** [comment]
Hello @VinayChaudhari1996 :  The way you install **ktrain** without an internet connection is exactly the same as any other Python package.  The `.whl` file only includes **ktrain**.  You'll need to download the other dependencies separately if there is no internet using the [instructions I posted perviously](https://stackoverflow.com/questions/11091623/how-to-install-packages-offline).  If you're using `transformers` models, you will also need to copy the model/tokenizer/config files for whatever model you're using over manually, as well, as indicated in this [FAQ](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-use-ktrain-without-an-internet-connection) entry.
