### ISSUE TITLE
Training a model on text and tabular data

### ISSUE THREAD

**Issue by AndrewNg** [amaiya/ktrain#451]
Hi there, I've used ktrain for several projects in the past and it's been super useful!

I have a binary classification problem that has both text, categorical, and numeric data. I would like to use a transformer to handle the text, something like an MLP to handle the other features after preprocessing, and concatenate the models together. I've seen https://github.com/amaiya/ktrain/issues/110 and this [tutorial](https://nbviewer.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A4-customdata-text_regression_with_extra_regressors.ipynb), but I don't believe that concatenating models in that way works for transformer models. I also saw https://github.com/amaiya/ktrain/issues/403 as a potential solution, but the example notebook given for concatenating models seems like it would get complex pretty quickly when there are multimodal features with large N.

One potential approach is to concatenate all the features together as text using separator token then passing that all to a transformer and that would work with ktrain out of the box, but that seems a bit janky especially with many features.

Is there something I'm missing that allows me to do this easily in ktrain today? And if not, is this use case something that might be added in the future?

Thank you for all your hard work!

**Comment by amaiya** [comment]
Hi @AndrewNg 

People usually just use concatenation in one form or another, and it wasn't quite clear to me why you thought it wouldn't work with transformers.  It's been shown to [work well with images](https://raw.githubusercontent.com/naity/image_tabular/master/pics/model.png).  With a `transformers` model like BERT, you'd end up with a vector with 768 dimensions and concatenate it with the tabular data and train the model end-to-end.  

An alternative way is to simply generate a document embedding (dense vector) of the document and use those as static features in a standard tabular model.   These would just be standard static word vectors, though. You could use sentence-transformers for this or use the more simplistic, built-in  `TransformerEmbedding` in **ktrain**:
```python
In [1]: from ktrain.text import TransformerEmbedding

In [2]: te = TransformerEmbedding('bert-base-cased')

In [3]: te.embed('George Washington went to Washington .', word_level=False).shape

Out[3]: (1, 768)
```


If you have other suggestions, then feel free to let me know.  I agree that this would be useful to include in a more automated way in future. There aren't immediate, concrete plans to add something like this right now, but PRs for this would be welcome.
