### ISSUE TITLE
Problem when training model

### ISSUE THREAD

**Issue by evangeliazve** [amaiya/ktrain#452]
Hello,

I am facing the following issue when trying to apply ktrain model : 
![image](https://user-images.githubusercontent.com/19437590/176417690-f74896ef-ebbf-48d1-a19c-567548a6ad1c.png)

Do you have any idea on what would be the source of the problem ?

Thank you in advance for your help and support 

Best

**Comment by amaiya** [comment]
Hello,

If you are importing keras directly in  your code, you need to have the TensorFlow package installed. Once TensorFlow is installed, import Keras via `from tensorflow import keras`.  Make sure you are not importing `keras` independently.

If that doesn't work, what version of TensorFlow are you using?  Are you able to reproduce this problem on Google Colab?
