### ISSUE TITLE
request for a ktrain version fully supported by Pytorch without TensorFlow dependencies

### ISSUE THREAD

**Issue by nicolashernandez** [amaiya/ktrain#453]
Currently training is only possible with TensorFlow (as seen at the bottom of the main README) but most of the use cases are mainly supported by PyTorch. The request is for a ktrain version fully supported by Pytorch (including training neural network) and with no TensorFlow dependencies.

**Comment by amaiya** [comment]
Hello: The only reason that **ktrain** supports so many PyTorch use cases is that `transformers` has historically provided better and faster support for PyTorch models than for Tensorflow models.  Even now, certain use cases are not even possible using TensorFlow in `transformers`.   If your goal is to deploy in an environment with only PyTorch installed and without TensorFlow, the recommended approach is as follows:

1. Train your model in **ktrain** using TensorFlow Keras
2. [Convert  model](https://nbviewer.org/github/amaiya/ktrain/blob/develop/examples/text/ktrain-ONNX-TFLite-examples.ipynb) to ONNX
3. In deployment, you can run inferences using your trained model with only ONNX (no TensorFlow) and run other pretrained models in **ktrain** (e.g., language translation) using only PyTorch.  No TensorFlow is needed on the deployment machine.

Simultaneiously supporting neural network training in two different frameworks is a lot of work.  Typically, libraries that are migrated to support PyTorch from TensorFlow cease supporting TensorFlow all together.  As of right now, **ktrain** will  continue to stick with TensorFlow Keras for neural network training.

**Comment by nicolashernandez** [comment]
Thank you for your comment. I indeed understand the effort to maintain a concurrent version for training. In my specific context, due to hosting restrictions, developing (and training) with TensorFlow was not an easy thing and we are more "PyTorch" people in my lab. Anyway ktrain is a really nice project and we appreciate the documentation.
