### ISSUE TITLE
Flops calculation.

### ISSUE THREAD

**Issue by Moshiur-Rahman-Faisal** [amaiya/ktrain#454]
Is there any built in library for Ktrain to calculate flops specially for BERT models?

**Comment by amaiya** [comment]
Hello:  There is nothing built into ktrain that will calculate Flops, but there are [other open-source libraries](https://pypi.org/project/keras-flops/) that you might be able to use with tf.keras models to do this.

**Comment by Moshiur-Rahman-Faisal** [comment]
Tried the keras-flops but it doesnt works with Ktrain transformer model.

**Comment by amaiya** [comment]
This is a question you should direct to the Hugging Face discussion forums.

Based on the [Support section](https://github.com/tokusumi/keras-flops#support), it does not support `transformers` models in general (with or without **ktrain**).
