### ISSUE TITLE
Training gets stuck on M1 Max

### ISSUE THREAD

**Issue by dpicca** [amaiya/ktrain#457]
Hi 

I am trying to do the training but the process gets stuck at this point:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/25099133/184601757-352e2155-2bfe-474c-8fff-0cfa8e8a6831.png">

On the contrary, on colab everything works correctly 

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/25099133/184602004-e0312deb-cd73-409d-96bb-c9194c32e180.png">

This is my configuration

>Apple silicon M1 Max
>Python 3.10
>tensorflow-estimator             2.9.0
>tensorflow-macos                 2.9.2
>tensorflow-metal                 0.5.0
>keras                            2.9.0`

are there any explanations and solutions?
Many thanks for your help

**Comment by amaiya** [comment]
Does the problem still occur if you use Python 3.9 (or the same version of Python as on Colab)?

**Comment by dpicca** [comment]
You hit the nail on the head. Actually downgrading to python 3.8, it works. I will try with version 3.9 but certainly, there is a problem with version 3.10

Thanks for the suggestion
