### ISSUE TITLE
Wanted to understand on what basis the parameters (max_features, ngram_range, max_length) are set

### ISSUE THREAD

**Issue by man0007** [amaiya/ktrain#46]
HI Guys,

Thanks for the contribution!

I would kindly request you to help me in understanding on what basis the parameter (max_features, ngram_range, and max_length) values are set in the fasttext model (https://github.com/amaiya/ktrain/blob/master/examples/text/IMDb-fasttext.ipynb).

Moreover, is the max_length has any limit in fasttext model, similar to the bert?

Thanks,
Anand.

**Comment by amaiya** [comment]
Hi @man0007 

The `ngram_range` feature is to add bigrams/trigrams at the end of sequences for Bag-of-Word-type models like `fasttext`, `nbsvm`, `logreg`.  It is from the [Keras fasttext example](https://keras.io/examples/imdb_fasttext/).  `max_features` is supplied to as `num_words` argument to Tokenizer in `tf.keras`.  The `maxlen` parameter is supplied as argument to `pad_sequences` in `tf..keras`.  The next release of *ktrain* will print the 95th and 99th percentiles of sequence lengths to inform setting `maxlen` value.   There is not a hard limit on sequence length for non-transformer models.
