### ISSUE TITLE
threshold moving in ktrain

### ISSUE THREAD

**Issue by semprepisfo** [amaiya/ktrain#462]
hello, is there any way to apply threshold moving in ktrain on predictions, it would help greatly on umbalanced data but I cannot find examples in documentation, can you provide me with one example:
here's tensorflow example from a course:

sample_example = ['Why is it that European food is so terrible', 'Are you ashamed of being Indian?']
test_data = tf.data.Dataset.from_tensor_slices((sample_example, [1]*len(sample_example)))
test_data = test_data.map(to_feature_map).batch(1)
preds = model.predict(test_data)
threshold = 0.4
['Insincere' if pred >= threshold else 'Sincere' for pred in preds]

or 

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state = 2)
clf.fit(X_train,y_train)
y_pred = (clf.predict_proba(X_test)[:,1] >= 0.3).astype(bool)

any help with a working code for ktrain would be greatly appreciated, I am trying to predict sentences in column and output to a file
but I would also need a threshold, I tried to apply this threshold and the prediction itself works but its capped at 0.5, ie the threshold does not work:

preds = predictor.predict(df['Text'].values.tolist())
threshold = 0.9
['Neutral' if pred >= threshold else 'Negative' for pred in preds]
df['Text'] = preds

on the whole Internet I have not seen 1 person using threshold moving in ktrain that would share a code

**Comment by amaiya** [comment]
Please see [this FAQ entry](https://github.com/amaiya/ktrain/blob/master/FAQ.md#how-do-i-get-the-predicted-class-probabilities-of-a-model).  Getting prediction probabilities is also discussed in the [text classification tutorial](https://nbviewer.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-04-text-classification.ipynb)
