### ISSUE TITLE
Support MarkupLM

### ISSUE THREAD

**Issue by sisygoboom** [amaiya/ktrain#463]
A new [LM from Microsoft](https://huggingface.co/microsoft/markuplm-base) for understanding markup documents has a different structure to existing LM implementations.

**Comment by amaiya** [comment]
Hello:  What task are you trying to solve with MarkupLM?

**Comment by sisygoboom** [comment]
Text classification/regression. I have a markup & markdown-rich corpus & don't want to miss formatting features

**Comment by amaiya** [comment]
Hi @sisygoboom:   **ktrain** is currently pinned to a lower version of `transformers` which doesn't seem to support this model.  In the future, we will upgrade to a newer version of **transformers** at which time MarkLM models will work.  I will keep this issue open and update it when the upgrade is complete.
