### ISSUE TITLE
'NoneType' object is not callable

### ISSUE THREAD

**Issue by vianseto** [amaiya/ktrain#465]
Hello, I'm trying to train with my own dataset and facing this error, can anyone help me?

![image](https://user-images.githubusercontent.com/103388165/200777176-6eb0cc98-636e-444a-9a54-aadd7f0bd7d3.png)

**Comment by amaiya** [comment]
Please provide the full code example and example of what your dataset looks like.

**Comment by vianseto** [comment]
> Please provide the full code example and example of what your dataset looks like.

here the google colab notebook https://colab.research.google.com/drive/1hi3V_iB8-39VqF5vlyCAXKTxfemq2Vv7?usp=sharing

**Comment by amaiya** [comment]
I'm assuming there is something wrong with this model you selected, as **ktrain** works just fine on your dataset using other models:

```python
!gdown 1zD3MM4DqJ87xeyvru4ApMcKzLnjHCgpu
!gdown 11UycJpe5o3Shh0lBd_rAukGn4eq4X1GL

import pandas as pd
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

import ktrain
from ktrain import text
MODEL_NAME ='distilbert-base-multilingual-cased'
t = text.Transformer(MODEL_NAME, maxlen=500)
trn = t.preprocess_train(list(train.text), list(train.label))
val = t.preprocess_test(list(test.text), list(test.label))
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
learner.fit_onecycle(5e-5, 1)

# OUTPUT:
# begin training using onecycle policy with max lr of 5e-05...
# 247/247 [==============================] - 53s 178ms/step - loss: 2.6586 - accuracy: 0.5027 - val_loss: 1.3838 - val_accuracy: 0.8777
```

**Comment by vianseto** [comment]
> I'm assuming there is something wrong with this model you selected, as **ktrain** works just fine on your dataset using other models:
> 
> ```python
> !gdown 1zD3MM4DqJ87xeyvru4ApMcKzLnjHCgpu
> !gdown 11UycJpe5o3Shh0lBd_rAukGn4eq4X1GL
> 
> import pandas as pd
> train = pd.read_csv("train.csv")
> test = pd.read_csv("test.csv")
> 
> import ktrain
> from ktrain import text
> MODEL_NAME ='distilbert-base-multilingual-cased'
> t = text.Transformer(MODEL_NAME, maxlen=500)
> trn = t.preprocess_train(list(train.text), list(train.label))
> val = t.preprocess_test(list(test.text), list(test.label))
> model = t.get_classifier()
> learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
> learner.fit_onecycle(5e-5, 1)
> 
> # OUTPUT:
> # begin training using onecycle policy with max lr of 5e-05...
> # 247/247 [==============================] - 53s 178ms/step - loss: 2.6586 - accuracy: 0.5027 - val_loss: 1.3838 - val_accuracy: 0.8777
> ```

thank you so much, yesterday I'm try with other model and it works
