### ISSUE TITLE
What does t.preprocess_train include?

### ISSUE THREAD

**Issue by WAEDwaed** [amaiya/ktrain#466]
What does data processing include in trn = t.preprocess_train(x_train, y_train)? does include tokenizer?
I want to do BERT tokenizer Does this need to be add to code ?
or is it included in the t.preprocess_train?

**Comment by amaiya** [comment]
The tokenizer is loaded and applied automatically based on the model name you supplied to `Transformer`.

**Comment by WAEDwaed** [comment]
Thank you for the reply
