### ISSUE TITLE
Train Model With NLI Task

### ISSUE THREAD

**Issue by vianseto** [amaiya/ktrain#467]
I have a question, is it possible to train model on NLI task with ktrain?
or just need to combine 2 sequence and add cls and sep token (BERT) and train like usually...

**Comment by vianseto** [comment]
> I have a question, is it possible to train model on NLI task with ktrain? or just need to combine 2 sequence and add cls and sep token (BERT) and train like usually...

sorry for the stupid question, i'm new to this field

**Comment by amaiya** [comment]
Hi @vianseto :  It's a good question that others may have also   Yes, you train an NLI model on two sequences separated by SEP and/or fine-tune an existing NLI model from hugging face model hub  (both of which can be viewed as 3-class text classification, I believe).

**Comment by vianseto** [comment]
> Hi @vianseto : It's a good question that others may have also Yes, you train an NLI model on two sequences separated by SEP and/or fine-tune an existing NLI model from hugging face model hub (both of which can be viewed as 3-class text classification, I believe).

thank you very much for the answer sir!
