### ISSUE TITLE
keras_bert's tokenizer breaks some unicode chars while lowercasing

### ISSUE THREAD

**Issue by anndop** [amaiya/ktrain#47]
Hello! I found out that lowercasing procedure within Tokenizer._tokenize in keras_bert (keras_bert/tokenizer.py line 103: `text = unicodedata.normalize('NFD', text))` breaks some national symbols existed in bert vocab. I.e. russian char й got translated to и. This leads to breaking some russian words existed in vocabulary to wrong syllables.
This can be turned off by passing cased=True parameter to Tokenizer class. So I suggest adding to BERTPreprocessor 
`__init__` function parameter "cased" and pass it to BERT_Tokenizer:

`--- preprocessor.py     2020-01-17 20:55:01.005621433 +0300`
`+++ preprocessor.py.new 2020-01-17 20:57:09.279613894 +0300`
`@@ -586,3 +586,3 @@`
`     def init(self, maxlen, max_features, classes=[], `
`-                lang='en', ngram_range=1, multilabel=False):`
`+                lang='en', ngram_range=1, multilabel=False, cased=False):`
` `
`@@ -597,3 +597,3 @@`
`                 token_dict[token] = len(token_dict)`
`-        tokenizer = BERT_Tokenizer(token_dict)`
`+        tokenizer = BERT_Tokenizer(token_dict, cased=cased)`
`         self.tok = tokenizer`

and to `text_from_array` in data.py to pass it further to BERTPreprocessor:

`--- data.py     2020-01-17 21:15:23.258549536 +0300`
`+++ data.py.new 2020-01-17 21:14:42.000000000 +0300`
`@@ -262,3 +262,3 @@`
`                    random_state=None,`
`-                   verbose=1):`
`+                   verbose=1, cased=False):`
`     """`
`@@ -310,3 +310,3 @@`
`                            classes = class_names,`
`-                           lang=lang, ngram_range=ngram_range)`
`+                           lang=lang, ngram_range=ngram_range, cased=cased)`
`     trn = preproc.preprocess_train(x_train, y_train, verbose=verbose)`

**Comment by amaiya** [comment]
Thanks for posting issue.  As of v0.8.x, *ktrain* includes the ability to use BERT via Hugging Face `transofmers`.    **Does this issue also occur when you use the Hugging Face `Transformer` interface within *ktrain*?**

Here is code for running Multilingual BERT through the Transformer interface in *ktrain*:

```
import ktrain
from ktrain import text
MODEL_NAME = 'bert-base-multilingual-cased'
t = text.Transformer(MODEL_NAME, maxlen=500,  
                     classes=train_b.target_names)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
learner.fit_onecycle(3e-5, 1)
```

**Comment by anndop** [comment]
Hello! I apologize for the late reply. I tried version 0.10.1. This problem is solved 
in BertTokenizer from hugging face transformers. Tnank you very much!

**Comment by amaiya** [comment]
Thanks @anndop
