### ISSUE TITLE
multi features column

### ISSUE THREAD

**Issue by WAEDwaed** [amaiya/ktrain#472]
I am trying to apply a bert model in dataset that contains eight features in addition to the text feature  but model only accepts the text feature alone and does not accept the features together . how can make bert model accepted many features column?

**Comment by amaiya** [comment]
You can construct a custom model for this  See [this tutorial](https://nbviewer.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A4-customdata-text_regression_with_extra_regressors.ipynb).  Note that the tutorial uses a vanilla Keras text classification model, but you can extend it for use with BERT.
