### ISSUE TITLE
How to perform a text classification using a custom model

### ISSUE THREAD

**Issue by Thiziri-Hafir** [amaiya/ktrain#481]
I've been working on text binary classification using a very domain specific data. I've been following the steps shown in the  [tutorials](https://github.com/amaiya/ktrain/tree/master/tutorials) using `distilbert-base-uncased'`. I've tried to test other mutilingual models  but for some reason that doesn't work.

 I also want to test a custom model that I built from scratch but I don't know how to do that.

Does anyone know how to do that ? 

Thank you for the help!

**Comment by amaiya** [comment]
At the end of the same tutorial you just mentioned, there is information on how to do this.  You'll need to use the `Transformer` API in **ktrain**, as described in detail [here](https://github.com/amaiya/ktrain/blob/master/tutorials/tutorial-A3-hugging_face_transformers.ipynb).

```python
# load text data
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
from sklearn.datasets import fetch_20newsgroups
train_b = fetch_20newsgroups(subset='train', categories=categories, shuffle=True)
test_b = fetch_20newsgroups(subset='test',categories=categories, shuffle=True)
(x_train, y_train) = (train_b.data, train_b.target)
(x_test, y_test) = (test_b.data, test_b.target)

# build, train, and validate model (Transformer is wrapper around transformers library)
import ktrain
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased' # replace with any transformers model you want
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
learner.fit_onecycle(5e-5, 4)
learner.validate(class_names=t.get_classes()) # class_names must be string values
```

**Comment by Thiziri-Hafir** [comment]
u for the quick answer.  Indeed, I have already tried this by adjusting it to my case (my pre-trained model is in a local folder) but it did not work.

**Comment by amaiya** [comment]
Please provide example code to reproduce the problem or tell me the model you're trying to load if you want further assistance.
