### ISSUE TITLE
Using Bert for new language without any pretrained model

### ISSUE THREAD

**Issue by mnitin73** [amaiya/ktrain#49]
Can I use ktrain to create a model using bert architecture, but without any pretrained data, using only my own corpus of text. Thanks

**Comment by amaiya** [comment]
You can take a look at [this Microsoft article](https://azure.microsoft.com/en-us/blog/microsoft-makes-it-easier-to-build-popular-language-representation-model-bert-at-large-scale/) and GitHub project on the subject.
