### ISSUE TITLE
Saving a lr_plot() file rather than viewing?

### ISSUE THREAD

**Issue by Logan-Pratico** [amaiya/ktrain#490]
Is there a way to save the lr_plot() image that shows up rather than view it directly? I am running a model on a remote Linux server and have no way to view the plot and interpret the learning rate unless I save it and transfer it to a local computer.

**Comment by amaiya** [comment]
Hi:  You should be able to call `lr_plot` with with `return_fig=True` and save the matplotlib figure that is returned (e.g., as a PNG file).
```python
# example
fig = learner.lr_plot(return_fig=True)
fig.savefig('/tmp/plot.png')
```
