### ISSUE TITLE
but what is about generating question for given text ?

### ISSUE THREAD

**Issue by Sandy4321** [amaiya/ktrain#493]
but what is about generating question for given text 
meaning txet is given then python code sould geneate many questions ?

**Comment by amaiya** [comment]
Hello @Sandy4321 : Here is how you can do it:

```python
from ktrain.text.generative_ai import GenerativeAI
model = GenerativeAI() # supply device="cpu" if you do not have a GPU with at least 16GB of GPU memory
prompt = """Generate a question about the following text. 
After a war lasting 20 years, following the decision taken first by President Trump and then by President Biden to withdraw American troops, Kabul, the capital of Afghanistan, fell within a few hours to the Taliban, without resistance."""
print(model.execute(prompt))   

# OUTPUT:
# What effect did the decision to withdraw American troops from Afghanistan have on the city of Kabul?
```

See the [GenerativeAI notebook](https://nbviewer.org/github/amaiya/ktrain/blob/master/examples/text/generative_ai_example.ipynb) for more information.

**Comment by amaiya** [comment]
Generating one question per word doesn't really make sense, but to generate more than one question you can simply change prompt:
```python
 prompt = """Generate two questions about the following text.
After a war lasting 20 years, following the decision taken first by President Trump and then by President Biden to withdraw American troops, Kabul, the capital of Afghanistan, fell within a few hours to the Taliban, without resistance."""
```

**Comment by Sandy4321** [comment]
thanks for naswer
but still if we need one question for each word in sentence ?

**Comment by amaiya** [comment]
Replace the number in the prompt with whatever you want.

**Comment by Sandy4321** [comment]
but it will be many questoins to whole sentence , but not one questoin for each word in sentence ?

**Comment by Sandy4321** [comment]
prompt2 = """Generate 123 questions about the following text.
After a war lasting 20 years, following the decision taken first by President Trump and then by President Biden to withdraw American troops, Kabul, the capital of Afghanistan, fell within a few hours to the Taliban, without resistance."""
print(model.execute(prompt2))
1. What was the cause of the 20-year war between the United States and Afghanistan?
2. How did the decision to withdraw American troops affect the situation in Kabul?
3. What effects did the fall of Kabul have on the American military strategy?
4. What was the Taliban's demand for the city prior to the attack?
5. How did the American soldiers in Kabul react to the sudden change in leadership?
6. What measures have been taken to secure the city since the withdrawal of American troops?
7. What is the current state of security in Kabul?
8. How has the situation in Afghanistan changed since the 2020 election? 
9. What impact will the withdrawal of American troops have on the long-term security situation in Afghanistan?
10. What are the prospects for a continued American military presence in the country?

**Comment by Sandy4321** [comment]
prompt2 = """Generate hundred questions about the following text.
After a war lasting 20 years, following the decision taken first by President Trump and then by President Biden to withdraw American troops, Kabul, the capital of Afghanistan, fell within a few hours to the Taliban, without resistance."""
prompt2
'Generate hundred questions about the following text.\nAfter a war lasting 20 years, following the decision taken first by President Trump and then by President Biden to withdraw American troops, Kabul, the capital of Afghanistan, fell within a few hours to the Taliban, without resistance.'
print(model.execute(prompt2))
What was the cause of the war?
What were the effects of the decision to withdraw American troops?
How quickly did Kabul fall?
What strategies were employed to weaken the Taliban?
What will be the consequences of the new American policy?
What are the implications for the future of the country?

**Comment by Sandy4321** [comment]
only 10 questoin max we can get???

**Comment by Sandy4321** [comment]
only 10 questoins max we can get?
why?

**Comment by amaiya** [comment]
Perhaps because of [max_new_tokens](https://amaiya.github.io/ktrain/text/generative_ai/core.html#ktrain.text.generative_ai.core.GenerativeAI), mentioned both in the example notebook and documentation.

**Comment by Sandy4321** [comment]
great
then how to get more than 10?
I see
max_new_tokens: int = 512
![image](https://github.com/amaiya/ktrain/assets/11426119/84d10d37-c92b-41a9-8456-56b3a1516903)
