### ISSUE TITLE
detected language is english in a code-mixed data

### ISSUE THREAD

**Issue by mcormick123** [amaiya/ktrain#495]
Hello, i've been reading the closed issues here but i can't seem to find what i'm looking for. 

I'm using `bert-base-multilingual-uncased` via text.Transformer since it includes the languages present in my dataset. But whenever i run and preprocess it, it detects language English only,  I've read some closed issue here that it was a bug? but it has been fixed., and `model.summary()` prints `Model: "tf_bert_for_sequence_classification_16"` shouldn't it be like 'multi_cased_xxx'?

Apologies, i'm really new in this and I want to understand everything as much as I can. Also, is the maxlen, the tokenized maximum length? Thank you so much!

**Comment by amaiya** [comment]
Hello: What you're describing is normal output.  The `text.Transformer` makes a best guess as what the primary language of the text is and will not detect every language buried in the training set.  For `Transformer` models, the detected language is used by `predictor.explain` to tokenize text differently if it is detected as Chinese.    The output of `model.summary` is also normal and will display the same thing regardless of the language of the model.
