### ISSUE TITLE
Installed tk event loop hook.

### ISSUE THREAD

**Issue by amaiya** [amaiya/ktrain#496]
Printed with importing.

**Comment by tokioshima** [comment]
Hello @amaiya,

I'm new in this new environment of coding, python, etc... and I don't understand your solution of "installed tk event loop hook" error. I encounter the same and I would like to apply your solution!

Thanks in advance!!

**Comment by amaiya** [comment]
"Installed tk event loop hook" is just something informational coming from matplotlib.  So, it's harmless and no solution is necessary.
