### ISSUE TITLE
Integration with tensorboard

### ISSUE THREAD

**Issue by sathish331977** [amaiya/ktrain#5]
Is the integration with tensorboard  supported? I tried the callbacks in autofit(), ran into function object has no attribute fetch_callbacks error

**Comment by amaiya** [comment]
Yes, this should already be supported, since *ktrain* is a lightweight wrapper around Keras.  I tested on Ubuntu 18.04 with Keras 2.2.4 and TensorFlow 1.10.1 and it works:

```
import keras
tbCallBack = keras.callbacks.TensorBoard(log_dir='./Graph', histogram_freq=0, write_graph=True, write_images=True)
learner.autofit(2e-5, 1, callbacks=[tbCallBack])
```
