### ISSUE TITLE
deploying to huggingface

### ISSUE THREAD

**Issue by gaurishhs** [amaiya/ktrain#503]
hi! thanks for this awesome library!

i'm trying to deploy a model to huggingface it uses `bert_multi_cased`. Huggingface needs a config.json file how can i get that?

I tried `predictor.model.to_json()` and that seems to output layers

**Comment by amaiya** [comment]
Hi @gaurishhs 

The `config.json` file is part of the set of `bert-multilingual-cased` model files that was downloaded from Hugging Face. when you created the model.  It is available [here](https://huggingface.co/bert-base-multilingual-cased/tree/main).

It is also automatically saved to wherever you save a predictor for the model you're deploying:

```python
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names)
trn = t.preprocess_train(x_train, y_train)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=None, batch_size=6)
learner.fit_onecycle(5e-5, 1)
predictor = ktrain.get_predictor(model, t)
predictor.save('/tmp/somepredictor')
!ls /tmp/somepredictor/
```
```shell
#  OUTPUT:
config.json  special_tokens_map.json  tf_model.h5  tf_model.preproc  tokenizer_config.json  tokenizer.json  vocab.txt
```

**Comment by gaurishhs** [comment]
i'm actually using `model = text.text_classifier('bert', trn , preproc=preproc)` not transformers

**Comment by gaurishhs** [comment]
@amaiya should text_classifier work with config.json? I tried migrating to Transformers 

```
MODEL_NAME = 'bert-base-multilingual-uncased'

t = text.Transformer(MODEL_NAME, maxlen=360, class_names=['0','1'])
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
```

and i'm getting this error

TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

**Comment by amaiya** [comment]
Hello:

Please follow [this example](https://github.com/amaiya/ktrain/blob/master/examples/text/20newsgroup-distilbert.ipynb) and ensure that your data is in the same or similar input format.  You can also refer to the tutorial notebook on text classification for supported input formats.

If you still get an error, please share a reproducible example of the problem that I can run on Google Colab.

Supported input formats (from tutorial notebook) are:
```python
# my_training_data.csv
TEXT,LABEL
I like this movie,positive
I hate this movie,negative

**Comment by gaurishhs** [comment]
Hi! i have the label column as an integer instead of string so i tried to map those integers as strings and then tried but i get that same error.

https://colab.research.google.com/drive/10n1PWHmZv-IeUsTaE7DcKIMk6x8xjwsM?usp=sharing

**Comment by gaurishhs** [comment]
Also it seems to detect the language as zh-cn whereas it contains multiple languages (just that chinese is a bit more than others) does that somehow matter? 

![image](https://github.com/amaiya/ktrain/assets/78847111/a860eb34-a7fb-4178-9ed7-b9f4c9bddebc)

**Comment by amaiya** [comment]
As the error message indicates, the input must be a list of strings.  The issue is that your dataset as `nan` values in it:

```python
In [13]: for s in x_test:
    ...:     if not isinstance(s, str):
    ...:         print(s)
    ...:         break
    ...:
nan
```

**Comment by gaurishhs** [comment]
That seems to be the issue! I have fixed it i had another question. I tried running the code on Colab and preprocess_train seems to consume all the available memory (12GB) is this expected?

**Comment by amaiya** [comment]
Great. Last time I checked, [this colab notebook](https://colab.research.google.com/drive/1AH3fkKiEqBpVpO5ua00scp7zcHs5IDLK) trained with no problem.  You might consider examining the differences between this notebook and your notebook.

**Comment by gaurishhs** [comment]
Could it be to due the dataset size difference? The dataset used here is just 14mb

**Comment by amaiya** [comment]
Hmmm - not really sure how much RAM is required for a dataset of this size.   

I will say that the BERT model has already been pretrained on a massive amount of data (transfer learning).  As a result, you typically don't need to fine-tune the pretrained model on millions of labeled examples to get good accuracy. Thus, this might be a waste of your resources.   You  might try training on a small sample of your dataset to see what kind of accuracy you get and iteratively increase the sample size until you're happy with the results or the results don't improve much.

**Comment by gaurishhs** [comment]
I've tried an AWS Sagemaker Notebook instance with 32GB of ram, 8v CPUs and even that seems to run out of ram. I had tried to train it on a small sample and the total accuracy it had was 0.8

**Comment by amaiya** [comment]
All that `preprocess*` does is make repeated calls to `encode_plus` from `transformers`.  For your entire dataset, this appears to take up 45GB of memory.   There are more memory efficient way to do this using `tf.Dataset` by perhaps subclassing `TransformerDataset`, if you really want to train on the entire dataset. This is not currently implemented in the library.

**Comment by gaurishhs** [comment]
Alright! Thank you so much for your help.

**Comment by amaiya** [comment]
I forgot to mention that one  trick some have used on large datasets is to split up their dataset into parts and run preprocessing and training each part individually.  This way, you can train on an entire large dataset using as little or as much memory as you want by specifying the size of each part. You can also potentially preprocess and train each part during entirely different sessions (e.g., days/weeks apart).

#### Example: Training on Large Dataset by Splitting Training Set Into Parts
```python
# load text data
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
from sklearn.datasets import fetch_20newsgroups
train_b = fetch_20newsgroups(subset='train', categories=categories, shuffle=True)
(x_train, y_train) = (train_b.data, train_b.target)

# split training set into parts (optionally store on disk and read in only one at a time)
part1_x = x_train[:1000]
part1_y = y_train[:1000]
part2_x = x_train[1000:]
part2_y = y_train[1000:]

# preprocess/train on first part
import ktrain
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names)
trn = t.preprocess_train(part1_x, part1_y)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=None, batch_size=6)
learner.fit_onecycle(5e-5, 1)

# save partially-trained model
predictor = ktrain.get_predictor(model, t)
predictor.save('/tmp/part1_pred')

# to resume training during different session you can
# read back in partially-trained model 
predictor = ktrain.load_predictor('/tmp/part1_pred')
model = predictor.model
t = predictor.preproc # Preprocessor object

# preprocess/train on second part
# Since we save the predictor, this can potentially occur in/on a different session/day
trn = t.preprocess_train(part2_x, part2_y)
learner = ktrain.get_learner(model, train_data=trn, val_data=None, batch_size=6)
learner.fit_onecycle(5e-5, 1)

# learner.model is now fully trained on entire dataset
```

**Comment by gaurishhs** [comment]
Yeah, that seems a better option. I even tried a 192GB ram instance and this kinda scares me off lol

![image](https://github.com/amaiya/ktrain/assets/78847111/62030fb9-a1eb-427d-bbae-525798e26760)
