### ISSUE TITLE
Bug with ktrain.text.translation

### ISSUE THREAD

**Issue by johngcolson** [amaiya/ktrain#508]
Since ktrain version == 33.0, the Translator object from ktrain.text.translation no longer works with pretrained models from HuggingFace. The latest version to work correctly was ktrain==0.32.3

Here is an example with an Helsinki-NLP model for the translation of English into French.
![image](https://github.com/amaiya/ktrain/assets/124262161/ec31246d-08fc-4cdb-a238-2f8d02bd1358)
![image](https://github.com/amaiya/ktrain/assets/124262161/a275cc55-c41e-4d27-997c-646f46a4a144)

Same code with ktrain version 0.32.3 yields an acceptable translation

![image](https://github.com/amaiya/ktrain/assets/124262161/01bd9450-d527-4014-9713-8f3d5c7dd318)
![image](https://github.com/amaiya/ktrain/assets/124262161/86a142ad-5e77-4d6d-b180-a8eb21fcef0a)

Please note that in all versions of ktrain after 0.32.3, the translation is always wrong (long list of repeated words) when loading a pretrained model from HuggingFace. However, the translation is correct when a fine-tuned model is loaded locally.

**Comment by amaiya** [comment]
Hello @johngcolson 

I just installed the latest version of ktrain (0.37.6) on Google Colab and everything works.  [Here](https://colab.research.google.com/drive/1zhzGsAUqVgscHhKkESvGgM-Cpp1dMsmZ?usp=sharing) is the Google Colab notebook, if you want to take a look.

Can you please provide the full code for a reproducible example of the problem you're seeing on Google Colab?

**Comment by johngcolson** [comment]
Hi, thank you, here is a link to the [notebook](https://colab.research.google.com/drive/1bygC-XStmCYCyE_Jd-5FGGlPicQmhmU5?usp=sharing)

Strangely enough, this code only works with ktrain==0.32.3 or older. The only difference I can see with your code, is that I have used a bigger Helsinki-NLP corpus.

Best,
John

**Comment by amaiya** [comment]
Please provide public access to your notebook so I can view it.

**Comment by johngcolson** [comment]
Sorry, here is a link with public access: [here](https://colab.research.google.com/drive/1bygC-XStmCYCyE_Jd-5FGGlPicQmhmU5?usp=sharing)
The model that only works with ktrain 0.32.3 or older is 'Helsinki-NLP/opus-mt-tc-big-en-fr'

**Comment by amaiya** [comment]
Hi @johngcolson 

This appears to be an issue with the model, not **ktrain**, as it happens when using the latest version of **transformers** directly:

```python
from transformers import MarianMTModel, MarianTokenizer

model_name = "Helsinki-NLP/opus-mt-tc-big-en-fr"
tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)
translated = model.generate(**tokenizer('It is fine weather today.', return_tensors="pt", padding=True))

for t in translated:
    print( tokenizer.decode(t, skip_special_tokens=True) )

# OUTOUT
# biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère biosphère

```

I'm not exactly sure why it's working in older versions of **ktrain**, but the workaround is to use a different model like: `Helsinki-NLP/opus-mt-en-fr`.  

The only recent change made in `ktrain==0.37.1` was to supply default arguments to `num_beams` and `early_stopping`.  Early versions of **ktrain** supplied None which only worked in older versions of transformers.

**Comment by johngcolson** [comment]
Hi, thank you anyway because I can now see where the  problem lies. As you
suggested, it has to do with the model but more precisely with an
incompatibility between that model at the latest transformer version. The
bug you show indeed occurs with transformer 4.32.0, which is default on
Google colab. On my kaggle account, however, the default transformer is
4.26.1 and there is no bug

[image: image.png]
Yes, using another model would be fine, but that one is the
state-of-the-art for free translation models English-French, and it is much
better than the smaller one. No problem, anyway, I'll stick to an older
transformer version or an older ktrain. Thanks to ktrain, students in
computational linguistics can have an access to less cryptic notebooks.
Thanks again,
John

Le ven. 25 août 2023 à 15:55, Arun S. Maiya ***@***.***> a
écrit :

**Comment by amaiya** [comment]
Interesting - thanks for letting me know.  Cheers, - Arun
