### ISSUE TITLE
 texts_from_df throws error AttributeError: 'NoneType' object has no attribute 'utils'

### ISSUE THREAD

**Issue by daniel-satria** [amaiya/ktrain#509]
Hello

I got a multi-class sentiment analysis task on AWS SageMaker, when running below code : 

`(X_train, y_train), (X_test, y_test), preprocess = text.texts_from_df(train_df=df, text_column='data',
                                                                      label_columns='sentimen', 
                                                                      maxlen=512, 
                                                                      preprocess_mode='bert')`

I got an error as follow : 

> --------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[136], line 1
> ----> 1 (X_train, y_train), (X_test, y_test), preprocess = text.texts_from_df(train_df=df_binary, text_column='data', label_columns='sentimen', maxlen=512, preprocess_mode='bert')
> 
> File ~/anaconda3/envs/python3/lib/python3.10/site-packages/ktrain/text/data.py:308, in texts_from_df(train_df, text_column, label_columns, val_df, max_features, maxlen, val_pct, ngram_range, preprocess_mode, lang, is_regression, random_state, verbose)
>     306 # transform labels
>     307 ytransdf = U.YTransformDataFrame(label_columns, is_regression=is_regression)
> --> 308 t_df = ytransdf.apply_train(train_df)
>     309 v_df = ytransdf.apply_test(val_df)
>     310 class_names = ytransdf.get_classes()
> 
> File ~/anaconda3/envs/python3/lib/python3.10/site-packages/ktrain/utils.py:924, in YTransformDataFrame.apply_train(self, df)
>     923 def apply_train(self, df):
> --> 924     return self.apply(df, train=True)
> 
> File ~/anaconda3/envs/python3/lib/python3.10/site-packages/ktrain/utils.py:897, in YTransformDataFrame.apply(self, df, train)
>     894         self.set_classes(class_names)
>     896 # transform targets
> --> 897 targets = super().apply(
>     898     targets, train=train
>     899 )  # self.c (new label_columns) may be modified here
>     900 targets = (
>     901     targets if len(targets.shape) > 1 else np.expand_dims(targets, 1)
>     902 )  # since self.label_columns is list
>     904 # modify DataFrame
> 
> File ~/anaconda3/envs/python3/lib/python3.10/site-packages/ktrain/utils.py:777, in YTransform.apply(self, targets, train)
>     772     if train and (len(set(targets)) != int(max(targets) + 1)):
>     773         raise ValueError(
>     774             "len(set(targets) is %s but max(targets)+1 is  %s"
>     775             % (len(set(targets)), int(max(targets) + 1))
>     776         )
> --> 777     targets = keras.utils.to_categorical(
>     778         targets, num_classes=len(self.get_classes())
>     779     )
>     780 if train:
>     781     self.train_called = True
> 
> AttributeError: 'NoneType' object has no attribute 'utils'

Could someone please tell me how I can fix it?
Thank you!

**Comment by kristopher-smith** [comment]
The `AttributeError: 'NoneType' object has no attribute 'utils'` error has the most recent traceback of `--> 777 targets = keras.utils.to_categorical(` This suggests that the `keras` object is `NoneType`. Did you import keras?

**Comment by daniel-satria** [comment]
> The `AttributeError: 'NoneType' object has no attribute 'utils'` error has the most recent traceback of `--> 777 targets = keras.utils.to_categorical(` This suggests that the `keras` object is `NoneType`. Did you install keras? See: [### Requirements](https://github.com/amaiya/ktrain/blob/a3dcf08fce9e30b8c837cf97c5610e7b09f8360c/README.md?plain=1#L425)

I've imported the Keras package, even check the version, but still can't manage to run it.
However, I try to create new notebook and re-run the same command and it works.
I wonder if there's any error in their conda environments.

Anyway, thankyou for replying!
