### ISSUE TITLE
Is there a method to convert ktrain predictor to onnx model (optimized and quantized) without using transformers PyTorch dependencies

### ISSUE THREAD

**Issue by cbjrobertson** [amaiya/ktrain#514]
I'm building an automl solution which allows users to train text classification models using `ktrain` (love the library, by the way, thanks!). Models are then saved using onnx and user can run inference on the `onnx` models. However, the only way I can figure out to convert `KTrain` models to `onnx` is using `transformers` `pytorch` dependencies, which adds huge overhead to the application (especially since I ALSO need `tensorflow` installed to train with). 

The code I'm using right now to convert `ktrain` models to `onnx` is:

```
from transformers.convert_graph_to_onnx import convert, optimize, quantize
import transformers
from pathlib import Path


def save_transformer(predictor):
    #save
    predictor_path = "path/to/predictor"
    tmp_dir_fp = "path/to/tmp/folder"
    
    predictor.save(predictor_path)
    
    # paths
    pt_path = tmp_dir_fp / "tf_model_pt"
    pt_onnx_path = tmp_dir_fp / "tf_model_pt." / 'onnx_model.onnx'

    # convert to ONNX
    transformers.AutoModelForSequenceClassification.from_pretrained(predictor_path, 
                                                                    from_tf=True).save_pretrained(pt_path)
    convert(framework='pt', 
            model=pt_path,
            output=Path(pt_onnx_path), 
            opset=11, 
            tokenizer="distilroberta-base",
            pipeline_name="text-classification")
    
    pt_onnx_quantized_path = quantize(optimize(Path(pt_onnx_path)))
```

In this example, the `predictor` argument is a [ktrain predictor class](https://amaiya.github.io/ktrain/text/predictor.html).

Is their a way to achieve the same results as above without needing the heavy pytorch dependencies?

**Comment by cbjrobertson** [comment]
Fixed link.

**Comment by amaiya** [comment]
Hi @cbjrobertson :  Your project sounds interesting.  Have you seen [this example notebook](https://nbviewer.org/github/amaiya/ktrain/blob/develop/examples/text/ktrain-ONNX-TFLite-examples.ipynb)?  While the example does use PyTorch, there's a note in the notebook about going directly from the TensorFlow `transformers` model to ONNX using the `predictor.export_model_to_onnx(onnx_model_path)` method (without PyTorch).   Under the hood, it uses [tf2onnx](https://github.com/onnx/tensorflow-onnx), which you can also try directly.
