### ISSUE TITLE
Pandas 1.0

### ISSUE THREAD

**Issue by Bidek56** [amaiya/ktrain#52]
Is there a reason you are checking for Pandas < 1.0 in setup.py?
With Pandas 1.0 it throws an error: 
`ERROR: ktrain 0.9.0 has requirement pandas<1.0, but you'll have pandas 1.0.0 which is incompatible.`
Thanks

**Comment by amaiya** [comment]
It's because of [this pandas 1.0 bug](https://github.com/pandas-dev/pandas/issues/31441) that is still open as of today and causes NER in *ktrain* to break.

**Comment by Bidek56** [comment]
The Pandas ticket was closed, do you think we can move to Pandas 1.0+? Thx

**Comment by amaiya** [comment]
Thanks - the pandas requirement was changed to `>=1.0.1` in develop and looks like things work.  Changes will be included in next release. Thanks for letting us know.
