### ISSUE TITLE
Memory Leak with predictor.predict_proba in ktrain

### ISSUE THREAD

**Issue by RamziRahli** [amaiya/ktrain#521]
I have a memory increment when calling ktrain's predictor.predict_proba(lines) method in a batch processing loop. Memory is not released even after batch processing, which leads to an increase in memory. 

I solved the problem by manually forcing memory release: 
```
from tensorflow.keras import backend as K

for lines in batchs:
   predictor.predict_proba(lines)
   K.clear_session()
```
but I'm looking for a softer way than that!
Thanks

**Comment by amaiya** [comment]
Hello,

I'm not able to reproduce this issue and you haven't provided enough information to investigate. ( It's not clear what model you're using, for example.)  I ran `predict_proba` in a loop like you for a DistilBERT model and did not see any memory increases. 

If you take a look at the prediction code, it doesn't seem that there is anything in the prediction code that would cause memory increments. The fact that `K.clear_session` works suggests that perhaps it is an issue in Tensorflow;.

Note that `predictor.predict_proba` is already making predictions in batches (controlled by `predictor.batch_size` parameter).  So, if you're dataset is already in memory, there is no need to batch your self, as you can just supply the entire list to `predict/predict_proba`.  If you are reading from disk, you might try supplying larger batches to `predict/predict_proba`.  Each call to `predict/predict_proba` converts your dataset to a `tf.Dataset`, which may be causing the memory increases. I don't know a solution to this other than to either minimize the calls to `predict/predict_proba` by supplying a larger number of examples or calling `K.clear_session`, as you have done.  The former is preferred.

If you need further assistance, please post a reproducible example on  Google Colab of the issue and share a link to it in this thread.

**Comment by amaiya** [comment]
The issue you're seeing may be related to the use of `tf.Datasets` within the `predictor` for Hugging Face models.   The next release of **ktrain** will include a change that may resolve the issue you're seeing (so you no longer have to call `K.clear_session`).  I will update this issue when this next version is released.
