### ISSUE TITLE
Could not interpret optimizer identifier

### ISSUE THREAD

**Issue by Nesarul-Hoque** [amaiya/ktrain#523]
I followed Tutorial A3: [Text Classification with Hugging Face Transformers]. I tried to implement the 'bert-base-multilingual-uncased' model from HuggingFace. When using the code, model = t_mod.get_classifier(), it generates an error message. This code was working perfectly some days ago. However, now it produces the following error:

**Error**
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

[<ipython-input-21-9ce4d9ec2ad7>](https://localhost:8080/#) in <cell line: 1>()
----> 1 model = t_mod.get_classifier()

3 frames

[/usr/local/lib/python3.10/dist-packages/tf_keras/src/optimizers/__init__.py](https://localhost:8080/#) in get(identifier, **kwargs)
    332         )
    333     else:
--> 334         raise ValueError(
    335             f"Could not interpret optimizer identifier: {identifier}"
    336         )

ValueError: Could not interpret optimizer identifier: <keras.src.optimizers.legacy.adam.Adam object at 0x7b2c22cb13c0>

**Comment by Nesarul-Hoque** [comment]
I have solved this issue by installing the tf_keras python package for using Keras 2.

**Comment by amaiya** [comment]
What pip command did you specifically use for tf_keras?

**Comment by chocolatewafer** [comment]
I have a similar issue, on google colab.
### code
`predictor=ktrain.load_predictor("/content/gdrive/My Drive/Minor/pred2.0")`
### Error
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-af7371f59490> in <cell line: 1>()
----> 1 predictor=ktrain.load_predictor("/content/gdrive/My Drive/Minor/pred2.0")

6 frames
/usr/local/lib/python3.10/dist-packages/tf_keras/src/optimizers/__init__.py in get(identifier, **kwargs)
    332         )
    333     else:
--> 334         raise ValueError(
    335             f"Could not interpret optimizer identifier: {identifier}"
    336         )

ValueError: Could not interpret optimizer identifier: <keras.src.optimizers.legacy.adam.Adam object at 0x7e19eddddbd0>

**Comment by amaiya** [comment]
I'm not able to reproduce locally either - only occurs on Google Colab.  It seems to be some sort of issue with either Google Colab or `transformers`.  The problem goes away when downgrading **transformers** to  `transformers<4.38`.    

The latest version of **ktrain** (`ktrain>=0.41.1`) now temporarily pins to `transformers=4.37.2`, so that this issue doesn't occur on Google Colab.

**Comment by chocolatewafer** [comment]
Yes! It does work after downgrading transformers to transformers<4.38. No idea what the issue was though.
