### ISSUE TITLE
Overfitting Issue

### ISSUE THREAD

**Issue by Nesarul-Hoque** [amaiya/ktrain#524]
During the implementation of the BanglaBERT (csebuetnlp/banglabert) transformer model, the overfitting issue comes just after the second epoch. Without the early stopping method, any other techniques are available to handle overfitting issues effectively when using the Ktrain package for implementing transformer models.

**Comment by amaiya** [comment]
See [`Learner.set_weight_decay`](https://amaiya.github.io/ktrain/core.html#ktrain.core.Learner.set_weight_decay).  More generally, as a wrapper to `tf.keras`, there is nothing preventing you from using any method to prevent overfitting in `tf.keras`.
