### ISSUE TITLE
Interpret optimizeter issue

### ISSUE THREAD

**Issue by tayyabawan786** [amaiya/ktrain#529]
**i face error ValueError: Could not interpret optimizer identifier: <keras.src.optimizers.legacy.adam.Adam object at 0x78ac23a95ab0>**

i have updated transformers also before 1 month it dont have any error now it show me this error when i run this code could you please guide me on this
MODEL_NAME = 'google-bert/bert-base-uncased'

t = text.Transformer(MODEL_NAME, maxlen=400, classes=np.array([0,1]))
trn = t.preprocess_train(np.array(X_train),np.array(y_train))
val = t.preprocess_test(np.array(X_val), np.array(y_val))
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=12)

**Comment by amaiya** [comment]
What versions of **ktrain** and **TensorFlow** are you using?

**Comment by tayyabawan786** [comment]
i have solved it by using this code
!pip install tf-keras
import os
os.environ['TF_USE_LEGACY_KERAS'] = "True"

**Comment by tahlilsiam** [comment]
Can you tell me what's the reason of this optimizer interpretation issue?
