### ISSUE TITLE
language preprocessing huggings face transformers

### ISSUE THREAD

**Issue by Alexookah** [amaiya/ktrain#53]
Your last release seems to fix my previous issue https://github.com/amaiya/ktrain/issues/51

However now that i just upgraded to the latest version, it seems i am getting this error:

`
train_data = t.preprocess_train(x_train, y_train)
`
```
preprocessor.py in detect_lang(texts, sample_size)
    335             continue
    336     if len(lst) == 0:
--> 337         raise Exception('could not detect language in random sample of %s docs.'  % (sample_size))
    338     return max(set(lst), key=lst.count)
    339 

```
Exception: could not detect language in random sample of 32 docs.

**Comment by amaiya** [comment]
Are you supplying a list to `preprocess_train`?  Or, is it a column from from pandas dataframe? If the latter, can you try converting to list with `.values` before feeding to `preprocess_train` and let me know outcome?

**Comment by Alexookah** [comment]
@amaiya 
oh yes, in the previous version i was supplying the dataframe without .values.
Now it needs .values, and it shows :
`preprocessing train...
language: el
train sequence lengths:
	mean : 69
	95percentile : 169
	99percentile : 290`

looks like its recognizing any language now? nice

**Comment by amaiya** [comment]
Thanks
