### ISSUE TITLE
new intel ultra cpu's NPU

### ISSUE THREAD

**Issue by GoPlayers** [amaiya/ktrain#535]
Hi, Does Ktrain can use new intel ultra CPU's NPU?

**Comment by amaiya** [comment]
Hi:  I'm not familiar with the device, but it really depends on whether TensorFlow (PyTorch) can support it.  You might checkout this [reddit thread on the topic](https://www.reddit.com/r/CUDA/comments/1ax74tt/if_the_intel_core_ultra_is_equipped_with_a_neural/).

**Comment by GoPlayers** [comment]
I read. My labtops NPU stranger than GPU as Geekbench AI benchmark.
