### ISSUE TITLE
preprocess mode when using roberta model?

### ISSUE THREAD

**Issue by igormis** [amaiya/ktrain#54]
I used the library for multi-classification task with bert model and everything went smooth. However, when I want to use the distilbert model, the 'bert' is not allowed as preprocess mode, which mode should I use?

**Comment by amaiya** [comment]
There are two ways to access BERT-like models.  To use Roberta, you'll need to use the `Transformer` API in *ktrain* as described in [this blog post](https://towardsdatascience.com/text-classification-with-hugging-face-transformers-in-tensorflow-2-without-tears-ee50e4f3e7ed).

To use DistlBert, you can either use the `Transformer` API as mentioned above or use the `text_classifier` API as shown in [this example notebook](https://github.com/amaiya/ktrain/blob/master/examples/text/20newsgroup-distilbert.ipynb). You'll need to specify `preprocess_mode='distilbert' in the `texts_from*` function.

**Comment by igormis** [comment]
perfect, tnx

**Comment by igormis** [comment]
I am using the Transformer API in ktrain and it works for RoBERTa, however the following error rises when using xlnet-large
`TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [int32, int64] that don't all match.`

**Comment by amaiya** [comment]
This is an issue with the Hugging Face transformers library, not *ktrain*.  You can read [this blog post on the Transformer interface in ktrain](https://towardsdatascience.com/text-classification-with-hugging-face-transformers-in-tensorflow-2-without-tears-ee50e4f3e7ed) for more details on the XLNet issue including a possible fix.

**Comment by amaiya** [comment]
After looking into this, I think this may be a bug in *ktrain* after all.  Issue #56 has been re-opened for this.

**Comment by amaiya** [comment]
This is fixed in v0.9.2 of *ktrain*.  Verified on `xlnet-base-cased`.  

Also, as of a couple of hours ago, Hugging Face fixed the issue with Multilingual DistilBert, so this should now work, as well.
