### ISSUE TITLE
How to use images_from_array with different shape of images? 

### ISSUE THREAD

**Issue by yonatanbitton** [amaiya/ktrain#58]
Hello. 

Your examples include: 
```
(trn, val, preproc) = vis.images_from_folder(
                         datadir='data/dogscats',
                         data_aug=data_aug,
                         train_test_names=['train', 'valid'], 
                         target_size=(224,224), color_mode='rgb')
```

I have a X_train that is composed of images with different shapes. 
I'm trying to use `images_from_array`: (I don't want to use `images_from_directory` because I have too many classes.

```
(train_data), (val_data), preproc = vision.images_from_array(x_train=X_train_orig,
                                                                     y_train=y_train_encoded,
                                                                     validation_data=(X_valid_orig, y_valid_encoded),
                                                                     data_aug=vision.get_data_aug(horizontal_flip=True),
                                                                     )
```

But I receieve `ValueError: setting an array element with a sequence.`

I'm trying to reshape them to the same size but i'm not sure it's the right way to do it.

I wonder if there is a way which is consistent with the model. For example if i'm using ResNet, it will use the resizing of ResNet with the same interpolation, etc.

How can I solve it? 

Is there some parameter that I can pass to `images_from_array` or to `data_aug`?

Thanks

**Comment by amaiya** [comment]
You could try storing your class labels in a CSV and using `images_from_csv`.  The `target_size` variable will resize your images automatically.  The `images_from_array` function does not support resizing. See [this post](https://stackoverflow.com/questions/41758385/resizing-images-in-keras-imagedatagenerator-flow-methods?rq=1)for more details/solutions.

See [this post](https://www.pyimagesearch.com/2019/06/24/change-input-shape-dimensions-for-fine-tuning-with-keras/) for a deep dive into image-resizing with transfer learning.
