### ISSUE TITLE
ktrain.load_predictor failed ! 

### ISSUE THREAD

**Issue by 3egg** [amaiya/ktrain#6]
You can find the detail code in there. 
 from keras_bert.bert import gelu_tensorflow
can not load  gelu_tensorflow
TensorFlow version ==1.14.0
https://colab.research.google.com/drive/160FUEpwcElZhouGiyJJjROdWvivhQkIQ

**Comment by amaiya** [comment]
Thank you for reporting this issue.  A fix will be released soon.  In the meantime, a quick workaround is to temporarily downgrade the keras_bert package:  `pip3 install keras_bert==0.71.0`.   (You may have to retrain and resave your model.)

**Comment by 3egg** [comment]
OK, Thanks, BTW, I run the code that I mentioned before. In my computer(i7-8650u+16g ram) without GPU.  It needs about 3 hours per echo, how to speed it up?

**Comment by amaiya** [comment]
A fix for this has been released in *ktrain* v0.3.0.

In regards to your question, BERT is a large model and  isn't really intended to be trained on CPU.  If training on a CPU, you might try simpler/faster models on CPU like fasttext, logreg, nbsvm, etc.  You could also try freezing some of the earlier layers as in transfer learning in image classification, but I haven't really tried this.
