### ISSUE TITLE
Getting error: when using distilBERT BaseCollectiveExecutor: Out of range

### ISSUE THREAD

**Issue by soujanyav** [amaiya/ktrain#65]
```
W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Out of range: End of sequence
	 [[{{node IteratorGetNext}}]]
```

This error is thrown after training.

Is this related to this ticket?
https://github.com/tensorflow/tensorflow/issues/31509

quote

> This is fixed with latest version of tf nightly 2.0 build '2.0.0-dev20190906' . Thanks!
> Replace tf.optmizer with tf.keras.optimizer on line 64
> 
> optimizer = tf.keras.optimizers.Adam(learning_rate=0.005, amsgrad=True)
> 

unquote

**Comment by amaiya** [comment]
This appears to be some sort of [open TensorFlow issue](https://github.com/tensorflow/tensorflow/issues/32817) that started appearing when we modified the `Transformer` API to internally use tf.Datasets created using `from_generator`.  It doesn't  seem to affect training or validation and appears to be more of a warning.
