### ISSUE TITLE
Error when using ktrain.text.texts_from_df

### ISSUE THREAD

**Issue by yangliu2** [amaiya/ktrain#66]
I'm trying to make a text classification model. I have a csv file in the format of:
```
category, transcript
category_n, <some text>
```
(if you have a method that directly deal with csv files in this format, please let me know.)
I read the csv file using pandas and convert the category label to one-hot-encoding columns. 
Using the texts_from_df to read the dataframe, I got this error. Maybe I'm using it incorrectly, so let me know. Thanks!
```
In [25]: bert_data = txt.texts_from_df(concat_df, text_column='transcript', label_columns=label, maxlen=40)
language: en
Word Counts: 2944
Nrows: 14811
14811 train sequences
train sequence lengths:
	mean : 13
	95percentile : 27
	99percentile : 36
x_train shape: (14811,40)
y_train shape: (14811, 21)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-6e164984d428> in <module>
----> 1 bert_data = txt.texts_from_df(concat_df, text_column='transcript', label_columns=label, maxlen=40)

~/anaconda3/envs/transformer/lib/python3.6/site-packages/ktrain/text/data.py in texts_from_df(train_df, text_column, label_columns, val_df, max_features, maxlen, val_pct, ngram_range, preprocess_mode, lang, random_state, verbose)
    254                            classes = label_columns,
    255                            lang=lang, ngram_range=ngram_range)
--> 256     trn = preproc.preprocess_train(x_train, y_train, verbose=verbose)
    257     val = preproc.preprocess_test(x_test,  y_test, verbose=verbose)
    258     return (trn, val, preproc)

~/anaconda3/envs/transformer/lib/python3.6/site-packages/ktrain/text/preprocessor.py in preprocess_train(self, train_text, y_train, verbose)
    529         # return
    530         result =  (x_train, y_train)
--> 531         self.set_multilabel(result, 'train')
    532         return result
    533

~/anaconda3/envs/transformer/lib/python3.6/site-packages/ktrain/text/preprocessor.py in set_multilabel(self, data, mode)
    377
    378     def set_multilabel(self, data, mode):
--> 379         if mode == 'train' and self.get_classes():
    380             self.multilabel = U.is_multilabel(data)
    381

~/anaconda3/envs/transformer/lib/python3.6/site-packages/pandas/core/indexes/base.py in __nonzero__(self)
   2148     def __nonzero__(self):
   2149         raise ValueError(
-> 2150             f"The truth value of a {type(self).__name__} is ambiguous. "
   2151             "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
   2152         )

ValueError: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

Feels like the `y_train` in `texts_from_df` expected single dimension encoding like [0,1,2] rather than one-hot-encoding like [[1,0,0], [0,1,0],[0,0,1]] format. This other tutorial seems to be working. But it's from a previous version. https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A3-hugging_face_transformers.ipynb

**Comment by amaiya** [comment]
If you type, `help(txt.texts_from_df)`, the docstring for the function will appear, which states:
```
Loads text data from Pandas dataframe file. Class labels are assumed to be  one-hot-encoded arrays representing classes:
- classification (a single one in each array): [[1,0,0], [0,1,0]]]
 - multi-label classification (one more ones in each array): [[1,1,0], [0,1,1]]
```
Both  `texts_from_df` and `texts_from_csv` assume the labels are 1-hot-encoded (or multi-hot-encoded for multilabel problems), so you'll need to 1-hot-encode the labels yourself and create a column for each label [as shown in the tutorials/examples](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/examples/text/ArabicHotelReviews-nbsvm.ipynb).

If you'd like *ktrain* to 1-hot-encode your labels for you, please use `texts_from_array` which supports a wider range of label formats.:
```texts_from_array(concat_df['transcript'].values, concat_df['category'].values, ...```

See [this Colab notebook](https://colab.research.google.com/drive/1AH3fkKiEqBpVpO5ua00scp7zcHs5IDLK) for how `texts_from_array` works.
