### ISSUE TITLE
Is it possible to load biobert with ktrain?

### ISSUE THREAD

**Issue by Shane-Neeley** [amaiya/ktrain#68]
Is it possible to load this one with text.Transformer?

https://huggingface.co/adamlin/NCBI_BERT_pubmed_mimic_uncased_base_transformers

`t = text.Transformer(MODEL_NAME, maxlen=500, classes=train_b.target_names)`

**Comment by amaiya** [comment]
Happy to look into this.  But, have you verified this model can be loaded directly using TensorFlow and the `transformers` library?    If so, can you please post the steps?

For example, this doesn't seem to work for me using the latest version of `transformers`:

```python
tokenizer = AutoTokenizer.from_pretrained("adamlin/NCBI_BERT_pubmed_mimic_uncased_base_transformers")

model = TFAutoModel.from_pretrained("adamlin/NCBI_BERT_pubmed_mimic_uncased_base_transformers")
```

**Comment by amaiya** [comment]
v0.10.0 of *ktrain* (just released) includes support for community-uploaded models like BioBERT:

```python
import ktrain
from ktrain import text
MODEL_NAME = 'monologg/biobert_v1.1_pubmed'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=label_list)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
learner.fit_onecycle(3e-5, 1)
```
