### ISSUE TITLE
How to import text for BERT / Language model

### ISSUE THREAD

**Issue by christophschuhmann** [amaiya/ktrain#69]
I want to use the texts_from_folder function to import and preprocess text data to finetune a BERT model:

![image](https://user-images.githubusercontent.com/22318853/75524858-0c901580-5a0f-11ea-8c4a-d308140c98e9.png)

But I don't know in what kinda form the data should be in the folders. 
Should each folder provide the data for the according class in txt files? Or a csv? What kinda seperators should seperate the data for each example? Or should each example be in a seperate file?

Could you give show me an example?

:-)

**Comment by talhaanwarch** [comment]
You can have one csv file, containing all of your data. 
Read that csv file using pandas 

split it to train and val set

then you can run the following code
```
import ktrain
from ktrain import text
MODEL_NAME = 'bert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=100,classes=[0,1])
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_val, y_val)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
```

**Comment by amaiya** [comment]
@christophschuhmann If using `texts_from_folder`, each document in a folder is simply a `.txt` file containing the text of the document (an entire document of paragraphs and sentences, a single sentence, or a text snippet).  See [here](https://github.com/amaiya/ktrain/tree/master/ktrain/tests/text_data/text_folder/train/pos) for an example.

Also, as @talhaanwarch said, if using the [Transformer API](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A3-hugging_face_transformers.ipynb) in *ktrain*, you can just load your data into arrays and go from there.

There is also `texts_from_csv` and `texts_from_df` functions that you can use.  For these functions, the current version of *ktrain* assumes the CSV contains a column for text in addition to one column for each label (i.e., labels are assumed to be 1-hot-encoded already):

```
TEXT,negative,positive
I like this movie,0,1
I hate this movie,1,0
```
In the next release  of *ktrain* (v0.10.0 to be released soon), `texts_from_csv` and `texts_from_df` will support a single label column:
```
TEXT,LABEL
I like this movie,positive
I hate this movie,negative
```
