### ISSUE TITLE
AttributeError on 'BERTPreprocessor'

### ISSUE THREAD

**Issue by waterflyer** [amaiya/ktrain#7]
Hey @amaiya 

There is no issue for loading and preprocess the data using texts_from_csv and texts_from_df, but after this step, I wanted to load the pretrained BERT model and pass the preproc to it then I hit this issue which is 

AttributeError: 'BERTPreprocessor' object has no attribute 'max_features'

I did set up the max_features in the load data methods and I have tested the return preproc object and there is no 'max_features' attribute.

**Comment by amaiya** [comment]
Thank you for reporting this issue.  This should now be fixed.  Please upgrade *ktrain* to v0.3.1.

**Comment by waterflyer** [comment]
Thank you for the upgrade.
