### ISSUE TITLE
Multiple GPU support using the HuggingFace Transformers

### ISSUE THREAD

**Issue by Niekvdplas** [amaiya/ktrain#78]
Hello Amaiya,

First of all what an awesome repo this is, it is very useful. I've read your other reply regarding multi-GPU support however I can't get it to work maybe because I mirror the wrong part. I've tried many options but I don't know what I'm doing wrong. Here is my code.

import os
os.environ["CUDA_VISIBLE_DEVICES"]="0,1,2,3,4";
import tensorflow as tf
from tensorflow import keras
from keras.layers import Embedding
import re
import numpy as np
import pandas as pd
from ktrain import text
import ktrain
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split

mirrored_strategy = tf.distribute.MirroredStrategy()
print ('Number of devices: {}'.format(mirrored_strategy.num_replicas_in_sync))
with mirrored_strategy.scope():
    def get_model():
        return text.Transformer(MODEL_NAME, maxlen=200, class_names=categories)

fields= ['CategoryShort','IssueDescription']
data=pd.read_csv('./test.csv', usecols=fields)

data = data[pd.notnull(data['IssueDescription'])]

pd.set_option('max_colwidth', 1000)
data['IssueDescription'] = data['IssueDescription'].str.lower()
data['IssueDescription'] = data['IssueDescription'].str.replace('x', '')
data['IssueDescription'] = data['IssueDescription'].str.replace('{', '')
data['IssueDescription'] = data['IssueDescription'].str.replace('}', '')
data['IssueDescription'] = data['IssueDescription'].str.replace('/', '')
data = data[:35000]

categories = data['CategoryShort'].unique().tolist()

MODEL_NAME = 'bert-base-uncased'

X = data['IssueDescription']
y = data['CategoryShort']
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

x_train, x_test, y_train, y_test = x_train.to_numpy(), x_test.to_numpy(), y_train.to_numpy(), y_test.to_numpy()

model = get_model()

model.lang = 'en'

count = 0
for x in y_train:
    y_train[count] = categories.index(x)
    count += 1

count = 0
for x in y_test:
    y_test[count] = categories.index(x)
    count += 1

trn = model.preprocess_train(x_train, y_train)
val = model.preprocess_test(x_test, y_test)

classifier = model.get_classifier()

learner = ktrain.get_learner(classifier, train_data=trn, val_data=val, batch_size=4)

learner.fit_onecycle(2e-5, 2)

predictor = ktrain.get_predictor(learner.model, t)

predictor.save('./multiclass pred')

res = predictor.predict("Didn't receive notice of right to dispute")

print("This complaint is classified as: " + res)

**Comment by Niekvdplas** [comment]
I think i figured it partially out. The model should be in the scope which in this case would be **The transformer**.get_classifier(). However, with this working it will hang on the epoch 1/2 and not show a progressbar of any progress for that matter.

This is the changed code

import os
os.environ["CUDA_VISIBLE_DEVICES"]="0,1,2,3,4";
import tensorflow as tf
from tensorflow import keras
from keras.layers import Embedding
import re
import numpy as np
import pandas as pd
from ktrain import text
import ktrain
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split

fields= ['CategoryShort','IssueDescription']
data=pd.read_csv('./test.csv', usecols=fields)

data = data[pd.notnull(data['IssueDescription'])]

pd.set_option('max_colwidth', 1000)
data['IssueDescription'] = data['IssueDescription'].str.lower()
data['IssueDescription'] = data['IssueDescription'].str.replace('x', '')
data['IssueDescription'] = data['IssueDescription'].str.replace('{', '')
data['IssueDescription'] = data['IssueDescription'].str.replace('}', '')
data['IssueDescription'] = data['IssueDescription'].str.replace('/', '')
data = data[:3500]

categories = data['CategoryShort'].unique().tolist()

MODEL_NAME = 'bert-base-uncased'

mirrored_strategy = tf.distribute.MirroredStrategy()

X = data['IssueDescription']
y = data['CategoryShort']
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

x_train, x_test, y_train, y_test = x_train.to_numpy(), x_test.to_numpy(), y_train.to_numpy(), y_test.to_numpy()

t = text.Transformer(MODEL_NAME, maxlen=200, class_names=categories)

t.lang = 'en'

count = 0
for x in y_train:
    y_train[count] = categories.index(x)
    count += 1

count = 0
for x in y_test:
    y_test[count] = categories.index(x)
    count += 1

trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)

with mirrored_strategy.scope():
     def get_model(t):
          return t.get_classifier()

    model = get_model(t) # model here is still in the scope.

#Back out of the scope()
learner = ktrain.get_learner(classifier, train_data=trn, val_data=val, batch_size=4)

learner.fit_onecycle(2e-5, 2)

predictor = ktrain.get_predictor(learner.model, t)

predictor.save('./multiclass pred')

res = predictor.predict("Didn't receive notice of right to dispute")

print("This complaint is classified as: " + res)

**Comment by amaiya** [comment]
When I place `t.get_classifier()` within the MirrordStrategy scope, multiple GPUs are used but validation throws an error. I'm not sure why since it works with non-Transformer models. Perhaps, it is a bug in TF2 or transformers library?  Or, maybe other things need to be in scope.  Not sure.  

In any case, a workaround is to omit the validation data from `get_learner` and validate at end of the multi-gpu training after reloading the model from disk:

```python
# use two GPUs to train
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID";
os.environ["CUDA_VISIBLE_DEVICES"]="0,1";  

# load text data
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
from sklearn.datasets import fetch_20newsgroups
train_b = fetch_20newsgroups(subset='train', categories=categories, shuffle=True)
test_b = fetch_20newsgroups(subset='test',categories=categories, shuffle=True)
(x_train, y_train) = (train_b.data, train_b.target)
(x_test, y_test) = (test_b.data, test_b.target)

# build, train, and validate model
import tensorflow as tf
mirrored_strategy = tf.distribute.MirroredStrategy()
import ktrain
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
with mirrored_strategy.scope():
    model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, batch_size=6)
learner.fit_onecycle(5e-5, 2)
learner.save_model('/tmp/my_model')
learner.load_model('/tmp/my_model', preproc=t)
learner.validate(val_data=val, class_names=t.get_classes())
```

Two GPUs used during training of the DistilBERT model:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.64       Driver Version: 430.64       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN V             Off  | 00000000:21:00.0 Off |                  N/A |
| 42%   59C    P2   163W / 250W |  11684MiB / 12066MiB |     84%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN V             Off  | 00000000:31:00.0 Off |                  N/A |
| 33%   49C    P2   132W / 250W |  11684MiB / 12066MiB |     84%      Default |
+-------------------------------+----------------------+----------------------+
```

Output of `learner.validate` at the end:
```
                        precision    recall  f1-score   support

           alt.atheism       0.93      0.93      0.93       319
         comp.graphics       0.98      0.95      0.96       389
               sci.med       0.96      0.97      0.97       396
soc.religion.christian       0.97      0.97      0.97       398

              accuracy                           0.96      1502
             macro avg       0.96      0.96      0.96      1502
          weighted avg       0.96      0.96      0.96      1502
```

**Comment by Niekvdplas** [comment]
It is true that it will work for 2 GPU's, however I am currently trying to get it working on 5 GPU's (which might be a bit overkill, but hey). It seems like it is forever stuck on allocating memory or something at epoch 1/2.

![Screenshot from 2020-03-09 13-46-19](https://user-images.githubusercontent.com/25798694/76214244-9d839f80-620c-11ea-9a7e-c1a969b68f7f.png)

**Comment by amaiya** [comment]
If it works for 2 GPUs but not for 5 GPUs, then it sounds like some sort of issue with TensorFlow and/or Transformers.  If you find a solution that involves changes to *ktrain*, please do let me know, so the changes can be implemented.

**Comment by Niekvdplas** [comment]
I managed to get a fix for this problem by installing the latest development version of Tensorflow, tf-nightly. Now it does work, however starting the epochs takes a bit longer, probably because of allocating memory for the gpus

**Comment by mabu-dev** [comment]
> When I place `t.get_classifier()` within the MirrordStrategy scope, multiple GPUs are used but validation throws an error. I'm not sure why since it works with non-Transformer models. Perhaps, it is a bug in TF2 or transformers library? Or, maybe other things need to be in scope. Not sure.
> 
> In any case, a workaround is to omit the validation data from `get_learner` and validate at end of the multi-gpu training after reloading the model from disk:
> 
> ```python
> # use two GPUs to train
> import os
> os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID";
> os.environ["CUDA_VISIBLE_DEVICES"]="0,1";  
> 
> # load text data
> categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
> from sklearn.datasets import fetch_20newsgroups
> train_b = fetch_20newsgroups(subset='train', categories=categories, shuffle=True)
> test_b = fetch_20newsgroups(subset='test',categories=categories, shuffle=True)
> (x_train, y_train) = (train_b.data, train_b.target)
> (x_test, y_test) = (test_b.data, test_b.target)
> 
> # build, train, and validate model
> import tensorflow as tf
> mirrored_strategy = tf.distribute.MirroredStrategy()
> import ktrain
> from ktrain import text
> MODEL_NAME = 'distilbert-base-uncased'
> t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names)
> trn = t.preprocess_train(x_train, y_train)
> val = t.preprocess_test(x_test, y_test)
> with mirrored_strategy.scope():
>     model = t.get_classifier()
> learner = ktrain.get_learner(model, train_data=trn, batch_size=6)
> learner.fit_onecycle(5e-5, 2)
> learner.save_model('/tmp/my_model')
> learner.load_model('/tmp/my_model', preproc=t)
> learner.validate(val_data=val, class_names=t.get_classes())
> ```
> 
> Two GPUs used during training of the DistilBERT model:
> 
> ```
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 430.64       Driver Version: 430.64       CUDA Version: 10.1     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  TITAN V             Off  | 00000000:21:00.0 Off |                  N/A |
> | 42%   59C    P2   163W / 250W |  11684MiB / 12066MiB |     84%      Default |
> +-------------------------------+----------------------+----------------------+
> |   1  TITAN V             Off  | 00000000:31:00.0 Off |                  N/A |
> | 33%   49C    P2   132W / 250W |  11684MiB / 12066MiB |     84%      Default |
> +-------------------------------+----------------------+----------------------+
> ```
> 
> Output of `learner.validate` at the end:
> 
> ```
>                         precision    recall  f1-score   support
> 
>            alt.atheism       0.93      0.93      0.93       319
>          comp.graphics       0.98      0.95      0.96       389
>                sci.med       0.96      0.97      0.97       396
> soc.religion.christian       0.97      0.97      0.97       398
> 
>               accuracy                           0.96      1502
>              macro avg       0.96      0.96      0.96      1502
>           weighted avg       0.96      0.96      0.96      1502
> ```

Just for clarity, you're not "transfer-learning" anything in this example right? As in this is not fine-tuning but just training the distillbert architecture from scratch?

**Comment by amaiya** [comment]
@mabu-dev  That's incorrect.  This is transfer learning, as we're fine-tuning a pretrained DistilBert model. Hugging Face transformer models are all pretrained. In the example above, the model was pretrained on English text ('distilbert-base-uncased').   If you were building a model for some other language, you would use a different pretrained model.  See [this list of pretrained models](https://huggingface.co/transformers/pretrained_models.html) for more information.

**Comment by mabu-dev** [comment]
@amaiya I don't see you freezing any layers in this examples, doesn't that imply we're training all layers and hence "no transfer learning"? Or are we freeze some layers in the background? 
My understanding is that we need to freeze the embedding layers? I'm sure I'm missing something, sorry for this. But please clarify?

**Comment by amaiya** [comment]
@mabu-dev No problem - happy to clarify.   A simple way to view transfer learning is that it is simply a   way to initialize the weights of  your network by pretraining (in contrast to randomly-initialized weights). Once you pretrain, there are different strategies to fine-tune the network.  If you don't freeze any of the layers, you are essentially fine-tuning the entire network to your dataset.  This is very different than training from scratch as the weights are starting off pretrained on a very large corpus (as opposed to being randomly-initialized).  So, it is still transfer learning even though you're not freezing any layers.

In *ktrain*, by default, we don't freeze any layers for Transformer models.  There's a paper that showed that fine-tuning all the layers for a BERT model performed comparably freezing some of the early layers.  By contrast, for image classification with a ResNet50, freezing the earlier layers is more important in my experience.  

In any case, the `learner` instance has a freeze method that will freeze the earlier Transformer layers and allow you to only fine-tune the custom head (i.e., final randomly-initialized dense layer).  You can experiment with that, if you'd like.  It should, in theory, speed training a little bit, at least.

**Comment by mabu-dev** [comment]
Crystal clear! Thanks a lot.
