### ISSUE TITLE
Binary Classification with BERT 

### ISSUE THREAD

**Issue by sathish331977** [amaiya/ktrain#8]
I was able to successfully train a binary classification using BERT, however the model files turned out be around 3.5 GB ,is this expected.
I ran the inference using these models however i see when it runs i see epoch 1/1 as a message (very briefly) , Am i missing any code that should be used before running the model on new data.

**Comment by amaiya** [comment]
When saving the BERT IMDb model, it looks like the saved model is 2GB.  As an alternative, you can try saving just the weights and reloading the weights of the model using standard Keras commands.

I don't see Epoch 1/1 appearing when making predictions.   Feel free to post the exact commands you're using.
