### ISSUE TITLE
Is it possible to have multi_input or multioutput model

### ISSUE THREAD

**Issue by talhaanwarch** [amaiya/ktrain#87]
In Ktrain , is it possible to have multi_input model. Like two sentence into the model and one out put label. Here is the implementation using TF hub. But i am looking if KTrain support this
https://colab.research.google.com/drive/1O4OeraZWXZUjk1DoQpgCFsaEotEK-OJy

**Comment by amaiya** [comment]
*ktrain* supports custom data formats and models outside of the defaults.  All you have to do is wrap your dataset in a `ktrain.Dataset` subclass, which is simply a Sequence Wrapper for use with custom models.  A detailed tutorial is here:  [Using ktrain with Custom Data Formats and Models](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/develop/tutorials/tutorial-A4-customdata-text_regression_with_extra_regressors.ipynb).

We do not yet support "pre-canned" models that accept two sentences as input, though.  Only binary/multiclass/multilabel text classification and text regression are currently supported. Might be good to add in future, though. The example you posted looks interesting.

**Comment by amaiya** [comment]
Please see [this example notebook on paraphrase detection](https://github.com/amaiya/ktrain/blob/master/examples/text/MRPC-BERT.ipynb) for an example of models that accept two sentences.  Thanks.
