### ISSUE TITLE
ValueError: Error when checking model input: [text_classifier]

### ISSUE THREAD

**Issue by itLek** [amaiya/ktrain#9]
> ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays

[Notebook](https://github.com/itLek/bug_/blob/master/BERT%20ktrain%20bug%20%5BSF%20NLP%20Movie%20Genre%5D%20v1.0.ipynb)

**Comment by amaiya** [comment]
It looks like you forgot to supply `preprocess_mode='bert'` argument to `texts_from_csv`.  BERT is a pretrained model and requires the data to be preprocessed in a specific way.  BERT expects two input arrays (not just the standard one), which is the reason for the error.  Try changing the line to this:
```

(x_train, y_train), (x_test, y_test), preproc = text.texts_from_csv(PATH+'train.csv',
                      'text',                                       
                      label_columns = classes,
                       preprocess_mode='bert',   # HERE'S THE MISSING PARAMETER
                      val_filepath=None, # if None, 10% of data will be used for validation
                      max_features=MAX_WORDS, maxlen=MAXLEN,
                      ngram_range=1)
```

For the next release, we can include a dataset check in *ktrain* that ensures the data is formatted correctly for BERT and outputs a more informative error message.

**Comment by itLek** [comment]
Thank you, worked. Please Add in the tutorial this part of the code.
