### ISSUE TITLE
AttributeError: module 'ktrain.text.preprocessor' has no attribute 'detect_lang'

### ISSUE THREAD

**Issue by david1983** [amaiya/ktrain#90]
/opt/conda/lib/python3.6/site-packages/ktrain/text/eda.py in __init__(self, texts, n_topics, n_features, min_df, max_df, stop_words, model_type, lda_max_iter, lda_mode, token_pattern, verbose, hyperparam_kwargs)
     54                                              lda_max_iter=lda_max_iter, lda_mode=lda_mode,
     55                                              token_pattern=token_pattern,
---> 56                                              hyperparam_kwargs=hyperparam_kwargs)
     57         else:
     58             vectorizer = None

/opt/conda/lib/python3.6/site-packages/ktrain/text/eda.py in train(self, texts, model_type, n_topics, n_features, min_df, max_df, stop_words, lda_max_iter, lda_mode, token_pattern, hyperparam_kwargs)
    122         # adjust defaults based on language detected
    123         if texts is not None:
--> 124             lang = pp.detect_lang(texts)
    125             if lang != 'en':
    126                 stopwords = None if stop_words=='english' else stop_words

AttributeError: module 'ktrain.text.preprocessor' has no attribute 'detect_lang'

**Comment by david1983** [comment]
tried using kaggle ennvironment

**Comment by david1983** [comment]
I've fixed it doing so

ktrain.text.preprocessor.detect_lang = ktrain.text.textutils.detect_lang

**Comment by amaiya** [comment]
@david1983  Thanks for posting issue.  This will be fixed in the next version (to be released soon).

**Comment by amaiya** [comment]
This should now be fixed - thanks.
