### ISSUE TITLE
Is all  community-uploaded Hugging Face transformer models supported?

### ISSUE THREAD

**Issue by WangHexie** [amaiya/ktrain#91]
```
import ktrain
from ktrain import text
MODEL_NAME = 'monologg/scibert_scivocab_uncased'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=label_list)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
learner.fit_onecycle(3e-5, 1)
```
The code runs well while the using the model `'monologg/scibert_scivocab_uncased'` 

but when
Changing model_name to `voidful/albert_chinese_base`  will raise error `OSError: Model name 'voidful/albert_chinese_base' was not found in tokenizers model name list (albert-base-v1, albert-large-v1, albert-xlarge-v1, albert-xxlarge-v1, albert-base-v2, albert-large-v2, albert-xlarge-v2, albert-xxlarge-v2). We assumed 'voidful/albert_chinese_base' was a path, a model identifier, or url to a directory containing vocabulary files named ['spiece.model'] but couldn't find such vocabulary files at this path or url.`

Changing model_name to `adamlin/bert-distil-chinese` will raise error  `ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 14 array(s), for inputs ['output_1', 'output_2', 'output_3', 'output_4', 'output_5', 'output_6', 'output_7', 'output_8', 'output_9', 'output_10', 'output_11', 'output_12', 'output_13', 'output_14'] but instead got the following list of 1 arrays: [<tf.Tensor 'args_3:0' shape=(None, None) dtype=int64>]...`

I have no experience in using bert and other hugging face model, I'm tring to write a colab code for reproducing this error faster. Just open the issue ahead of time.

**Comment by WangHexie** [comment]
oh, I've found out why the first error happened -> [https://huggingface.co/voidful/albert_chinese_base](https://huggingface.co/voidful/albert_chinese_base)
This model have to use `BertTokenizer `.
pretrained hugging face model is really complicated.

**Comment by amaiya** [comment]
In theory, any community-uploaded model should work.  In practice, most work, but a few may cause problems due to issues with the model or transformers library.  To verify that it is a problem with transformers model and not *ktrain*, you can try loading the model yourself with something like:
```python
from transformers import *
model = TFAutoModelForSequenceClassification.from_pretrained(model_name, from_pt=True)
```
where `from_pt` should be set based on whether the community-uploaded model is a PyTorch one or TensorFlow one.

**Comment by khalilruss** [comment]
What was the workaround to use the voidful/albert_chinese_base with ktrain?

**Comment by amaiya** [comment]
If you go to the model hub page for `voidful/albert_chinese_base`, it says that you need to use BertTokenizer with this model, as mentioned above by @WangHexie .

So, you can just set the tokenizer manually to a `BertTokenizer` instance as shown below:

```python
import ktrain
from ktrain import text
MODEL_NAME = 'voidful/albert_chinese_base'  
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=your_label_names)
t.tok = BertTokenizer.from_pretrained(MODEL_NAME)  # set tokenizer manually instead of using AutoTokenizer
t.preprocess_train(x_train, y_train)
```
@WangHexie previously recommended falling back to BertTokenizer automatically in the library, which is a good suggestion and should probably be added.

**Comment by khalilruss** [comment]
Alright makes sense, Thank you. Awesome library btw using it for my dissertation and it has helped a lot
