### ISSUE TITLE
Cannot save visualization of topic model to custom filepath

### ISSUE THREAD

**Issue by stedomedo** [amaiya/ktrain#93]
If I provide a filepath, e.g.
`top_model.visualize_documents(doc_topics=top_model.get_doctopics(), filepath="./outgraph.html")`
then the graph is not stored in the provided html file but instead in `/tmp/t.html`

Should be:

```
if filepath is not None:
            bp.output_file(filepath)
            bp.save(p)
```

https://github.com/amaiya/ktrain/blob/5e927f0e7d09c8782ca4cb090b1fceefe8a3eca5/ktrain/text/eda.py#L450

**Comment by amaiya** [comment]
Thanks for reporting issue.  This fix was included in v0.11.2.
