### ISSUE TITLE
How to reload? Cannot create group in read-only mode! 

### ISSUE THREAD

**Issue by gyunggyung** [amaiya/ktrain#98]
```
learner.fit_onecycle(3e-5, int(epoch), checkpoint_folder = checkpoint_path, callbacks=[tbCallBack])
```
I saved the model through the code above.

However, it is not possible to reload the model. Please tell me how to solve it.

Why read-only?

```
new_model = keras.models.load_model(checkpoint_path + '/weights-20.hdf5')
```

![image](https://user-images.githubusercontent.com/26733242/77403809-26493080-6df4-11ea-8e6f-038018afa981.png)

**Comment by amaiya** [comment]
The `checkpoint_folder` argument saves the weights only at the end of each epoch, not the entire model.  Use `load_weights`, not `load_model:

```python
learner.model.load_weights('checkpoint_path + '/weights-20.hdf5')
```

If you need to save the entire model, use `learner.save_model` and `learner.load_model`.  Transformer models cannot be loaded with `load_model` anyways - you must use `from_pretrained` which is what `learner.load_model` will do.

**Comment by gyunggyung** [comment]
```
learner.load_model
learner.save_model
```
Do you have a document that explains the two functions well?
If I write it the way I used before, I get an error.

**Comment by amaiya** [comment]
The `load_model` and `save_model` methods are simply wrappers to other methods depending on the model used.  For instance, `load_model` simply calls Keras' `load_model` for non-transformer models and calls `from_pretrained` for transformer models.  Same with `load_model`.

Here is a full working example that is confirmed to work on Google colab:
```python
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
from sklearn.datasets import fetch_20newsgroups
train_b = fetch_20newsgroups(subset='train', categories=categories, shuffle=True)
test_b = fetch_20newsgroups(subset='test',categories=categories, shuffle=True)
(x_train, y_train) = (train_b.data, train_b.target)
(x_test, y_test) = (test_b.data, test_b.target)
import ktrain
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=train_b.target_names)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
learner.fit_onecycle(5e-5, 1, checkpoint_folder='/tmp/savedweights')

# load weights into model
learner.model.load_weights('/tmp/savedweights/weights-01.hdf5')

# save model
learner.save_model('/tmp/savedmodel')

# load model
learner.load_model('/tmp/savedmodel', t)

# save and load predictors (which simply save/load both model and t object above
predictor = ktrain.get_predictor(learner.model, t)
predictor.predict('My computer monitor is blurry.') # prints comp.graphics
predictor.save('/tmp/savedpredictor')
predictor = ktrain.load_predictor('/tmp/savedpredictor')
predictor.predict('My computer monitor is blurry.') # prints comp.graphics
```

**Comment by gyunggyung** [comment]
Thank!!!!!
